### ISSUE TITLE
How to import p12 certificate

### ISSUE THREAD

**Issue by rhashi** [yuezk/GlobalProtect-openconnect#103]
I am trying to import the .p12 certificate but I can't figure out how to do it. Does it support importing a .p12 certificate?
Need help......
I am using Manjaro and the current kernel version is 5.14.

**Comment by yuezk** [comment]
@rhashi Please try thefollow steps:

1. Try to convert the .p12 certificate to the .pem format certificate ([reference](https://superuser.com/questions/1252387/openconnect-config-using-pfx-file-on-debian))
    ```
    openssl pkcs12 -in client.p12 -out client.pem
    ```
1. Open the setting dialog of this client and input the parameter `--certificate <path to your client.pem>` to the `Custom Parameters` field. (ref: https://github.com/yuezk/GlobalProtect-openconnect#passing-the-custom-parameters-to-openconnect-cli)

**Comment by yuezk** [comment]
Hi, @rhashi may I know does my solution work?

**Comment by rhashi** [comment]
@yuezk no bro I didn't work. I converted .p12 to .pem and then I pass the custom parameters --certificate ~/Downloads/mycert.pem
But when I try to connect and enter my credentials it says not connected. My credentials are correct as I am already using them on my windows machine.

**Comment by yuezk** [comment]
Sorry about that.

This client will call the OpenConnect command line under the hood. So, if you like, you can use that command line directly. It could provide more info for troubleshooting if an error occurred.

**Comment by JeyP4** [comment]
> nvidia@nvidia:~/Downloads$ sudo openconnect -b gp-dmec.vpn.polimi.it -c /home/nvidia/Downloads/certificate-10518176-20211112.p12 --form-entry main:username=10518176
POST https://gp-dmec.vpn.polimi.it/
Connected to 131.175.19.131:443
Enter PKCS#12 pass phrase:
Using client certificate '10518176@polimi.it'
SSL negotiation with gp-dmec.vpn.polimi.it
Connected to HTTPS on gp-dmec.vpn.polimi.it with ciphersuite (TLS1.2)-(RSA)-(AES-256-GCM)
XML response has no "auth" node
GET https://gp-dmec.vpn.polimi.it/
Connected to 131.175.19.131:443
SSL negotiation with gp-dmec.vpn.polimi.it
Connected to HTTPS on gp-dmec.vpn.polimi.it with ciphersuite (TLS1.2)-(RSA)-(AES-256-GCM)
XML response has no "auth" node
Failed to complete authentication

I have above results.
I have authenticate with username and password which I know.
Can you help me with the syntax line?

Thanks

**Comment by yuezk** [comment]
Closing it for now, if the certificate authentication is still needed, reopen it or report another feature request, I will support it.
