### ISSUE TITLE
How to save multiple gateways

### ISSUE THREAD

**Issue by teklabania** [yuezk/GlobalProtect-openconnect#105]
Hi. The tray icon gives the possibility of switching a gateway. I'm using GlobalProtect-openconnect for months but still didn't figure out how to save multiple gateways and make use of a gateway picker. I can see on the list only one gateway, the one I inserted in the main window before connecting. @yuezk, could you please update README.md (even if the feature is not yet implemented).

**Comment by DMJC** [comment]
Is the select preferred gateway feature designed for connecting to a cluster of Palo Alto firewalls? What I'd like to do is what Teklabania wants to do. When you work at an MSP, you often need to connect to multiple Palo Alto VPNs. What would be good is a way to save multiple Palo Alto VPN connections so you can just choose the one you want to join. Can we get this added as a feature?

**Comment by yuezk** [comment]
Supported in 2.x release.
