### ISSUE TITLE
GlobalProtect login window is empty

### ISSUE THREAD

**Issue by philippulus** [yuezk/GlobalProtect-openconnect#106]
GlobalProtect login windows on Ubuntu 20.04 is empty.
Get the same issue on two different Linux machines.

![GlobalProtectLoginWindowEmpty](https://user-images.githubusercontent.com/89039695/142836677-6623cb0f-6c71-4a51-acf5-0eaf4d8fca5e.png)

**Comment by philippulus** [comment]
Don't come any farther with the than '$ gp-saml-gui' command. 

$ pip3 install https://github.com/dlenski/gp-saml-gui/archive/master.zip
Collecting https://github.com/dlenski/gp-saml-gui/archive/master.zip
  Downloading https://github.com/dlenski/gp-saml-gui/archive/master.zip
     - 164 kB 175 kB/s
Requirement already satisfied: pygobject in /usr/lib/python3/dist-packages (from gp-saml-gui==0.1) (3.36.0)
Requirement already satisfied: requests in /usr/lib/python3/dist-packages (from gp-saml-gui==0.1) (2.22.0)
Requirement already satisfied: pycairo>=1.11.1 in /usr/lib/python3/dist-packages (from pygobject->gp-saml-gui==0.1) (1.16.2)
Building wheels for collected packages: gp-saml-gui
  Building wheel for gp-saml-gui (setup.py) ... done
  Created wheel for gp-saml-gui: filename=gp_saml_gui-0.1-py3-none-any.whl size=22563 sha256=b55dafecbba7a98bc15f2956cc1de8d035a036324816dc54a4f6813829fdb877
  Stored in directory: /tmp/pip-ephem-wheel-cache-aa1pi5st/wheels/e2/0f/fd/0fe4e06555dce4a18ca14842b18d0f07c8fba37c309af8695e
Successfully built gp-saml-gui
Installing collected packages: gp-saml-gui
  WARNING: The script gp-saml-gui is installed in '/home/nicolas/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Successfully installed gp-saml-gui-0.1

$ gp-saml-gui
gp-saml-gui: command not found
nicolas@nicolas-Z97X-UD5H:~$ usage: gp-saml-gui [-h] [--no-verify] [-C COOKIES | -K] [-p | -g] [-c CERT]
-K]: command not found
-g]: command not found
usage:: command not found
$                    [--key KEY] [-v | -q] [-x | -P | -S] [-u]
-P: command not found
-S]: command not found
-q]: command not found
[--key: command not found
$                    [--clientos {Windows,Linux,Mac}] [-f EXTRA]
[--clientos: command not found
$                    server [openconnect_extra [openconnect_extra ...]]
Defaulting to port 8080Listening on port 8080

**Comment by philippulus** [comment]
> Please try [gp-saml-gui](https://github.com/dlenski/gp-saml-gui) to see if it works.

Any idea why the login Window is empty?

**Comment by yuezk** [comment]
Are you using the self-signed certificate?

**Comment by philippulus** [comment]
No, I am just starting the app to try to login.

**Comment by yuezk** [comment]
@philippulus Can you post the log files, which can be found at https://github.com/yuezk/GlobalProtect-openconnect#troubleshooting

**Comment by philippulus** [comment]
I can now use your GP app. The problem is that I had installed the app from the Ubuntu store and this one was making the problem. I have uninstalled it and refresh my system before installing according to your instructions.

**Comment by MartiniBnu** [comment]
I'm already facing the same problem... 

![Screenshot from 2022-01-08 14-01-46](https://user-images.githubusercontent.com/51671529/148652955-25b3a6e2-146a-40d7-80f8-91781cd47772.png)

**Comment by yuezk** [comment]
@MartiniBnu Make sure to install it from the PPA, not the app store.

**Comment by MartiniBnu** [comment]
> @MartiniBnu Make sure to install it from the PPA, not the app store.

It works! Thanks!!!
