### ISSUE TITLE
Unknown prelogin response

### ISSUE THREAD

**Issue by ColdIce1** [yuezk/GlobalProtect-openconnect#11]
Hi,
I've come across a portal that is not supported.
The prelogin response is similar to this:
[https://github.com/gabrielmuras/openconnect-docker/blob/master/PAN_GlobalProtect_protocol_doc.md#pre-login-response](gabrielmuras/openconnect-docker/PAN_GlobalProtect_protocol_doc.md#pre-login-response)

Response is as of follow:
`<?xml version="1.0" encoding="UTF-8" ?>
<prelogin-response>
<status>Success</status>
<ccusername></ccusername>
<autosubmit>false</autosubmit>
<msg></msg>
<newmsg></newmsg>
<authentication-message>Enter login credentials</authentication-message>
<panos-version>1</panos-version><region>NO</region>
</prelogin-response>`

**Comment by ColdIce1** [comment]
Related issue https://github.com/dlenski/openconnect/issues/117

**Comment by yuezk** [comment]
@ColdIce1 Looks like the portal prelogin response doesn't contain the fields for authentication. Can you post out the gateway prelogin response of `https://<SERVER>/ssl-vpn/prelogin.esp`? Thanks.

**Comment by yuezk** [comment]
@ColdIce1 Please upgrade it to 1.2.4 to see if it was fixed.

If not, can you help provide the logs collected from `$HOME/.cache/GlobalProtect-openconnect/gpclient.log`? Thanks.

**Comment by MincingWords** [comment]
When trying this on Arch Linux against vpn.gatech.edu I get an error box saying "Gateway authentication failed. Unknown response for gateway prelogin interface."

The result of https://vpn.gatech.edu/global-protect/prelogin.esp?tmp=tmp&kerberos-support=yes&ipv6-support=yes&clientVer=4100&clientos=Linux is:

`<prelogin-response>
<status>Success</status>
<ccusername/>
<autosubmit>false</autosubmit>
<msg/>
<newmsg/>
<authentication-message>Enter login credentials</authentication-message>
<username-label>Username</username-label>
<password-label>Password</password-label>
<panos-version>1</panos-version>
<saml-default-browser>yes</saml-default-browser>
<region>US</region>
</prelogin-response>`

**Comment by nicolasshu** [comment]
@MincingWords I have the same issue

**Comment by TheRealIndru** [comment]
Hi! I have the same issue.
