### ISSUE TITLE
Bad HighDPI support

### ISSUE THREAD

**Issue by kaimast** [yuezk/GlobalProtect-openconnect#115]
I'm using a HighDPI screen on GNOME/Wayland. The app looks like in the screenshot below and cannot be resized:

![image](https://user-images.githubusercontent.com/4525445/147016302-fa42723a-0e2a-4458-98ec-7bc01609dbf3.png)
![image](https://user-images.githubusercontent.com/4525445/147016420-5300d662-780e-4133-88a0-097972464612.png)

**Comment by yuezk** [comment]
I'm gonna have a 4K monitor soon. Will fix it soon.

**Comment by melkorm** [comment]
Hey 👋🏼 any news on this? also, is there a way to resize the main window? (configuration window allows resizing 🤔 but main window doesn't )

**Comment by yuezk** [comment]
Fixed in 1.4.4

**Comment by melkorm** [comment]
Still the window size is small 🤔 Perhaps as a start we could enable resizing for main window, what do you think?

![Screenshot from 2022-05-16 23-21-39](https://user-images.githubusercontent.com/619996/168684645-b9bee901-0ba1-4927-b5d0-1f7972463ef5.png)

```
➜  ~ gpclient -v
2022-05-16 23:20:53.520 INFO  [241969] [main@25] GlobalProtect started, version: 1.4.4
gpclient 
```

**Comment by markcellus** [comment]
Yes same here, window is still small

**Comment by yuezk** [comment]
Weird. I tested it with ubuntu 22.04 on the virtual machine and set the scale to 200%. It works fine.
Can you guys post what's your configuration of the display settings?

**Comment by yuezk** [comment]
Just right-mouse click on the desktop and select Display Settings or something alike.

**Comment by yuezk** [comment]
My solution in 1.4.4 is simple. Just add the `QT_AUTO_SCREEN_SCALE_FACTOR` environment variable if it wasn't set according to my research.

You can try to export the `QT_AUTO_SCREEN_SCALE_FACTOR=1` and run `gpclient` in the terminal to see if it works.

**Comment by melkorm** [comment]
![Screenshot from 2022-05-18 09-54-32](https://user-images.githubusercontent.com/619996/168987423-a490fa5c-356d-49f5-8b56-ced9c5a92212.png)

Setting `QT_AUTO_SCREEN_SCALE_FACTOR=1` fixes the issue

**Comment by markcellus** [comment]
Thanks! `QT_AUTO_SCREEN_SCALE_FACTOR` would apply globally. Would changing its value cause issues with other applications on the system? :thinking:

**Comment by melkorm** [comment]
@markcellus I've added it just to desktop entry so it shouldn't affect anything else 🤔

**Comment by markcellus** [comment]
Ah that worked! Thanks!

**Comment by yuezk** [comment]
I will add it to the desktop entry in the next release.

**Comment by yuezk** [comment]
Added in 1.4.5, closing it.
