### ISSUE TITLE
After few seconds connection, GlobalProtect every time will disconnecting. What is mean?

### ISSUE THREAD

**Issue by agabit** [yuezk/GlobalProtect-openconnect#116]
[<a href="https://imgbb.com/"><img src="https://i.ibb.co/Tg3bDR9/2021-12-27-12-18.png" alt="2021-12-27-12-18" border="0"></a>](url)
[<a href="https://imgbb.com/"><img src="https://i.ibb.co/HqzKL5X/2021-12-27-12-17.png" alt="2021-12-27-12-17" border="0"></a>](url)

**Comment by baccione** [comment]
Same here. It works with a previous CLI only version of globalprotect.

**Comment by aloisdg** [comment]
I think I may have this problem too.

![fail_gpc](https://user-images.githubusercontent.com/3449303/148085406-2cbfaa32-3226-4e76-86ed-2427dbf61ec2.gif)

I am using v1.3.4-3 on 5.10.84-1-MANJARO.

**Comment by aloisdg** [comment]
Note that in my case a simple reboot fixed it. [\o/](https://www.youtube.com/watch?v=nn2FB1P_Mn8)

**Comment by jmiezitis** [comment]
On ubuntu 21.10 I see this behavior, also the following in syslog:
audit: type=1400 audit(1641443100.643:304): apparmor="DENIED" operation="open" profile="snap.globalprotect-openconnect.gpservice" name="/dev/net/tun" pid=5900 comm="openconnect" requested_mask="wr" denied_mask="wr" fsuid=0 ouid=0
and other similar lines.
Attempted to create an apparmor profile for this but got nowhere.

**Comment by yuezk** [comment]
Hi guys, when this issue happens, view the log file at `~/.cache/GlobalProtect-openconnect/gpclient.log` and see what's the output before the disconnection.

@jmiezitis Please try to install it from PPA (see [README.md](https://github.com/yuezk/GlobalProtect-openconnect#linux-mint-ubuntu-1804-or-later)). The snap version is not well tested, still in the `edge` channel.

**Comment by jmiezitis** [comment]
Install from the PPA works better although it didn't update any resolvers but that is a small and easily worked around issue.
Thank you for your work.

**Comment by jmiezitis** [comment]
Looking at the logs:
2022-01-07 13:09:49.455 INFO  [3785490] [GPClient::onVPNLogAvailable@489] /usr/share/vpnc-scripts/vpnc-script: 502: cannot open /var/run/vpnc/resolv.conf-backup: No such file
2022-01-07 13:09:49.456 INFO  [3785490] [GPClient::onVPNLogAvailable@489] Script '/usr/share/vpnc-scripts/vpnc-script' returned error 2
This is easily addressed and not really a reportable issue anymore.

**Comment by agabit** [comment]
> Hi guys, when this issue happens, view the log file at `~/.cache/GlobalProtect-openconnect/gpclient.log` and see what's the output before the disconnection.
> 
> @jmiezitis Please uninstall the snap version and try to install it from PPA (see [README.md](https://github.com/yuezk/GlobalProtect-openconnect#linux-mint-ubuntu-1804-or-later)). The snap version is not well tested, still in the `edge` channel.

This method helped. Thx man :)
