### ISSUE TITLE
Privatage escalation to root via Custom Parameters option

### ISSUE THREAD

**Issue by cam404** [yuezk/GlobalProtect-openconnect#118]
Any command you put in the Custom parameters field with --script option field is run as root without auth. You basically do anything you want if you have user access to a system.
example
--script="whoami > /out.txt"
 output:
root

**Comment by yuezk** [comment]
@cam404, thanks for your report. Is it the same problem as #113?

**Comment by cam404** [comment]
yep, i must have missed that previous report.
