### ISSUE TITLE
sslError not implemented in samlloginwindow.cpp

### ISSUE THREAD

**Issue by jreo** [yuezk/GlobalProtect-openconnect#119]
When the certificate on the gateway is expired or invalid, the window stays open, displays the ERR_CERT_AUTHORITY_INVALID message and does not handle the error.
![Sem título](https://user-images.githubusercontent.com/33395101/151075298-c9563608-ea53-41cf-bfd4-33842cf8c5c5.jpg)

**Comment by yuezk** [comment]
Will take care of it in the future release.

**Comment by jreo** [comment]
The same problem occur in normal login, if the certificate is expired or invalid the OpenConnect return an option to trust in the server with suggestion to use -servercert pin-sha256:s2/XXXXXXXXXXXXXXX. Which in terms of security doesn't make any sense. The Client GUI does not notice this, it proceeds as if it is connected.

**Comment by yuezk** [comment]
No longer a problem in 2.x, closing.
