### ISSUE TITLE
No tray icon when using with Tray Icons Reloaded on Wayland

### ISSUE THREAD

**Issue by tunix** [yuezk/GlobalProtect-openconnect#123]
I use this app on Fedora Silverblue 35 and it works just fine. (thank you!) But on wayland, it doesn't show its tray icon properly. I'm not sure whether it's related to me using tray icons reloaded extension instead of appindicator extension.

**Comment by klDen** [comment]
Hey, I'm on sway/wayland and I can see the tray properly. 
![image](https://user-images.githubusercontent.com/5478260/163070194-2b098536-6964-44d8-8f6d-b6ae42c9b7f9.png)

**Comment by valentingregoire** [comment]
I am working on Fedora 37 (Gnome 43.3), and I don't see the tray icon either with the Tray Icons Reloaded, nor with the suggested extension in the [docs](https://github.com/yuezk/GlobalProtect-openconnect#display-the-system-tray-icon-on-gnome-40).
