### ISSUE TITLE
Failed compilation

### ISSUE THREAD

**Issue by BangShiuh** [yuezk/GlobalProtect-openconnect#130]
./scripts/install-ubuntu.sh
Hit:1 http://us.archive.ubuntu.com/ubuntu focal InRelease
Hit:2 http://us.archive.ubuntu.com/ubuntu focal-updates InRelease              
Hit:3 http://us.archive.ubuntu.com/ubuntu focal-security InRelease             
Hit:4 http://ppa.launchpad.net/system76/pop/ubuntu focal InRelease             
Hit:5 http://us.archive.ubuntu.com/ubuntu focal-backports InRelease            
Hit:6 http://apt.pop-os.org/proprietary focal InRelease                        
Ign:7 https://launchpad.net/~dwmw2/+archive/ubuntu/openconnect focal InRelease 
Err:8 https://launchpad.net/~dwmw2/+archive/ubuntu/openconnect focal Release
  404  Not Found [IP: 2001:67c:1560:8003::8004 443]
Reading package lists... Done
E: The repository 'https://launchpad.net/~dwmw2/+archive/ubuntu/openconnect focal Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

**Comment by yuezk** [comment]
I haven't met this error. How about installing it directly instead of building it?

**Comment by yuezk** [comment]
Sorry, just noticed you opened another issue. #129 . I'll try it in my VM.
