### ISSUE TITLE
Stale /etc/resolv.conf after system rebooted without disconnecting from VPN

### ISSUE THREAD

**Issue by bogen85** [yuezk/GlobalProtect-openconnect#132]
version: ```globalprotect-openconnect-1.4.1-1.1.x86_64```

My /etc/resolv.conf is a symlink to /usr/lib/systemd/resolv.conf

My system rebooted while GlobalProtect-openconnect was connected.

After logging back in, names were not being resolved.

I checked /etc/resolv.conf, saw it was stale. I redid the symlink and realized that /usr/lib/systemd/resolv.conf had been overwritten.

Thankfully I was able to copy over  /usr/lib/systemd/resolv.conf from another system.

Not sure how this could be mitigated, but I can think of a few ways.

1. If /etc/resolv.conf is a symlink, remove the symlink and write a file rather then overwriting what /etc/resolv.conf is pointing to?
2. Make a backup of /etc/resolv.conf in /etc (not sure of a good name)
3. Add an option to not overwrite/restore /etc/resolv.conf (Some VPN cases, specifially mine, don't rely on name resolution for the network being connecting to).

**Comment by jardon-u** [comment]
I think I got the same issue. No name resolution working after reboot. wasn't expecting this package to harm my system.

**Comment by log02** [comment]
This helped me to fix my system: https://askubuntu.com/questions/812714/run-resolvconf-resolv-conf-gets-erased-each-time-i-restart-and-i-cant-use-int

**Comment by bogen85** [comment]
@log02 I'm using almalinux and there is no such resolvconf package available. I'm using systemd-resolved for name resolution.

**Comment by bogen85** [comment]
After reading the systemd-resolved documentation I see that the symlink should be:

```/etc/resolv.conf -> /run/systemd/resolve/stub-resolv.conf```

and not:

```/etc/resolv.conf -> /usr/lib/systemd/resolv.conf```

So, it was my mistake that led to /etc/resolv.conf being invalid on reboot.

Since ```/run/systemd/resolve/stub-resolv.conf``` is rewritten during system startup, it was stale before a system reboot it won't be after the reboot is compete.

Closing this issue.
