### ISSUE TITLE
Can not find application logs

### ISSUE THREAD

**Issue by alex-k86** [yuezk/GlobalProtect-openconnect#135]
Hello!
Readme says that logs can be found in `~/.cache/GlobalProtect-openconnect/gpclient.log` but after recent updates, I can not find logs in the specified folder.

Thank you for the app it is awesome :+1:

**Comment by yuezk** [comment]
The log file is removed due to security concerns. You can view logs by running the `gpclient` command in the Terminal.

**Comment by markcellus** [comment]
Came here to post an issue about this. What were the security concerns? Aren't those concerns still present if logging is still possible via terminal command?

**Comment by yuezk** [comment]
@markcellus The security concern is that the sensitive information wasn't redacted from the log entries. For the VPN gateway, the SAML gateway response. etc. I don't think this security concern is still valid when launching via the terminal.

**Comment by ysiivan** [comment]
> The log file is removed due to security concerns. You can view logs by running the `gpclient` command in the Terminal.

1.4.1 on Manjaro. ```gpclient``` fails to login, ```openconnect``` from command line works.  
Trying to troubleshoot and I don't see log entries (besides the initial greeting line) being written when ```gpclient``` is launched from the terminal.
```bash
[awesome@acer paloalto]$ gpclient
2022-05-13 09:51:08.199 INFO  [5856] [main@23] GlobalProtect started, version: 1.4.1
[awesome@acer paloalto]$ 
```

**Comment by yuezk** [comment]
@ysiivan Can you try to install the AUR version from https://aur.archlinux.org/packages/globalprotect-openconnect-git?

**Comment by w0d4** [comment]
Hi, I just wanted to mention, that I have the exact same problem. My login fails right after clicking connect without any useful error.
I wanted to see the logs to debug the problem on my side.
I only get the one log line and nothing more. The windows opens, but no more log output.
It works if I run it as root, but then it crashes with the following line:
`[26549:26549:0518/094530.118478:ERROR:zygote_host_impl_linux.cc(90)] Running as root without --no-sandbox is not supported. See https://crbug.com/638180`

Is there any possibility to get the log output as normal user in the shell?

**Comment by ysiivan** [comment]
@yuezk  Pulled and compiled 1.4.4 from github. Entries are showing in the terminal for non-sudo user.

**Comment by yuezk** [comment]
> Pulled and compiled 1.4.4 from github. Entries are showing in the terminal for non-sudo user.

@ysiivan So your problem is resolved?

@w0d4 It's not recommended to run `gpclient` as root. You can try to compile it from the source code.
