### ISSUE TITLE
Better detection of openconnect failing to launch

### ISSUE THREAD

**Issue by azonenberg** [yuezk/GlobalProtect-openconnect#136]
I set up a new laptop and copied my home directory (including a globalprotect-openconnect install)  over to it, but was unable to log into the VPN. The GUI stayed hung on the "connecting" state.

After some investigation I found that I had forgotten to install the openconnect client on the system. It would be nice if your tool would detect openconnect not being found / not starting and display a nice error message rather than silently hanging.

**Comment by markcellus** [comment]
Does a more detailed error show up in the logs? The log file has been removed (see https://github.com/yuezk/GlobalProtect-openconnect/issues/135#issuecomment-1080158798) so it can no longer be viewed.

> The log file is removed due to security concerns. 

So the only way to check the logs would be to start the app from the terminal.

**Comment by azonenberg** [comment]
That was the first thing I did. It printed out a bunch of XML blobs from the SAML authentication, then nothing. No indication of why it was waiting.

**Comment by yuezk** [comment]
No longer a problem in 2.x release, which won't use the openconnect binary, instead, we are using the shared openconnect library.
