### ISSUE TITLE
debian 11 bullseye

### ISSUE THREAD

**Issue by ng0177** [yuezk/GlobalProtect-openconnect#140]
seems not to work out of the box; guessing [glibc](https://tracker.debian.org/pkg/glibc) may be a problem? Thanks.

**Comment by martindoublem** [comment]
I am faced with issues building on bullseye as well, on my end. I have to build as I am attempting to build on armv7 infrastructure.

`[ 79%] Building CXX object GPClient/CMakeFiles/gpclient.dir/main.cpp.o
gmake[2]: *** [GPClient/CMakeFiles/gpclient.dir/build.make:158: GPClient/CMakeFiles/gpclient.dir/gatewayauthenticator.cpp.o] Error 1
gmake[2]: *** Waiting for unfinished jobs....
In file included from /home/pi/dev/GlobalProtect-openconnect/build/GPClient/plog/src/plog-GPClient/include/plog/Appenders/IAppender.h:2,
                 from /home/pi/dev/GlobalProtect-openconnect/build/GPClient/plog/src/plog-GPClient/include/plog/Logger.h:2,
                 from /home/pi/dev/GlobalProtect-openconnect/build/GPClient/plog/src/plog-GPClient/include/plog/Log.h:7,
                 from /home/pi/dev/GlobalProtect-openconnect/GPClient/gphelper.cpp:9:
/home/pi/dev/GlobalProtect-openconnect/build/GPClient/plog/src/plog-GPClient/include/plog/Record.h: In instantiation of ‘plog::Record& plog::Record::operator<<(const T&) [with T = QByteArray]’:
/home/pi/dev/GlobalProtect-openconnect/GPClient/gphelper.cpp:52:45:   required from here
/home/pi/dev/GlobalProtect-openconnect/build/GPClient/plog/src/plog-GPClient/include/plog/Record.h:240:23: error: ambiguous overload for ‘operator<<’ (operand types are ‘plog::util::nostringstream’ {aka ‘std::__cxx11::basic_ostringstream<char>’} and ‘const QByteArray’)
  240 |             m_message << data;
      |             ~~~~~~~~~~^~~~~~~
In file included from /usr/include/c++/10/istream:39,
                 from /usr/include/c++/10/sstream:38,
                 from /home/pi/dev/GlobalProtect-openconnect/build/GPClient/plog/src/plog-GPClient/include/plog/Util.h:6,
                 from /home/pi/dev/GlobalProtect-openconnect/build/GPClient/plog/src/plog-GPClient/include/plog/Record.h:4,
                 from /home/pi/dev/GlobalProtect-openconnect/build/GPClient/plog/src/plog-GPClient/include/plog/Appenders/IAppender.h:2,
                 from /home/pi/dev/GlobalProtect-openconnect/build/GPClient/plog/src/plog-GPClient/include/plog/Logger.h:2,
                 from /home/pi/dev/GlobalProtect-openconnect/build/GPClient/plog/src/plog-GPClient/include/plog/Log.h:7,
                 from /home/pi/dev/GlobalProtect-openconnect/GPClient/gphelper.cpp:9:
/usr/include/c++/10/ostream:166:7: note: candidate: ‘std::basic_ostream<_CharT, _Traits>::__ostream_type& std::basic_ostream<_CharT, _Traits>::operator<<(long int) [with _CharT = char; _Traits = std::char_traits<char>; std::basic_ostream<_CharT, _Traits>::__ostream_type = std::basic_ostream<char>]’
  166 |       operator<<(long __n)
      |       ^~~~~~~~
/usr/include/c++/10/ostream:170:7: note: candidate: ‘std::basic_ostream<_CharT, _Traits>::__ostream_type& std::basic_ostream<_CharT, _Traits>::operator<<(long unsigned int) [with _CharT = char; _Traits = std::char_traits<char>; std::basic_ostream<_CharT, _Traits>::__ostream_type = std::basic_ostream<char>]’
  170 |       operator<<(unsigned long __n)
      |       ^~~~~~~~
/usr/include/c++/10/ostream:174:7: note: candidate: ‘std::basic_ostream<_CharT, _Traits>::__ostream_type& std::basic_ostream<_CharT, _Traits>::operator<<(bool) [with _CharT = char; _Traits = std::char_traits<char>; std::basic_ostream<_CharT, _Traits>::__ostream_type = std::basic_ostream<char>]’
  174 |       operator<<(bool __n)
      |       ^~~~~~~~
In file included from /usr/include/c++/10/ostream:784,
                 from /usr/include/c++/10/istream:39,
                 from /usr/include/c++/10/sstream:38,
                 from /home/pi/dev/GlobalProtect-openconnect/build/GPClient/plog/src/plog-GPClient/include/plog/Util.h:6,
                 from /home/pi/dev/GlobalProtect-openconnect/build/GPClient/plog/src/plog-GPClient/include/plog/Record.h:4,
                 from /home/pi/dev/GlobalProtect-openconnect/build/GPClient/plog/src/plog-GPClient/include/plog/Appenders/IAppender.h:2,
                 from /home/pi/dev/GlobalProtect-openconnect/build/GPClient/plog/src/plog-GPClient/include/plog/Logger.h:2,
                 from /home/pi/dev/GlobalProtect-openconnect/build/GPClient/plog/src/plog-GPClient/include/plog/Log.h:7,
                 from /home/pi/dev/GlobalProtect-openconnect/GPClient/gphelper.cpp:9:
/usr/include/c++/10/bits/ostream.tcc:91:5: note: candidate: ‘std::basic_ostream<_CharT, _Traits>& std::basic_ostream<_CharT, _Traits>::operator<<(short int) [with _CharT = char; _Traits = std::char_traits<char>]’
   91 |     basic_ostream<_CharT, _Traits>::
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/c++/10/istream:39,
                 from /usr/include/c++/10/sstream:38,
                 from /home/pi/dev/GlobalProtect-openconnect/build/GPClient/plog/src/plog-GPClient/include/plog/Util.h:6,
                 from /home/pi/dev/GlobalProtect-openconnect/build/GPClient/plog/src/plog-GPClient/include/plog/Record.h:4,
                 from /home/pi/dev/GlobalProtect-openconnect/build/GPClient/plog/src/plog-GPClient/include/plog/Appenders/IAppender.h:2,
                 from /home/pi/dev/GlobalProtect-openconnect/build/GPClient/plog/src/plog-GPClient/include/plog/Logger.h:2,
                 from /home/pi/dev/GlobalProtect-openconnect/build/GPClient/plog/src/plog-GPClient/include/plog/Log.h:7,
                 from /home/pi/dev/GlobalProtect-openconnect/GPClient/gphelper.cpp:9:
/usr/include/c++/10/ostream:181:7: note: candidate: ‘std::basic_ostream<_CharT, _Traits>::__ostream_type& std::basic_ostream<_CharT, _Traits>::operator<<(short unsigned int) [with _CharT = char; _Traits = std::char_traits<char>; std::basic_ostream<_CharT, _Traits>::__ostream_type = std::basic_ostream<char>]’
  181 |       operator<<(unsigned short __n)
      |       ^~~~~~~~
In file included from /usr/include/c++/10/ostream:784,
                 from /usr/include/c++/10/istream:39,
                 from /usr/include/c++/10/sstream:38,
                 from /home/pi/dev/GlobalProtect-openconnect/build/GPClient/plog/src/plog-GPClient/include/plog/Util.h:6,
                 from /home/pi/dev/GlobalProtect-openconnect/build/GPClient/plog/src/plog-GPClient/include/plog/Record.h:4,
                 from /home/pi/dev/GlobalProtect-openconnect/build/GPClient/plog/src/plog-GPClient/include/plog/Appenders/IAppender.h:2,
                 from /home/pi/dev/GlobalProtect-openconnect/build/GPClient/plog/src/plog-GPClient/include/plog/Logger.h:2,
                 from /home/pi/dev/GlobalProtect-openconnect/build/GPClient/plog/src/plog-GPClient/include/plog/Log.h:7,
                 from /home/pi/dev/GlobalProtect-openconnect/GPClient/gphelper.cpp:9:
/usr/include/c++/10/bits/ostream.tcc:105:5: note: candidate: ‘std::basic_ostream<_CharT, _Traits>& std::basic_ostream<_CharT, _Traits>::operator<<(int) [with _CharT = char; _Traits = std::char_traits<char>]’
  105 |     basic_ostream<_CharT, _Traits>::
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/c++/10/istream:39,
                 from /usr/include/c++/10/sstream:38,
                 from /home/pi/dev/GlobalProtect-openconnect/build/GPClient/plog/src/plog-GPClient/include/plog/Util.h:6,
                 from /home/pi/dev/GlobalProtect-openconnect/build/GPClient/plog/src/plog-GPClient/include/plog/Record.h:4,
                 from /home/pi/dev/GlobalProtect-openconnect/build/GPClient/plog/src/plog-GPClient/include/plog/Appenders/IAppender.h:2,
                 from /home/pi/dev/GlobalProtect-openconnect/build/GPClient/plog/src/plog-GPClient/include/plog/Logger.h:2,
                 from /home/pi/dev/GlobalProtect-openconnect/build/GPClient/plog/src/plog-GPClient/include/plog/Log.h:7,
                 from /home/pi/dev/GlobalProtect-openconnect/GPClient/gphelper.cpp:9:
/usr/include/c++/10/ostream:192:7: note: candidate: ‘std::basic_ostream<_CharT, _Traits>::__ostream_type& std::basic_ostream<_CharT, _Traits>::operator<<(unsigned int) [with _CharT = char; _Traits = std::char_traits<char>; std::basic_ostream<_CharT, _Traits>::__ostream_type = std::basic_ostream<char>]’
  192 |       operator<<(unsigned int __n)
      |       ^~~~~~~~
/usr/include/c++/10/ostream:201:7: note: candidate: ‘std::basic_ostream<_CharT, _Traits>::__ostream_type& std::basic_ostream<_CharT, _Traits>::operator<<(long long int) [with _CharT = char; _Traits = std::char_traits<char>; std::basic_ostream<_CharT, _Traits>::__ostream_type = std::basic_ostream<char>]’
  201 |       operator<<(long long __n)
      |       ^~~~~~~~
/usr/include/c++/10/ostream:205:7: note: candidate: ‘std::basic_ostream<_CharT, _Traits>::__ostream_type& std::basic_ostream<_CharT, _Traits>::operator<<(long long unsigned int) [with _CharT = char; _Traits = std::char_traits<char>; std::basic_ostream<_CharT, _Traits>::__ostream_type = std::basic_ostream<char>]’
  205 |       operator<<(unsigned long long __n)
      |       ^~~~~~~~
/usr/include/c++/10/ostream:220:7: note: candidate: ‘std::basic_ostream<_CharT, _Traits>::__ostream_type& std::basic_ostream<_CharT, _Traits>::operator<<(double) [with _CharT = char; _Traits = std::char_traits<char>; std::basic_ostream<_CharT, _Traits>::__ostream_type = std::basic_ostream<char>]’
  220 |       operator<<(double __f)
      |       ^~~~~~~~
/usr/include/c++/10/ostream:224:7: note: candidate: ‘std::basic_ostream<_CharT, _Traits>::__ostream_type& std::basic_ostream<_CharT, _Traits>::operator<<(float) [with _CharT = char; _Traits = std::char_traits<char>; std::basic_ostream<_CharT, _Traits>::__ostream_type = std::basic_ostream<char>]’
  224 |       operator<<(float __f)
      |       ^~~~~~~~
/usr/include/c++/10/ostream:232:7: note: candidate: ‘std::basic_ostream<_CharT, _Traits>::__ostream_type& std::basic_ostream<_CharT, _Traits>::operator<<(long double) [with _CharT = char; _Traits = std::char_traits<char>; std::basic_ostream<_CharT, _Traits>::__ostream_type = std::basic_ostream<char>]’
  232 |       operator<<(long double __f)
      |       ^~~~~~~~
/usr/include/c++/10/ostream:245:7: note: candidate: ‘std::basic_ostream<_CharT, _Traits>::__ostream_type& std::basic_ostream<_CharT, _Traits>::operator<<(const void*) [with _CharT = char; _Traits = std::char_traits<char>; std::basic_ostream<_CharT, _Traits>::__ostream_type = std::basic_ostream<char>]’
  245 |       operator<<(const void* __p)
      |       ^~~~~~~~
In file included from /home/pi/dev/GlobalProtect-openconnect/build/GPClient/plog/src/plog-GPClient/include/plog/Appenders/IAppender.h:2,
                 from /home/pi/dev/GlobalProtect-openconnect/build/GPClient/plog/src/plog-GPClient/include/plog/Logger.h:2,
                 from /home/pi/dev/GlobalProtect-openconnect/build/GPClient/plog/src/plog-GPClient/include/plog/Log.h:7,
                 from /home/pi/dev/GlobalProtect-openconnect/GPClient/gphelper.cpp:9:
/home/pi/dev/GlobalProtect-openconnect/build/GPClient/plog/src/plog-GPClient/include/plog/Record.h:58:21: note: candidate: ‘void plog::detail::operator<<(plog::util::nostringstream&, const char*)’
   58 |         inline void operator<<(util::nostringstream& stream, const char* data)
      |                     ^~~~~~~~
In file included from /home/pi/dev/GlobalProtect-openconnect/build/GPClient/plog/src/plog-GPClient/include/plog/Appenders/IAppender.h:2,
                 from /home/pi/dev/GlobalProtect-openconnect/build/GPClient/plog/src/plog-GPClient/include/plog/Logger.h:2,
                 from /home/pi/dev/GlobalProtect-openconnect/build/GPClient/plog/src/plog-GPClient/include/plog/Log.h:7,
                 from /home/pi/dev/GlobalProtect-openconnect/GPClient/gphelper.cpp:9:
/home/pi/dev/GlobalProtect-openconnect/build/GPClient/plog/src/plog-GPClient/include/plog/Record.h:93:143: note: candidate: ‘typename plog::detail::meta::enableIf<(! !(sizeof (static_cast<std::__cxx11::basic_string<char> >(declval<T>())) + sizeof (T*))), void>::type plog::detail::operator<<(plog::util::nostringstream&, const T&) [with T = QByteArray; typename plog::detail::meta::enableIf<(! !(sizeof (static_cast<std::__cxx11::basic_string<char> >(declval<T>())) + sizeof (T*))), void>::type = void; plog::util::nostringstream = std::__cxx11::basic_ostringstream<char>]’
   93 | !!(sizeof(static_cast<std::basic_string<util::nchar> >(meta::declval<T>())) + sizeof(T*)), void>::type operator<<(util::nostringstream& stream, const T& data)
      |                                                                                                        ^~~~~~~~

/home/pi/dev/GlobalProtect-openconnect/build/GPClient/plog/src/plog-GPClient/include/plog/Record.h:100:143: note: candidate: ‘typename plog::detail::meta::enableIf<(! !(sizeof (declval<Container>().begin()) + sizeof (declval<Container>().end()))), void>::type plog::detail::operator<<(plog::util::nostringstream&, const Container&) [with Container = QByteArray; typename plog::detail::meta::enableIf<(! !(sizeof (declval<Container>().begin()) + sizeof (declval<Container>().end()))), void>::type = void; plog::util::nostringstream = std::__cxx11::basic_ostringstream<char>]’
  100 | !!(sizeof(meta::declval<Container>().begin()) + sizeof(meta::declval<Container>().end())), void>::type operator<<(util::nostringstream& stream, const Container& data)
      |                                                                                                        ^~~~~~~~

In file included from /usr/include/c++/10/istream:39,
                 from /usr/include/c++/10/sstream:38,
                 from /home/pi/dev/GlobalProtect-openconnect/build/GPClient/plog/src/plog-GPClient/include/plog/Util.h:6,
                 from /home/pi/dev/GlobalProtect-openconnect/build/GPClient/plog/src/plog-GPClient/include/plog/Record.h:4,
                 from /home/pi/dev/GlobalProtect-openconnect/build/GPClient/plog/src/plog-GPClient/include/plog/Appenders/IAppender.h:2,
                 from /home/pi/dev/GlobalProtect-openconnect/build/GPClient/plog/src/plog-GPClient/include/plog/Logger.h:2,
                 from /home/pi/dev/GlobalProtect-openconnect/build/GPClient/plog/src/plog-GPClient/include/plog/Log.h:7,
                 from /home/pi/dev/GlobalProtect-openconnect/GPClient/gphelper.cpp:9:
/usr/include/c++/10/ostream:511:5: note: candidate: ‘std::basic_ostream<_CharT, _Traits>& std::operator<<(std::basic_ostream<_CharT, _Traits>&, char) [with _CharT = char; _Traits = std::char_traits<char>]’
  511 |     operator<<(basic_ostream<_CharT, _Traits>& __out, char __c)
      |     ^~~~~~~~
/usr/include/c++/10/ostream:517:5: note: candidate: ‘std::basic_ostream<char, _Traits>& std::operator<<(std::basic_ostream<char, _Traits>&, char) [with _Traits = std::char_traits<char>]’
  517 |     operator<<(basic_ostream<char, _Traits>& __out, char __c)
      |     ^~~~~~~~
/usr/include/c++/10/ostream:523:5: note: candidate: ‘std::basic_ostream<char, _Traits>& std::operator<<(std::basic_ostream<char, _Traits>&, signed char) [with _Traits = std::char_traits<char>]’
  523 |     operator<<(basic_ostream<char, _Traits>& __out, signed char __c)
      |     ^~~~~~~~
/usr/include/c++/10/ostream:528:5: note: candidate: ‘std::basic_ostream<char, _Traits>& std::operator<<(std::basic_ostream<char, _Traits>&, unsigned char) [with _Traits = std::char_traits<char>]’
  528 |     operator<<(basic_ostream<char, _Traits>& __out, unsigned char __c)
      |     ^~~~~~~~
In file included from /usr/include/c++/10/ostream:784,
                 from /usr/include/c++/10/istream:39,
                 from /usr/include/c++/10/sstream:38,
                 from /home/pi/dev/GlobalProtect-openconnect/build/GPClient/plog/src/plog-GPClient/include/plog/Util.h:6,
                 from /home/pi/dev/GlobalProtect-openconnect/build/GPClient/plog/src/plog-GPClient/include/plog/Record.h:4,
                 from /home/pi/dev/GlobalProtect-openconnect/build/GPClient/plog/src/plog-GPClient/include/plog/Appenders/IAppender.h:2,
                 from /home/pi/dev/GlobalProtect-openconnect/build/GPClient/plog/src/plog-GPClient/include/plog/Logger.h:2,
                 from /home/pi/dev/GlobalProtect-openconnect/build/GPClient/plog/src/plog-GPClient/include/plog/Log.h:7,
                 from /home/pi/dev/GlobalProtect-openconnect/GPClient/gphelper.cpp:9:
/usr/include/c++/10/bits/ostream.tcc:321:5: note: candidate: ‘std::basic_ostream<_CharT, _Traits>& std::operator<<(std::basic_ostream<_CharT, _Traits>&, const char*) [with _CharT = char; _Traits = std::char_traits<char>]’
  321 |     operator<<(basic_ostream<_CharT, _Traits>& __out, const char* __s)
      |     ^~~~~~~~
In file included from /usr/include/c++/10/istream:39,
                 from /usr/include/c++/10/sstream:38,
                 from /home/pi/dev/GlobalProtect-openconnect/build/GPClient/plog/src/plog-GPClient/include/plog/Util.h:6,
                 from /home/pi/dev/GlobalProtect-openconnect/build/GPClient/plog/src/plog-GPClient/include/plog/Record.h:4,
                 from /home/pi/dev/GlobalProtect-openconnect/build/GPClient/plog/src/plog-GPClient/include/plog/Appenders/IAppender.h:2,
                 from /home/pi/dev/GlobalProtect-openconnect/build/GPClient/plog/src/plog-GPClient/include/plog/Logger.h:2,
                 from /home/pi/dev/GlobalProtect-openconnect/build/GPClient/plog/src/plog-GPClient/include/plog/Log.h:7,
                 from /home/pi/dev/GlobalProtect-openconnect/GPClient/gphelper.cpp:9:
/usr/include/c++/10/ostream:606:5: note: candidate: ‘std::basic_ostream<char, _Traits>& std::operator<<(std::basic_ostream<char, _Traits>&, const char*) [with _Traits = std::char_traits<char>]’
  606 |     operator<<(basic_ostream<char, _Traits>& __out, const char* __s)
      |     ^~~~~~~~
gmake[2]: *** [GPClient/CMakeFiles/gpclient.dir/build.make:197: GPClient/CMakeFiles/gpclient.dir/gphelper.cpp.o] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:360: GPClient/CMakeFiles/gpclient.dir/all] Error 2
gmake: *** [Makefile:149: all] Error 2`

**Comment by martindoublem** [comment]
Sorry for how long this is, but it is the only way I thought of transcribing the whole error, without using a pastebin.

**Comment by gentlesystems** [comment]
It does seem to work for me on bookworm now, with the updated glibc.  Of course, it also works to add the ubuntu repo to the sources list and simply install the package.  For bullseye, I'm stuck on 1.3 of this software because of the glibc dependency.
