### ISSUE TITLE
Enhancement: monochrome icons for taskbar (optional)

### ISSUE THREAD

**Issue by TS-CUBED** [yuezk/GlobalProtect-openconnect#144]
Firsts of all: a great thanks and kudos for making GlobalProtect useable. The proprietary app is terrible. This one in awesome.

The only improvement I'd wish for is a choice between coloured and monochrome icons for the taskbar. Most Linux DEs are moving to monochrome icons and the coloured ones don't fit in well with this new aesthetic.

**Comment by yuezk** [comment]
Good suggestion, will try it.
