### ISSUE TITLE
Request: Keep in tray when closing

### ISSUE THREAD

**Issue by jacob-swenson** [yuezk/GlobalProtect-openconnect#15]
I'm using i3wm. It would be great if when I close the window after connecting it would stay in the system tray. It seems to keep running in the background, I don't disconnect from VPN, but I don't see it in the tray and have to run the application again to be able to disconnect.

**Comment by yuezk** [comment]
I see. AFAIK, it will keep in tray when closing in KDE. I tested it in GNOME and found the same problem as yours. It looks like a problem of Qt. But I will try to find a way to fix it.

**Comment by jacob-swenson** [comment]
I can dig if I have time but haven't had much free time for the last couple weeks.

**Comment by patrickathompson** [comment]
Really like the app.. btw! I was digging around looking for answers to the same issue in Cinnamon which is based on gnome originally. This was the best I found:

https://doc.qt.io/qt-5/qtwidgets-desktop-systray-example.html

I was then reminded I have no experience with qt ui apps. ;)

Maybe that will help, though.

**Comment by mikedld** [comment]
Adding this in main.cpp (right after creating `app`) help here:

```cpp
app.setQuitOnLastWindowClosed(false);
```
