### ISSUE TITLE
Autheticaton Failed After Entering MFA Code

### ISSUE THREAD

**Issue by sangoku116** [yuezk/GlobalProtect-openconnect#151]
The Authentication fails after entering the MFA Code. I am then stuck on an authentication failed window after selecting the server even after reboot. 

![image](https://user-images.githubusercontent.com/18174977/167686914-a6dc77b3-d49b-4689-8ef4-96f8af236721.png)

I have tried removing the ```~/.cache/gpclient/``` folder.

**Comment by yuezk** [comment]
I encountered this problem occasionally, I'm still working on it.

**Comment by sangoku116** [comment]
> 

Awesome, thank you! If you need more information or logs, I will happily provide them.

**Comment by sangoku116** [comment]
It was an error with the provider's DNS. It has now been fixed
