### ISSUE TITLE
package for OpenSUSE Leap 15.4

### ISSUE THREAD

**Issue by snikulov** [yuezk/GlobalProtect-openconnect#160]
Thank you for great package!

Unfortunatelly unable to find package for openSUSE Leap 15.4
It would be nice to provide it through OBS https://download.opensuse.org/repositories/home:/yuezk/
Pacakge from 15.4 is not installable with issue
`Problem: nothing provides 'openconnect >= 8.0' needed by the to be installed globalprotect-openconnect-1.4.8-1.1.x86_64`

**Comment by vinyanalista** [comment]
@snikulov In fact, the openSUSE Leap 15.4 OSS repo provides [openconnect](https://software.opensuse.org/package/openconnect) 7.08.

You can install a newer version from the [network](https://build.opensuse.org/package/show/network/openconnect) OBS repo:

```
sudo zypper addrepo https://download.opensuse.org/repositories/network/15.4/network.repo
sudo zypper refresh
sudo zypper install openconnect
```

As of now, those commands are going to give you openconnect 9.01.

**Comment by vinyanalista** [comment]
In case openconnect is already installed, you can force the installation of the newer version with:

```
sudo zypper install openconnect-9.01
```

I just tested those commands on the openSUSE Leap 15.4 GNOME Live media and, to my surprise, openconnect was already installed.

**Comment by vinyanalista** [comment]
After installing the newer openconnect, you can install [GlobalProtect-openconnect](https://software.opensuse.org/package/globalprotect-openconnect) with:

```
sudo zypper addrepo https://download.opensuse.org/repositories/home:yuezk/15.4/home:yuezk.repo
sudo zypper refresh
sudo zypper install globalprotect-openconnect
```

**Comment by vinyanalista** [comment]
@yuezk you could update your instructions on [how to install on openSUSE Leap](https://github.com/yuezk/GlobalProtect-openconnect#opensuse) with the commands above.

**Comment by vinyanalista** [comment]
@yuezk here is another tip for you: you could fork the openconnect package from the [network](https://build.opensuse.org/package/show/network/openconnect) OBS repo to yours ([home:yuezk](https://build.opensuse.org/project/show/home:yuezk)).

That way, anyone installing [GlobalProtect-openconnect](https://software.opensuse.org/package/globalprotect-openconnect) from your repo would automatically get the required openconnect version.

Also, the user wouldn't need to add two repos (network and home:yuezk), but just one (home:yuezk).

**Comment by iamtalhaasghar** [comment]
> @yuezk you could update your instructions on [how to install on openSUSE Leap](https://github.com/yuezk/GlobalProtect-openconnect#opensuse) with the commands above.

I have opened  a PR for this #263
