### ISSUE TITLE
Gateway authentication failed

### ISSUE THREAD

**Issue by smiddy** [yuezk/GlobalProtect-openconnect#161]
System: Ubuntu 22.04
Client version: 1.48

I try to connect to the server gpvpn.mit.edu

I receive the error:

Gateway authentication failed. Error occurred on the gateway prelogin interface.

**Comment by smiddy** [comment]
It seems that the GlobalProtect-openconnect has issues with MIT's load balancer. I used a specific acces and it worked fine. See https://kb.mit.edu/confluence/display/istcontrib/Install+and+Connect+to+the+Prisma+Access+VPN+on+Linux

**Comment by TheRealIndru** [comment]
I am having the same problem with my corporate VPN connexion. Any helpful tips on what should I do?

**Comment by eitzenbe** [comment]
filing in in the queue, global protect with Azure AD SAML

**Comment by yuezk** [comment]
Have you ever tried https://github.com/dlenski/gp-saml-gui?

**Comment by eitzenbe** [comment]
Yes it works but I needed to change config of open SSL... If this could be a reason I can attach modified config and script I use

23.10.2022 13:15:32 Kevin Yue ***@***.***>:

**Comment by yuezk** [comment]
@eitzenbe That would be great, but I’m afraid I don’t have enough time to investigate it.

**Comment by yuezk** [comment]
Should no longer be a problem in 2.x. Closing it for now, repoen it if it still exists in 2.x.
