### ISSUE TITLE
Debian package

### ISSUE THREAD

**Issue by A-Joshi** [yuezk/GlobalProtect-openconnect#17]
Thought it would be good to have a debian package. I have added a debian repository and created a package. Would you like a pull request for it?

**Comment by yuezk** [comment]
Of cause, I have been planning the debian package for a long time. But I didn't have time to learn how to package it.

PR would be welcomed and thank you very much.

**Comment by A-Joshi** [comment]
I have sent in a PR #19

**Comment by yuezk** [comment]
Thank you for your contribution.

What's the next step? Can you help publish it to the debian repository or I do it by myself?

BTW, the current version number is `1.2.4`.

**Comment by solj** [comment]
I was able to use the debian packaging to build a .deb but the version in the changelog needs to be updated to 1.3.0 per the instructions in the readme.

**Comment by Nat-As** [comment]
Is there a way to build the .deb package with travic ci? Or is that a Gitlab thing?

**Comment by yuezk** [comment]
I'm intending to integrate the build process into the GitHub Actions, but haven't got the time to do it yet.

**Comment by Nat-As** [comment]
I have a build going in my branch using travis-ci. It is throwing dependency errors though.

**Comment by rfmaynard** [comment]
Hi, How do i create the deb package? I am having some troubles during the fakeroot command.

```
dh clean  
make: dh: Command not found
make: *** [debian/rules:9: clean] Error 127
dpkg-buildpackage: error: debian/rules clean subprocess returned exit status 2
```

**Comment by Nat-As** [comment]
Even when I got the build to work, the deb package didn't work. I'm currently using open connect: http://www.infradead.org/openconnect/download.html

**Comment by rfmaynard** [comment]
> 
> 
> Even when I got the build to work, the deb package didn't work. I'm currently using open connect: http://www.infradead.org/openconnect/download.html

@Nat-As will this work with microsoft 2FA?

**Comment by solj** [comment]
> Hi, How do i create the deb package? I am having some troubles during the fakeroot command.
> 
> ```
> dh clean  
> make: dh: Command not found
> make: *** [debian/rules:9: clean] Error 127
> dpkg-buildpackage: error: debian/rules clean subprocess returned exit status 2
> ```

Looks like you need to install debhelper.

```
$ dpkg -S $(which /usr/bin/dh)
debhelper: /usr/bin/dh
```
