### ISSUE TITLE
Segmentation Fault when starting the service

### ISSUE THREAD

**Issue by octaviaguo** [yuezk/GlobalProtect-openconnect#173]
Hi! I got a segmentation error when starting the GlobalProtect with the command `sudo dpkg -i {path to the extracted files}/GlobalProtect_UI_deb-{current version}.deb.` How can I fix it? Thanks!
![Screenshot from 2022-08-04 13-46-05](https://user-images.githubusercontent.com/42426882/182916870-17062e0a-c766-4741-9884-2182d8c7cbcd.png)

**Comment by yuezk** [comment]
This is the official client, not mine.
