### ISSUE TITLE
Support custom URL scheme beyond-identity-endpoint in Qt Web

### ISSUE THREAD

**Issue by klDen** [yuezk/GlobalProtect-openconnect#175]
Currently, I'm using [beyond-identity](https://www.beyondidentity.com/) as MFA. After clicking on `Connect` in GlobalProtect-openconnect, it redirects me to a web page where normally it would attempt to open the URL scheme `beyond-identity-endpoint:///`.
Unfortunately, I don't believe it's possible to specify the scheme at the moment (no pop-up notification to select application like Firefox).
I believe the following links may be helpful for adding support for custom URL scheme :
- https://doc.qt.io/qt-6/qtwebengine-features.html#custom-schemes
- https://doc.qt.io/qt-6/qwebengineurlscheme.html
- https://doc.qt.io/qt-6/qtwebengine-features.html#web-notifications

## Firefox
![image](https://user-images.githubusercontent.com/5478260/184259732-0e4913a7-0443-456a-8e12-adb60dbd8033.png)

## Chromium
![image](https://user-images.githubusercontent.com/5478260/184268668-77692c67-2cc6-466a-b0c6-d7c53bf4fc27.png)

**Comment by yuezk** [comment]
Implemented in 2.x
