### ISSUE TITLE
Ini.c truncating config file arguments

### ISSUE THREAD

**Issue by zpalmtree** [yuezk/GlobalProtect-openconnect#176]
The max line length definition in ini.h is causing me issues with my config file.
https://github.com/yuezk/GlobalProtect-openconnect/blob/master/3rdparty/inih/ini.h#L130

I am attempting to provide a number of routes, but the config line is being truncated and not all routes are being respected.

For example, with a config like this (using garbage data instead of my real routes)

> openconnect-args=--script="aaaaaaaaaabbbbbbbbbbccccccccccddddddddddeeeeeeeeeeffffffffffgggggggggghhhhhhhhhhiiiiiiiiiijjjjjjjjjjkkkkkkkkkkllllllllllmmmmmmmmmmnnnnnnnnnnooooooooooppppppppppqqqqqqqqqqrrrrrrrrrrssssssssssttttttttttuuuuuuuuuuvvvvvvvvvvwwwwwwwwwwxxxxxxxxxxyyyyyyyyyyzzzzzzzzzz"

You will see something like this in the log file:

```
2022-08-12 14:11:48.282 INFO  [383748] [GPClient::onVPNLogAvailable@517] Got extra OpenConnect args for server: gpvpn2.velocitymsc.com, --script="aaaaaaaaaabbbbbbbbbbccccccccccddddddddddeeeeeeeeeeffffffffffgggggggggghhhhhhhhhhiiiiiiiiiijjjjjjjjjjkkkkkkkkkkllllllllllmmmmmmmmmmnnnnnnnnnnooooooooooppppppppppqqqqqqqqqqrr
```

`openconnect-args=--script="aaaaaaaaaabbbbbbbbbbccccccccccddddddddddeeeeeeeeeeffffffffffgggggggggghhhhhhhhhhiiiiiiiiiijjjjjjjjjjkkkkkkkkkkllllllllllmmmmmmmmmmnnnnnnnnnnooooooooooppppppppppqqqqqqqqqqrr` plus a newline is 200 characters.

This behaviour is configurable - with certain combinations of compilation flags, the buffer will get resized automatically. These must not be set, however.
https://github.com/yuezk/GlobalProtect-openconnect/blob/master/3rdparty/inih/ini.c#L97-L155

**Comment by yuezk** [comment]
Did you try to split it with multiple lines? See the example https://github.com/yuezk/GlobalProtect-openconnect/wiki/Configuration#example

**Comment by zpalmtree** [comment]
Is it possible to do that in the middle of a vpn-slice string?
My config looks like this:

openconnect-args=--script="vpn-slice ipa ipb ipc ipd ipe ipf ipg iph ipj ipk ipl ipm ..."

I tried seeing if it would automatically concat multiple string values like 
```
openconnect-args=--script="vpn-slice"
    "ipa ipb ipc"
    "ipd ipe ipf"
```
but that did not work.

**Comment by yuezk** [comment]
How about writing the command to a shell script file and using the script file in the `--script` parameter?

`vpn-script.sh`:
```sh
vpn-slice ipa ipb ipc ipd ipe ipf ipg iph ipj ipk ipl ipm ...
```
And configure the args as:

`openconnect-args=--script="/path/to/vpn-script.sh"`

**Comment by zpalmtree** [comment]
That did the trick. Thanks!
