### ISSUE TITLE
Disconnection after a few seconds

### ISSUE THREAD

**Issue by ParadaCarleton** [yuezk/GlobalProtect-openconnect#178]
The VPN disconnects just a few seconds after connecting. Do you know what might be causing this?

**Comment by yuezk** [comment]
I encountered a similar problem before, but it backed to normal after a while. It could be a problem with the VPN server if you didn't encounter this problem constantly.

**Comment by K4S1** [comment]
Seeing similar issues this morning.

and I'm seeing a "Failed to open tun device: No such device"
When it disconnect.

![image](https://user-images.githubusercontent.com/8589819/185851237-fd7a163d-9d1c-4163-b948-bc530b1f55fb.png)

**Comment by Panicfly** [comment]
I have the same error. Im connected and after like 12-13 seconds it disconnect me again.

**Comment by yuezk** [comment]
Should no longer be a problem in 2.x. Closing it for now, repoen it if it still exists in 2.x.
