### ISSUE TITLE
Use browser instead of webview to authenticate

### ISSUE THREAD

**Issue by glennib** [yuezk/GlobalProtect-openconnect#185]
Is it possible to use the user's standard browser to authenticate and log into the VPN? Would be helpful with regards to browser password managers.

**Comment by iamkroot** [comment]
I see [Headless Chromium](https://chromium.googlesource.com/chromium/src/+/lkgr/headless/README.md#usage-as-a-c_library) can be used as a C++ library apparently. Pointing it to an existing user profile would then do the trick.

There is also this- https://github.com/durdyev/webdriverxx

**Comment by yuezk** [comment]
Supported in 2.x. Closing.
