### ISSUE TITLE
Not able to configure specific location within cluster

### ISSUE THREAD

**Issue by nekodojo** [yuezk/GlobalProtect-openconnect#191]
I would like to reconnect back to the same location but I keep getting the first gateway in the list, not the one I configured, or the one I chose on the last session.
For example: Connected successfully to vpn.company.com, find I am connected to location amsterdam-vpn.company.com. Change location to San Jose and get sanjose-vpn.company.com.  On disconnect and reconnect I am back to amsterdam-vpn.company.com. 

I am also experiencing a separate issue where I cannot reconnect after timeout because gpclient is going back to the specific location gateway, not going back to the main login portal. ( https://github.com/yuezk/GlobalProtect-openconnect/issues/147 ) In my case amsterdam-vpn.company.com is not a proper login endpoint, only vpn.company.com. So I have to "Reset" after session time out.

Because of having to reset, I cannot rely on gpclient to "remember" the gateway I chose last time. So I figured, I will add this to the config file.  The information about specifying the config, as given in the wiki, is super sketchy and assumes you know openconnect command line syntax.  So, I tried just adding "san-jose-vpn.company.com" to openconnect-args= in config.  This results in both my text and the unwanted gateway being passed on the command line together.  I don't see a way to configure gpclient to connect to san-jose-vpn.company.com and not keep going back to amsterdam-vpn.company.com.

2022-11-04 13:56:03.214 INFO  [12994] [GPClient::onVPNLogAvailable@517] Got extra OpenConnect args for server: amsterdam-vpn.company.com, sanjose-vpn.company.com
2022-11-04 13:56:03.214 INFO  [12994] [GPClient::onVPNLogAvailable@517] Start process with arugments: --protocol=gp, sanjose-vpn.company.com, -u, commscope\gconnor, --cookie-on-stdin, amsterdam-vpn.company.com

**Comment by yuezk** [comment]
Should no longer be a problem in 2.x. Closing it for now, repoen it if it still exists in 2.x.
