### ISSUE TITLE
stuck at connecting on ubuntu 22.04

### ISSUE THREAD

**Issue by harpreetmann24** [yuezk/GlobalProtect-openconnect#192]
After logging in - I am stuck at connecting. I am using Ubuntu 22.04.

**Comment by diomenezes** [comment]
I change to Elementary OS and works

**Comment by Lawrence-Hall** [comment]
I'm running 22.04.1 LTS and seem to not be having this issue.

**Comment by Digital2Slave** [comment]
> After logging in - I am stuck at connecting. I am using Ubuntu 22.04.

+1 

```
➜  ~ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.6 LTS
Release:	20.04
Codename:	focal
```

**Comment by yuezk** [comment]
Should no longer be a problem in 2.x. Closing it for now, repoen it if it still exists in 2.x.
