### ISSUE TITLE
Stuck on connectiong using a domain login

### ISSUE THREAD

**Issue by teicors** [yuezk/GlobalProtect-openconnect#197]
Hi,
I'm using the latest version and looking at the jobs running I can see 
'/usr/sbin/openconnect --protocol=gp -u domain\user --cookie-on-stdin XX.YY.ZZ.KK'
but nothing more.
If I try to use only user, the connection works fine, but I don't receive an appropriate IP.
The version on my ubuntu 22.04 is Open client for multiple VPN protocols, version v8.20-1

**Comment by yuezk** [comment]
Have you ever tried the bare `openconnect` command, instead of using the GUI?

**Comment by yuezk** [comment]
Should no longer be a problem in 2.x. Closing it for now, repoen it if it still exists in 2.x.
