### ISSUE TITLE
Command Line

### ISSUE THREAD

**Issue by madorian** [yuezk/GlobalProtect-openconnect#199]
I'm on NixOS and this seems to be the only way to connect to GlobalProtect. I'd rather use command line. Is that possible with this client?;)

**Comment by yuezk** [comment]
Is your VPN server configured to use external authentication, e.g. SAML? If not, you might not need to use this client. The OpenConnect cli could be suffice.

**Comment by shaifulpaynet** [comment]
@yuezk if my company VPN server is configured to use external authentication, is it still possible to connect through cli?

**Comment by yuezk** [comment]
The command line has been improved in 2.x. and it can use the SSO authentication.
