### ISSUE TITLE
Cannot Enter Portal Address On gpclient UI

### ISSUE THREAD

**Issue by lanandra** [yuezk/GlobalProtect-openconnect#206]
Hi,

Recently i've got strange error. I cannot input portal address on gpclient UI
The error said:
```
gpclient: symbol lookup error: /usr/lib/plugins/platforminputcontexts/libibusplatforminputcontextplugin.so: undefined symbol: _ZdlPvm, version Qt_5
```

Previously i cannot login to my vpn server and error said some gateway error. Then i followed some workaround in [here](https://github.com/yuezk/GlobalProtect-openconnect/issues/147) to remove GPClient.conf, but this issue arises

**Comment by yuezk** [comment]
What version are you using?

**Comment by lanandra** [comment]
version `1.4.9`

**Comment by yuezk** [comment]
The error message seems related to the input method. If possible, please try to downgrade to 1.4.8 to see if it works.

**Comment by lanandra** [comment]
If i want to downgrade to version `1.4.8`. Can i just download the assests from [here](https://github.com/yuezk/GlobalProtect-openconnect/releases). And then i run the `./scripts/install-ubuntu.sh` ? let's say i'm using Ubuntu

**Comment by yuezk** [comment]
Yes, you can.

**Comment by yuezk** [comment]
Should no longer be a problem in 2.x. Closing it for now, repoen it if it still exists in 2.x.
