### ISSUE TITLE
Portal address gets changed automatically

### ISSUE THREAD

**Issue by tinkermakar** [yuezk/GlobalProtect-openconnect#209]
When I connect to my VPN, the URL gets automatically changed, it seemingly changes to the actual gateway URL I get connected to, but that results to connection failure. Can you make it disablable, please? It seems to be a recent feature.

**Comment by yuezk** [comment]
It's not a recent feature. Can you try to switch the gateway from the system tray menu and see if it works?

**Comment by bandogora** [comment]
This issue started occurring for me in the past couple of weeks.

- Error: [Notice] Gateway authentication error occurred on the gateway prelogin interface.
- Custom parameters: None
- Version: 1.4.9-1
- OS: Arch Linux
- Package manager: aur

Steps to reproduce:
1. Launch app
2. Select "Reset" from app menu
3. Enter gateway address
4. Click "Connect" in app
5. Fill out SAML authentication
6. Receive error; gateway changed

Work around:
1. Dismiss notice
2. Re-enter original gateway address
3. Connect

**Comment by yuezk** [comment]
Should no longer be a problem in 2.x. Closing it for now, repoen it if it still exists in 2.x.
