### ISSUE TITLE
Login only after reload, then no window for MFA-Code

### ISSUE THREAD

**Issue by dderjoel** [yuezk/GlobalProtect-openconnect#212]
Hi,
I used this software successfully a couple months ago. I do not know what changed (maybe our IT), but I can no longer connect.

I'm using this remote URL:
`https://remote.adelaide.edu.au` And the Little QT windows that opens does not show the login form 'username'/'password', only the background image. I can then right-click and reload, then It appears. I can then Login with my credentials, it redirects to that PALO ALTO login screen for a split second and then only background image again.
(Usually, what happens is that it displays the form for me to choose if I want OKTA push / sms / Google Authenticator, ...)

I tried to debug but the logs don't give me that much info and the code base is a bit big for me.

I assume you don't have credentials for this particular vpn, but If we find out why it is not rendering the form at start, it may be the same cause for the second - not rendering.

I'm happy to recompile / give logs / whatever may assist you to find.

I'm using a latest version of Arch (`Linux arch4 6.1.8-arch1-1 #1 SMP PREEMPT_DYNAMIC Tue, 24 Jan 2023 21:07:04 +0000 x86_64 GNU/Linux`), latest version of openconnect (`v9.01`) (but I don't think that matters at this point)

EDIT: after the redirect with correct credentials, I can 'reload' again, but then I get the username/password form again.

**Comment by yuezk** [comment]
Try resetting the client via the system tray menu.

**Comment by dderjoel** [comment]
I cannot reset the client when the Qt window is up (Clicking and right-clicking the tray icon does not open the popup.)
I've reset it without the window open.
Now, first login-page does not load at first. When I right-click and reload, the username/password form displays. Upon login, I can also enter and send my MFA code. Then, some redirects happen, the window closes but eventually reopens with the empty website (just like the one I started with and needed to right-click+reload).

Please find attached the logs (with my annotations, what I did)
[gplog2.log](https://github.com/yuezk/GlobalProtect-openconnect/files/10574265/gplog2.log)

**Comment by matthew-shirey** [comment]
I've run into this exact same issue after an Okta upgrade at my University.  Is there any more information on this?  Is there a workaround?  I have tried the reset option, but it changes nothing.
Is there a way to force the client to use my default web browser instead of the Qt dialog?  When communicating with my Windows co-workers, they all say their client opens the default web browser for the authentication part.  I suspect that if I could use the default browser, this wouldn't be a problem.

**Comment by sarthak247** [comment]
@dderjoel I have the same issue and am from UoA too. Using this on Arch and it just won't work. After reloading the page I am able to login, authenticate with Okta and everything but it just reloads the login page which doesn't make sense. Were you able to get it working?

**Comment by yuezk** [comment]
Should no longer be a problem in 2.x, reopen if not.
