### ISSUE TITLE
gpclient: error while loading shared libraries: libre2.so.9: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by madhur** [yuezk/GlobalProtect-openconnect#213]
I am on arch and I get this error.

I had it installed it using pacman 
```
sudo pacman -S globalprotect-openconnect 
```

The libre version which I have installed is `2.10.0-1`, again from pacman which I believe is latest.

**Comment by DavidPerezIngeniero** [comment]
With Ubuntu 22.04 works fine.

**Comment by dderjoel** [comment]
whats the output of 
```bash
ldd `which gpclient` | grep libre
```

mine says
```
$ ldd `which gpclient` |grep libre
        libresolv.so.2 => /usr/lib/libresolv.so.2 (0x00007f09ee080000)
        libre2.so.10 => /usr/lib/libre2.so.10 (0x00007f09ebc65000)
```

So I think its interesting that mine is looking for `libre2.so.10` (and finds it) and yours is looking for `libre2.so.9`.

**Comment by madhur** [comment]
Invalid issue. Ignore.
