### ISSUE TITLE
Blank page at login

### ISSUE THREAD

**Issue by glennib** [yuezk/GlobalProtect-openconnect#218]
As of today I get this blank page when I try to log in to my VPN:

![image](https://user-images.githubusercontent.com/3914032/219297923-b1e1b24e-3b32-4031-b377-a4cbd7f392b3.png)

Don't know whether it's a portal issue or a client issue.

**Comment by yuezk** [comment]
Did upgrade this client before the problem occurs? It‘s likely a portal problem.

**Comment by glennib** [comment]
> Did upgrade this client before the problem occurs?

I didn't upgrade before, and I was on the latest version.

> It‘s likely a portal problem.

Seems you are right: https://status.jumpcloud.com/incidents/xzrw00gdbytc

Works now.
