### ISSUE TITLE
Option to auto connect on startup

### ISSUE THREAD

**Issue by jblinkgroup** [yuezk/GlobalProtect-openconnect#219]
Currently, when GlobalProtect is started, it does not connect automatically. If possible, it would be great to have an option to enable 'auto connect' so that once started, it will connect to specified server automatically.

**Comment by yuezk** [comment]
The latest client supports connecting to the VPN server automatically when launched. Enable it and then add this client to the auto start applications.

- In KDE, see https://userbase.kde.org/System_Settings/Autostart
- In GNOME, see https://help.gnome.org/users/gnome-help/stable/shell-apps-auto-start.html.en
