### ISSUE TITLE
Cannot mix incompatible Qt library (5.15.7) with (5.15.8)

### ISSUE THREAD

**Issue by UrsusArct** [yuezk/GlobalProtect-openconnect#220]
So I've been trying to install this package for a few weeks now, as all other alternatives simply do not work whatsoever. I need this VPN for university related purposes so I've been trying to fully system update and reinstall this client, with no avail for a while. The client installs fine, but doesn't open, and when I run via terminal I get the following:

2023-02-25 13:22:19.091 INFO  [31864] [main@24] GlobalProtect started, version: 1.4.9
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
Cannot mix incompatible Qt library (5.15.7) with this library (5.15.8)
Aborted (core dumped)

I'm running Arch 6.0.9 and I have the newest Qt version installed (5.15.8)

Any help is appreciated as I really need to get this working ASAP

**Comment by raboonik** [comment]
Please unsubscribe me from this thread. I've tried everything but I still
receive notifications.

**Comment by yuezk** [comment]
@raboonik Did you watch the repo? If yes, you can unwatch it.

**Comment by yuezk** [comment]
@UrsusArct I haven't encountered this problem. You could probably review the Qt libraries installed and upgrade them to 5.15.8. Or you could try to compile this client from the source code.

**Comment by cardonator** [comment]
I got this as well on Kubuntu 22.04 and KDE Neon. I'm thinking they just don't have late enough packages.

**Comment by UrsusArct** [comment]
> @UrsusArct I haven't encountered this problem. You could probably review the Qt libraries installed and upgrade them to 5.15.8. Or you could try to compile this client from the source code.

Well I thought this might work, but I’ve upgraded and reinstalled my Qt libraries and compiled from scratch. I may try compile the program again, but I’m stumped as I’m fairly certain I was having the same issue but in reverse when using 5.15.7, with the program saying it cannot mix 5.15.8 with the installed 5.15.7

**Comment by UrsusArct** [comment]
Upon attempting to compile from source I get the following error, which I also got when installing the git package from the AUR:

CMake Error at /usr/lib64/cmake/Qt5WebEngineCore/Qt5WebEngineCoreConfig.cmake:111 (find_package):
  Could not find a configuration file for package "Qt5Quick" that is
  compatible with requested version "5.15.8".

  The following configuration files were considered but not accepted:

    /usr/lib64/cmake/Qt5Quick/Qt5QuickConfig.cmake, version: 5.15.7

Call Stack (most recent call first):
  /usr/lib64/cmake/Qt5WebEngine/Qt5WebEngineConfig.cmake:111 (find_package)
  /usr/lib64/cmake/Qt5/Qt5Config.cmake:28 (find_package)
  CMakeLists.txt:23 (find_package)


This is surely not an issue with my packages, as they are all updated

**Comment by yuezk** [comment]
I don't have experience in this. But from the error log, looks like you are using libraries with "5.15.7", and it requested is version "5.15.8" Have you ever tried to use "5.15.8"?

**Comment by yuezk** [comment]
No longer a problem in 2.x, which won't depends on Qt libraries.
