### ISSUE TITLE
This site can't be reached after authentication with Okta

### ISSUE THREAD

**Issue by dtluna** [yuezk/GlobalProtect-openconnect#221]
After entering my authentication details to Okta I get the following error:
![login_failure](https://user-images.githubusercontent.com/25333996/221807591-36bd2e3f-a579-40b2-bac8-9e647ccace92.png)

**Comment by hazy-halcyon** [comment]
Me too, it's because of self-signed or expired certificate of the PA gateway. I still haven't found a way around this. smh

**Comment by hazy-halcyon** [comment]
Hi! I just found a workaround to this problem. Firstly, open your Global Protect gateway IP on your browser where can you export the certificate file.

![image](https://user-images.githubusercontent.com/77142658/225092667-3871357c-12c2-4fbf-ba12-967dae374c5c.png)

![Screenshot from 2023-03-15 00-15-41](https://user-images.githubusercontent.com/77142658/225092997-a326ca1e-f466-4074-908f-3a0ec26cd4d5.png)

**Don't forget to export it in Base64-encoded, ceritificate chain**

And then use this guide to import the certificate into your linux system.
https://thomas-leister.de/en/how-to-import-ca-root-certificate/

Remove and reinstall the app, and you are good to go! :)

**Comment by yuezk** [comment]
Should no longer be a problem in 2.x, which has an option to ignore the TLS errors. Closing it for now, reopen it if the problem still there.
