### ISSUE TITLE
It gets stuck when I have a short Internet disconnection

### ISSUE THREAD

**Issue by DavidPerezIngeniero** [yuezk/GlobalProtect-openconnect#225]
My network is sometimes a little unstable, and I have a few seconds of no internet connection (maybe milliseconds), 

In this case, `gpclient` gets stuck, and I lose my Internet access even though it is restored.  

In order to work again, I have to kill it in this way:
```
sudo pkill -9 gpclient
sudo pkill -9 gpservice
```

and enter the credentials once more.

**Comment by yuezk** [comment]
The client has been refactored in 2.x, closing it for now, reopen it if the problem still exists in 2.x.
