### ISSUE TITLE
Stuck on Authenticating after succesfull Okta log in

### ISSUE THREAD

**Issue by MorriAtAltos** [yuezk/GlobalProtect-openconnect#227]
Hi!

my company use globalprotect with Okta. I managed to log in into Okta and send the push notification, but the app is stuck after the "Login Succesfull"

**Comment by roworu** [comment]
Got same error. Is there any log files we can provide to help identify this issue?

**Comment by yuezk** [comment]
Should be fixed in 2.x, which rewrote the authentication. Reopen it not.
