### ISSUE TITLE
.deb package build error

### ISSUE THREAD

**Issue by Nat-As** [yuezk/GlobalProtect-openconnect#23]
On the last step of the debian build process I get this error in the terminal:
```
dpkg-source: error: can't build with source format '3.0 (quilt)': no upstream tarball found at ../globalprotect-openconnect_1.2.7.orig.tar.{bz2,gz,lzma,xz}
dpkg-buildpackage: error: dpkg-source -b globalprotect-openconnect-1.3.0 subprocess returned exit status 25
```

**Comment by yuezk** [comment]
Looks like the version number in the [changelog](https://github.com/yuezk/GlobalProtect-openconnect/blob/master/debian/changelog) is different from the version number in README.md.

I have updated the version number in the changelog. So please update the repo and try again.

**Comment by Nat-As** [comment]
Fixed it in my branch. I was able to build the .deb package but it isn't working currently. Thank you!
