### ISSUE TITLE
DNS problem on Ubuntu 20.04LTS

### ISSUE THREAD

**Issue by porschberg** [yuezk/GlobalProtect-openconnect#230]
Hi,
I use the latest version of gpclient. I can connect but name resolution does not work.
Is there a way to configure e.g. via openconnect-args the proper DNS-Server? 
BTW the package _resolvconf_ is installed.

Best regards 
Thomas

**Comment by jooon** [comment]
The bug could also be in vpnc-scripts. In Ubuntu 22.04 there is a dns setup bug in that package.
https://bugs.launchpad.net/ubuntu/+source/vpnc-scripts/+bug/1990141
