### ISSUE TITLE
Disable UI popup on login

### ISSUE THREAD

**Issue by madhur** [yuezk/GlobalProtect-openconnect#235]
Hi Team
Thanks for this wonderful software.

I am running the globalprotect-openconnect on startup. However, on each startup it displays the login popup, which I have to close manually. 

Is there  a way to pass a flag such that it doesn't display the popup? Only the tray icon should be present. Upon clicking the tray icon, the popup should open.

**Comment by yuezk** [comment]
Thanks for your feedback. Reasonable requirement.

I'm rewriting it on branch [refactor](https://github.com/yuezk/GlobalProtect-openconnect/tree/refactor), with the tech stack that I am more familiar with. It will support what you mentioned when it is finally released.

**Comment by madhur** [comment]
Thank you. For now, I configured my window manager(AwesomeWM) to start this as minimized.

**Comment by yuezk** [comment]
Supported in 2.x. Closing.
