### ISSUE TITLE
Fido2 / Yubikey doesnt work with SSO SAML login

### ISSUE THREAD

**Issue by CalleB3** [yuezk/GlobalProtect-openconnect#239]
Hi,

I cant seem to get my FIDO2 key to work with gpclient, using MFA with microsoft authenticator works fine, trying to switch to it using my yubikey instead and it gets stuck here with "Your PC will open a security window" and nothing happens.
(it works fine in browser windows using Microsoft SAML SSO.
Do I need to make some custom configuration for this to work? Thanks. 

![image](https://github.com/yuezk/GlobalProtect-openconnect/assets/91601778/67ba62db-b04e-4b6f-8640-c0870a993701)

**Comment by yuezk** [comment]
Will support it in 2.0 using Tauri.

**Comment by CalleB3** [comment]
Okey, thanks. Any information when that will be released?

**Comment by CalleB3** [comment]
Hello again, any news regarding this and the 2.0 release?

**Comment by yuezk** [comment]
I'm still working on it. It could be released by the end of the year.

**Comment by yuezk** [comment]
With 2.x, it supports Yubikey by using the external-browser. You can enable this in settings.
