### ISSUE TITLE
Handle SSL Error

### ISSUE THREAD

**Issue by yuezk** [yuezk/GlobalProtect-openconnect#24]
From https://aur.archlinux.org/packages/globalprotect-openconnect/#comment-755587

Gateway Authentication fail...Need help. 2020-07-11 20:44:39.119 ERROR [4823] [GatewayAuthenticator::onPreloginFinished@81] Failed to prelogin the gateway at https://X.X.X.X/ssl-vpn/prelogin.esp?tmp=tmp&kerberos-support=yes&ipv6-support=yes&clientVer=4100&clientos=Linux, SSL handshake failed

**Comment by gcngov** [comment]
guys help required on above issue.

**Comment by yuezk** [comment]
Hi, @gcngov are you using the self-signed certificate?

Can you open the URL https://X.X.X.X/ssl-vpn/prelogin.esp?tmp=tmp&kerberos-support=yes&ipv6-support=yes&clientVer=4100&clientos=Linux in Chrome to see if the chrome says an SSL error? Thanks.

**Comment by yuezk** [comment]
@gcngov Can you upgrade to v1.2.5 to verify if this issue has been fixed? Thanks.
