### ISSUE TITLE
Copy and paste buffer not working as expected on Fedora 38

### ISSUE THREAD

**Issue by jmakin-godaddy** [yuezk/GlobalProtect-openconnect#242]
I suspect this problem is outside of the scope of this code, and possibly in F38's various QT5 packages, but it would be nice to find out.
Since upgrading from F37 to F38 I'm unable to simply copy and paste an email address or password into the login fields when trying to connect.

I'm trying to avoid manually typing in a long and unrememberable password every day.

**Comment by yuezk** [comment]
I'm refactoring this client using Tauri. So it can be fixed once the refactoring is done.

**Comment by sladiri** [comment]
Just wanted to say that I have upgraded from F37 to F38 too and I could copy paste fine. I think this is the first Qt5 app I installed on the system.

**Comment by yuezk** [comment]
Closing as the refactoring has been finished.
