### ISSUE TITLE
Microsoft SAML auth asks for full authentication each morning. Despite clicking Yes to the "Stay signed in?" prompt.

### ISSUE THREAD

**Issue by ipaqmaster** [yuezk/GlobalProtect-openconnect#250]
You can disconnect and reconnect without having to enter the credentials again and even restart gpclient (fully, no tray icon) and still connect without re-authenticating again just fine. But the following day I'm always prompted by Microsoft's full authentication process as if its never seen my gpclient before.

I am uncertain just yet whether this is a policy set on our end, or some cache problem causing MS auth to entirely forget gpclient's existing SAML session. Our other services which also use Microsoft's SAML have no issue keeping a session for weeks at a time.

**Comment by yuezk** [comment]
I'm using MSFT as well, no longer a problem in 2.x. Closing.
