### ISSUE TITLE
Stuck on "Login Successful!"

### ISSUE THREAD

**Issue by rwitkop-rh** [yuezk/GlobalProtect-openconnect#254]
After I enter my credentials, it shows "Login Successful!" modal below, but doesn't connect.
![image](https://github.com/yuezk/GlobalProtect-openconnect/assets/138809311/5c840a6c-0b5e-4480-b32d-c623031a32d9)
![image](https://github.com/yuezk/GlobalProtect-openconnect/assets/138809311/15fffaa3-b70a-4511-85fd-bffe77783f45)

**Comment by LatifahSul** [comment]
I have the same problem

**Comment by anmolnar** [comment]
+1

**Comment by devinsmith** [comment]
Might be related to https://github.com/dlenski/gp-saml-gui/issues/71

The headers suddenly changed from all lowercase to capitalized?

**Comment by AloneAndUnknown** [comment]
+1

**Comment by smedelyan** [comment]
I had the same issue. After having upgraded to the latest master branch it works now! (Though, I had to just pull the sources and launch the `gp_saml_gui.py` as the instructions for the installation didn't work for me either)

**Comment by yuezk** [comment]
No longer a problem in the latest 2.x release, which support authentication using the default browser. Closing.
