### ISSUE TITLE
Can't build on debian

### ISSUE THREAD

**Issue by victorpigmeo** [yuezk/GlobalProtect-openconnect#257]
When I try to add the repository I got an error on `sudo apt update` saying that the repository don't have a Release file. And when I try to build from source it keeps asking me for the password of my ssh-key 100 times and at the and it says that the build finished with error. I'm on debian 11 with all the dependecies installed.

![image](https://github.com/yuezk/GlobalProtect-openconnect/assets/8128451/e22ef861-e2b2-41ea-beb5-6e7a1c4d7b57)
![image](https://github.com/yuezk/GlobalProtect-openconnect/assets/8128451/564f547a-ea19-498b-bf8a-34a60d28ac93)

**Comment by yuezk** [comment]
@victorpigmeo I have published it in the Mantic series. You could try to install it from the PPA again. Thanks.

**Comment by JP5457** [comment]
I'm having the same issue on Debian bookworm

**Comment by jono-phobos** [comment]
I'm also having the issue on Debian bookworm (trying to move over from ubuntu). Love this app btw, thank you so much @yuezk
