### ISSUE TITLE
error when running the program

### ISSUE THREAD

**Issue by galtthedestroyer** [yuezk/GlobalProtect-openconnect#258]
I just installed today.  I'm running an up to date KDE Neon Linux install.  Here's my error when I try to launch the program:

gpclient: symbol lookup error: /lib/x86_64-linux-gnu/libQt5Quick.so.5: undefined symbol: _ZN18QTextureGlyphCache8populateEP11QFontEngineiPKjPK11QFixedPoint, version Qt_5_PRIVATE_API

even though it didn't work, thanks for the program!  I'm sure the issue will be fixed.

**Comment by yuezk** [comment]
No longer a problem in 2.x
