### ISSUE TITLE
ERR_CERT_AUTHORITY_INVALID

### ISSUE THREAD

**Issue by rednag** [yuezk/GlobalProtect-openconnect#260]
I'm connected and I can access the machines in our network, but I'm not able to access any websites using your client - I'm always getting notified -> **ERR_CERT_AUTHORITY_INVALID**

**Comment by asonirh** [comment]
I am facing the same issue. Is their any solution you were able to figure out ?

**Comment by giangdip2410** [comment]
I have a same issue. Anybody fix the bug?

**Comment by yuezk** [comment]
Should be fixed in 2.x. Reopen it if not.
