### ISSUE TITLE
not able to connect to internet

### ISSUE THREAD

**Issue by Yusheng-cai** [yuezk/GlobalProtect-openconnect#266]
I'm trying to connect to vpn.upenn.edu on ubuntu 20.04, the vpn connects no problem and I'm able to ssh to certain ip address that's within Penn's network, however, I am no longer able to browse the internet (e.g. loading google or youtube on Chrome takes forever). I'm pretty new to this, I was wondering if anyone can give some pointers, thanks!

**Comment by yuezk** [comment]
Staled issue. If this problem still exists in 2.x, I'm happy to help. Closing for now.
