### ISSUE TITLE
hipreport

### ISSUE THREAD

**Issue by nreith** [yuezk/GlobalProtect-openconnect#27]
Does this support any settings or configuration?
Or inclusion of a `hipreport.sh` file?

Thanks!

**Comment by yuezk** [comment]
@nreith Is it the same requirement as #7? If yes, please refer to the solution to that issue.

**Comment by nreith** [comment]
Yes. Same question. Does that answer mean you can only launch it via cli?

**Comment by yuezk** [comment]
@nreith No, this argument is appended to the service that the GUI application could launch in the background. You still using the GUI client to connect the VPN server.

**Comment by yuezk** [comment]
It should have been resolved in 1.3.0, as described in https://github.com/yuezk/GlobalProtect-openconnect#passing-the-custom-parameters-to-openconnect-cli
