### ISSUE TITLE
This site can’t be reached: ERR_CERT_AUTHORITY_INVALID

### ISSUE THREAD

**Issue by giangdip2410** [yuezk/GlobalProtect-openconnect#277]
When I tried to log in the App on Linux system, I face the below issue (When I tested on Window11, it worked well). If you have any solution for the bug, please share with me. Thank you in advance.

This site can’t be reached
The webpage at https://***.8888.***.edu/idp/profile/SAML2/Redirect/SSO?SAMLRequest=hZHfb4IwEMf%2FFdJ3aa0wYiMkTB9m4iIRtoe9LKWcswm0rFfM%2Fvyhzsy9uMfLfX%2FkPrdA2bW9yAd%2FMDv4HAB98NW1BsV5kZLBGWElahRGdoDCK1HmzxvBQyZ6Z71VtiVBjgjOa2uW1uDQgSvBHbWCl90mJQfvexSU...........................................................................................D might be temporarily down or it may have moved permanently to a new web address.
ERR_CERT_AUTHORITY_INVALID

**Comment by yuezk** [comment]
Should be fixed in 2.x, where you can configure to ignore the TLS errors. Reopen if not.
