### ISSUE TITLE
a failed attempt at using 2.0.0-beta1 on Debian Bullseye with Okta

### ISSUE THREAD

**Issue by martindorey** [yuezk/GlobalProtect-openconnect#279]
I'm running Debian Bullseye.  I'd previously built from source, as explained in https://github.com/yuezk/GlobalProtect-openconnect/issues/184#issuecomment-1427123022.  The instructions for building from source don't seem to have been updated for 2.0.0-beta1.  I eventually guessed my way to:
```
mad@shuttle:~/Downloads/GlobalProtect-openconnect/GlobalProtect-openconnect$ cargo build
error: failed to parse manifest at `/u2/home/mad/Downloads/GlobalProtect-openconnect/GlobalProtect-openconnect/Cargo.toml`

Caused by:
  invalid type: unit variant, expected string only for key `profile.release.strip`
mad@shuttle:~/Downloads/GlobalProtect-openconnect/GlobalProtect-openconnect$ 
```
... which Google suggested was likely due to a downrev version of Rust.  There was no offputting message about Ubuntu or other flavors of Linux this time, so I thought I'd try the amd64.deb.  The dependencies don't appear to be quite right because, while that installed fine, I got this:
```
mad@shuttle:~$ gpclient&
[6] 2479555
mad@shuttle:~$ gpclient: /lib/x86_64-linux-gnu/libopenconnect.so.5: version `OPENCONNECT_5_7' not found (required by gpclient)
```
That was hurdled easily enough with `sudo aptitude install -t bullseye-backports openconnect`.  Then I could start the GUI and try to connect.  Sometimes I'd get quick failures after the password like:
```
Error GT1001. Please contact Global Service Center at [email](mailto:%20<my company IT>)
```
Sometimes the password and two-step Okta authentication would go through but the initial GUI window would say "Authenticating (2 of 5)" and a login pane would pop up flashing "Got invalid token, retrying..." at some epilepsy-inducing frequency.  Only while writing up this did I leave that going for long enough to see it finish and give me a login prompt again.  But it just left me in the same place, this time after visibly saying "Login successful".  I think the first time and a few times since, it felt like I got further, only to have a failure reported in the initial GUI window about a failed dns response for a URL involving my company's VPN gateway.  Sorry, I didn't write down the exact message and, being a GUI thing, there's no paper trail in my terminal window.  When I did `host <DNS name>` that worked fine.  `/etc/resolv.conf` was still pointing at 8.8.8.8.  When, however, I did `getent ahosts <DNS name>`, I got nothing back.  Gah, `sudo nscd --invalidate=hosts` to the rescue.  I saw that failure mode four times at the beginning but it won't seem to happen again. 

Giving up and going back to the 1.4.9 client, I got a DNS failure for <my company>.okta.com in the login pane.  Ah, maybe that accounts for DNS pauses.  I wasn't checking that with getent.  I've had a few goes now and got stuck at "Authenticating..." after the login pane has disappeared following a successful two-step Okta authentication.  Perhaps something's amiss with the bullseye-backports versions of the underlying code that I installed.  Perhaps they don't work with 1.4.9.  I tried downgrading openconnect and libopenconnect5.  Still no dice.  Finally, I tried stopping nscd.  "Connected" at last!  Being an idiot, I disconnected, upgraded openconnect and libopenconnect5 and tried to connect again.  Connected at the first go!  Back to 2.0.0-beta1.  This time it went through the Okta two-step more quickly but "Got invalid token, retrying..." appeared briefly before it wanted a "2 of 5" go, which led to a "3 of 5" go where it cleared the credentials that had been remembered, followed by a GT1001.  Back to the old thing, Connected first time.  The recent 2.0.0-beta1 tests were with it configured to say it was Linux, because I think the old thing was doing that, but I just had one final try with it in the default setting where it's configured to say it's Windows and that behaved the same as my previous Linux go.

Right, so the new version here is broken for me and there's some unfortunate interaction with nscd, likely making both versions more flaky than they otherwise would be, so perhaps more relating to the underlying code.  https://github.com/systemd/systemd/issues/7074#issuecomment-338157851 is what perhaps convinced me that nscd is compulsory with the success of Poettering's systemd juggernaut.

**Comment by yuezk** [comment]
@martindorey Thanks for your feedback.

1. Yes, the readme doc is not yet updated, so the building instructions of building from the source code no longer apply. I will update the doc soon.
2. This project depends on openconnect, so we must install it. But I have added to the deb's dependencies field, that it should install openconnect when installing the deb. I tested it in Ubuntu but didn't check it on Debian. Will check it later.
3. Regarding `Got invalid token, retrying...` and `Authenticating (2 of 5)...`. This is because the SSO authentication part is pretty unstable (I don't know how to describe it precisely).

	The scenario is, that we usually couldn't get the auth token, even though we have performed the authentication. My experience is that retry the authentication workflow, and it could finally get the auth token. That's why you could see `Got invalid token, retrying...`.
	
	Another problem is that even though we get the auth token, we cannot fetch the VPN portal configuration using this auth token, and my experience is that retrying the authentication workflow could get the VPN portal configuration finally. That's why you see `Authenticating (2 of 5)...`. It will try it 5 times at most, and display an error if failed.

	I have a similar authentication problem when working with the official client on macOS. Whenever this happens, I just retry it manually, so I make it retry automatically in my client. 
4. The new version client provides better CLI support, the GUI client is **optional**. You can use the `gpclient` command to connect your portal. See `gpclient -h` for more details.
5. I use `Windows` as the default user agent simulation because I found it works better with my VPN portal, I often encounter problems when using `Linux` as the UA simulation. So, I make it the default.

BTW, where is this error reported from: `Error GT1001. Please contact Global Service Center at [email](mailto:%20<my company IT>)`, I have no idea who reported it. Because I never experience it.

**Comment by martindorey** [comment]
> I have added to the deb's dependencies field

Indeed, but not with the right version constraint.

```
mad@shuttle:~$ apt-cache policy openconnect
openconnect:
  Installed: 9.01-2~bpo11+1
  Candidate: 9.01-2~bpo11+1
  Version table:
 *** 9.01-2~bpo11+1 100
        100 http://mirrors.xmission.com/debian bullseye-backports/main amd64 Packages
        100 /var/lib/dpkg/status
     8.10-2+b1 500
        500 http://mirrors.xmission.com/debian bullseye/main amd64 Packages
```
The bullseye version wasn’t new enough but the bullseye-backports version was.  That much I know for sure but I might speculate that:

https://gitlab.com/openconnect/openconnect/-/blob/master/libopenconnect5.symbols?ref_type=heads#L9

… is telling us that the 5.7 symbol I needed was first supplied in version 8.20, whereas you’ve got it set to `Depends: openconnect (>= 8.0)`.  Upstream’s change log doesn’t make it clear.

> where is this error reported from

In what I’ve called above “the login pane”.  It happens very quickly after hitting Enter on my password, almost too quickly to have even checked whether I’ve been locked out.  To my surprise, I wasn’t, despite umpty-dozen go-arounds here today.  Likely specific to <my company>.  Googling for the error code and Okta tells you what <my company> is, so I don’t know why I’m persisting with the secret squirrel act.

**Comment by kokizzu** [comment]
similar thing on Pop!_OS 22.04, downgrading to 1.x works tho..

**Comment by acossette** [comment]
Similar problem on Ubuntu 23.10 with newer version. Works great in 1.x:

![image](https://github.com/yuezk/GlobalProtect-openconnect/assets/571403/1c1493c3-cf9b-4d89-8676-628798a0ec87)

**Comment by yuezk** [comment]
The authentication problem is similar to #280. This has been fixed in 2.0.0-beta2

**Comment by martindorey** [comment]
I had a go with 2.0.0-beta2.  I still couldn't connect.  The flashing retry problem is fixed.  Behavior isn't always quite the same.  The first two times I tried, I got GT1001 immediately after giving my password, with no Okta interaction.  After switching back to 1.4.9 to confirm that my account was OK and I'd remembered the password (yes and yes), I came back to 2.0.0-beta2 and this time got a single Okta interaction which led to the UI retrying and then failure.  I reproduced that a second time.  The bold made this sound important:

> The new version client provides better CLI support, the GUI client is **optional**

... so I then gave that a try, not really knowing which bits I should have manually <elided> in addition to the automatic b*****rization, which failed again but perhaps the output might tell our illustrious host what's going on:

```
mad@shuttle:~/Downloads/GlobalProtect-openconnect$ gpclient connect v<elided>m
[2024-01-20T16:31:55Z INFO  gpclient::cli] gpclient started: 2.0.0-beta2 (2024-01-18)
[2024-01-20T16:31:55Z INFO  gpapi::portal::prelogin] Portal prelogin, user_agent: PAN GlobalProtect
[2024-01-20T16:31:55Z INFO  gpauth::cli] gpauth started: 2.0.0-beta2 (2024-01-18)
[2024-01-20T16:31:55Z INFO  gpauth::auth_window] Open auth window, user_agent: PAN GlobalProtect
[2024-01-20T16:31:55Z INFO  gpauth::auth_window] Auth window user agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.0 Safari/605.1.15
[2024-01-20T16:31:55Z INFO  gpauth::auth_window] Load the SAML request as HTML...
[2024-01-20T16:31:55Z INFO  gpauth::auth_window] Loaded uri: about:blank
[2024-01-20T16:31:55Z INFO  gpauth::auth_window] Trying to read auth data from response headers...
[2024-01-20T16:31:55Z INFO  gpauth::auth_window] No headers found in response
[2024-01-20T16:31:55Z INFO  gpauth::auth_window] No auth data found in headers, trying to read from body...
[2024-01-20T16:31:55Z INFO  gpauth::auth_window] No auth data found in HTML
[2024-01-20T16:31:55Z INFO  gpauth::auth_window] No auth data found, it may not be the /SAML20/SP/ACS endpoint
[2024-01-20T16:31:55Z INFO  gpauth::auth_window] Raise window in 1 second(s)
[2024-01-20T16:31:55Z INFO  gpauth::auth_window] Raise window cancelled
[2024-01-20T16:31:57Z INFO  gpauth::auth_window] Loaded uri: https://s**********m/content/login-page.html?fromURI=h**********D
[2024-01-20T16:31:57Z INFO  gpauth::auth_window] Trying to read auth data from response headers...
[2024-01-20T16:31:57Z INFO  gpauth::auth_window] No saml-auth-status header found
[2024-01-20T16:31:57Z INFO  gpauth::auth_window] No auth data found in headers, trying to read from body...
[2024-01-20T16:31:57Z INFO  gpauth::auth_window] No auth data found in HTML
[2024-01-20T16:31:57Z INFO  gpauth::auth_window] No auth data found, it may not be the /SAML20/SP/ACS endpoint
[2024-01-20T16:31:57Z INFO  gpauth::auth_window] Raise window in 1 second(s)
[2024-01-20T16:31:58Z INFO  gpapi::utils::window] Raising window: GlobalProtect Login
[2024-01-20T16:31:58Z INFO  gpapi::utils::window] Window raised after 2 attempts
[2024-01-20T16:32:15Z INFO  gpauth::auth_window] Loaded uri: https://h**********m/app/panw_globalprotect/e<elided>7/sso/saml?RelayState=b**********%3D
[2024-01-20T16:32:15Z INFO  gpauth::auth_window] Trying to read auth data from response headers...
[2024-01-20T16:32:15Z INFO  gpauth::auth_window] No saml-auth-status header found
[2024-01-20T16:32:15Z INFO  gpauth::auth_window] No auth data found in headers, trying to read from body...
[2024-01-20T16:32:15Z INFO  gpauth::auth_window] No auth data found in HTML
[2024-01-20T16:32:15Z INFO  gpauth::auth_window] No auth data found, it may not be the /SAML20/SP/ACS endpoint
[2024-01-20T16:32:15Z INFO  gpauth::auth_window] Loaded uri: https://v**********m/SAML20/SP/ACS
[2024-01-20T16:32:15Z INFO  gpauth::auth_window] Trying to read auth data from response headers...
[2024-01-20T16:32:15Z INFO  gpauth::auth_window] Got auth data from headers
[2024-01-20T16:32:15Z INFO  gpapi::portal::config] Portal config, user_agent: PAN GlobalProtect

Error: Invalid auth cookie, retrying can help
mad@shuttle:~/Downloads/GlobalProtect-openconnect$ 
```
Depends is still openconnect (>= 8.0) rather than openconnect (>= 8.20), sad face.

**Comment by martindorey** [comment]
I tried again today with [v2.2.1](https://github.com/yuezk/GlobalProtect-openconnect/releases/tag/v2.2.1), got the same GT1001 error a few times... until I added --hip to the command line, having noticed this in the logs produced on stdout/stderr:
```
2024-05-18 12:42:08.733 INFO  [4159] [GPClient::onVPNLogAvailable@518] WARNING: Server asked us to submit HIP report with md5sum 83aa62f47abf314a49da5a99ca2739fe.
    VPN connectivity may be disabled or limited without HIP report submission.
    You need to provide a --csd-wrapper argument with the HIP report submission script.
```
I can't claim to have completely succeeded, because I'm now stuck at:
```
GPST Dead Peer Detection detected dead peer!
```
... but I'm using an unfamiliar endpoint today and I was getting the same error with the old GlobalProtect-openconnect 1.4.8, that I've been a happy user of for a while.  Perhaps I should reopen https://github.com/yuezk/GlobalProtect-openconnect/issues/268 but at least this issue's central mystery is solved.
