### ISSUE TITLE
'Error: Invalid auth cookie, retrying can help' with OpenConnect version v8.20-1

### ISSUE THREAD

**Issue by aallu-rythmos** [yuezk/GlobalProtect-openconnect#280]
I use `Ubuntu 22`. I've been using `GlobalProtect-openconnect` VPN client to login to VPN without any issues over a year, Today, I executed `apt update` and the client got updated to latest version. I thought its a good news, but it turned out to be a bad one. The new version is broken for me.

![image](https://github.com/yuezk/GlobalProtect-openconnect/assets/89516629/c83cff0d-d875-4410-a229-c68285417524)

```
[3.2.2]~ ➭ gpclient --fix-openssl xxxxx
[2024-01-18T04:51:34Z INFO  gpclient::cli] gpclient started: 2.0.0-beta.1 (2024-01-17)
[2024-01-18T04:51:34Z INFO  gpapi::portal::prelogin] Portal prelogin, user_agent: PAN GlobalProtect
[2024-01-18T04:51:40Z INFO  gpauth::cli] gpauth started: 2.0.0-beta.1 (2024-01-17)
[2024-01-18T04:51:40Z INFO  gpauth::cli] Fixing OpenSSL environment
[2024-01-18T04:51:40Z INFO  gpauth::auth_window] Open auth window, user_agent: PAN GlobalProtect
[2024-01-18T04:51:41Z INFO  gpauth::auth_window] Load the SAML request as HTML...
[2024-01-18T04:51:41Z INFO  gpauth::auth_window] Loaded uri: about:blank
[2024-01-18T04:51:41Z INFO  gpauth::auth_window] Trying to read auth data from response headers...
[2024-01-18T04:51:41Z INFO  gpauth::auth_window] No headers found in response
[2024-01-18T04:51:41Z INFO  gpauth::auth_window] No auth data found in headers, trying to read from body...
[2024-01-18T04:51:41Z INFO  gpauth::auth_window] No auth data found in HTML
[2024-01-18T04:51:41Z INFO  gpauth::auth_window] No auth data found, it may not be the /SAML20/SP/ACS endpoint
[2024-01-18T04:51:41Z INFO  gpauth::auth_window] Raise window in 1 second(s)
[2024-01-18T04:51:41Z INFO  gpauth::auth_window] Raise window cancelled
[2024-01-18T04:51:48Z INFO  gpauth::auth_window] Loaded uri: https://u**********m/app/panw_globalprotect/exk402mugovQhBPg22p7/sso/saml
[2024-01-18T04:51:48Z INFO  gpauth::auth_window] Trying to read auth data from response headers...
[2024-01-18T04:51:48Z INFO  gpauth::auth_window] No saml-auth-status header found
[2024-01-18T04:51:48Z INFO  gpauth::auth_window] No auth data found in headers, trying to read from body...
[2024-01-18T04:51:48Z INFO  gpauth::auth_window] No auth data found in HTML
[2024-01-18T04:51:48Z INFO  gpauth::auth_window] No auth data found, it may not be the /SAML20/SP/ACS endpoint
[2024-01-18T04:51:48Z INFO  gpauth::auth_window] Raise window in 1 second(s)
[2024-01-18T04:51:49Z INFO  gpapi::utils::window] Raising window: GlobalProtect Login
[2024-01-18T04:51:49Z INFO  gpapi::utils::window] Window raised after 1 attempts
[2024-01-18T04:53:24Z INFO  gpauth::auth_window] Loaded uri: https://u**********m/login/token/redirect?stateToken=0**********w
[2024-01-18T04:53:24Z INFO  gpauth::auth_window] Trying to read auth data from response headers...
[2024-01-18T04:53:24Z INFO  gpauth::auth_window] No saml-auth-status header found
[2024-01-18T04:53:24Z INFO  gpauth::auth_window] No auth data found in headers, trying to read from body...
[2024-01-18T04:53:24Z INFO  gpauth::auth_window] No auth data found in HTML
[2024-01-18T04:53:24Z INFO  gpauth::auth_window] No auth data found, it may not be the /SAML20/SP/ACS endpoint
[2024-01-18T04:53:30Z INFO  gpauth::auth_window] Loaded uri: https://v**********m/SAML20/SP/ACS
[2024-01-18T04:53:30Z INFO  gpauth::auth_window] Trying to read auth data from response headers...
[2024-01-18T04:53:30Z INFO  gpauth::auth_window] Got auth data from headers
[2024-01-18T04:53:30Z INFO  gpapi::portal::config] Portal config, user_agent: PAN GlobalProtect

Error: Invalid auth cookie, retrying can help
```

I use `okta` for VPN of my organization's VPN gateway. 

**This is the error I get `Error: Invalid auth cookie, retrying can help`**

I tried with UI client and the cli too, both give the same response, I don't think I would be able to use openconnect anymore , its been my savior for over than a year.** 

![image](https://github.com/yuezk/GlobalProtect-openconnect/assets/89516629/ead34901-69f7-482f-a05b-f9a47b66b5fc)

I suspect its got to do with the cookies,
`user_agent: PAN GlobalProtect`

I cannot be able to check in the `remeber me for 30 days` which I usually do, this time, I am not able to click the check box,
![image](https://github.com/yuezk/GlobalProtect-openconnect/assets/89516629/80fb5db5-f136-44fe-8037-a66dbbed8afc)

I don't know how to change the user agent to a browser like `google chrome` instead of `PAN GlobalProtect`, as I can be able to tick the `remember me` checkbox and It would help me not go through the `5` retries trying to get the token from the cookies.

I am sure the upgrade to latest version is causing this behavior, not sure if it can be fixed, but wanted to let you guys know about it. 

Thanks for what you've been doing with this client so far. Its been a delight until the latest version of the UI client.

**Comment by yuezk** [comment]
<img width="782" alt="image" src="https://github.com/yuezk/GlobalProtect-openconnect/assets/3297602/21746e0d-2d81-4fd0-8602-ceafd82c66ee">

Have you ever tried to change the options on the settings page?

**Comment by aallu-rythmos** [comment]
> <img alt="image" width="782" src="https://private-user-images.githubusercontent.com/3297602/297626200-21746e0d-2d81-4fd0-8602-ceafd82c66ee.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU1NTU3MTYsIm5iZiI6MTcwNTU1NTQxNiwicGF0aCI6Ii8zMjk3NjAyLzI5NzYyNjIwMC0yMTc0NmUwZC0yZDgxLTRmZDAtODYwMi1jZWFmZDgyYzY2ZWUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDExOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMThUMDUyMzM2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YTFhODEyZDNhZDcyMzc4NDA4NmY0MDM2YTljNTIyZDdiYzIyYjNjNDFhZmVjYjA5OTQ1NDlkMWJlZTFiMThjNyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.RvSyTdriq6zxq54LFbmhvgUbJmBVPXWn2_KG8d-FNg0">
> Have you ever tried to change the options on the settings page?

Thanks for response. Yeah, it was defaulted to windows I guess, after my auth attempts were failing I changed it to `Linux` and tried too, still didn't work. I tried to disable and enable `OpenSSL` config options too, then also it failed. I tried all setting combinations possible and then only clicked on `feedback` and opened this issue here.

**Comment by Davegb** [comment]
Same here. Previous version was working.

**Comment by aallu-rythmos** [comment]
I uninstalled the latest broken version of `GlobalProtect-openclient` and installed the last working version `v1.4.9`. I am able to connect to VPN without any issues in this version. Below are the steps that can help others who are facing connection issues as in this issue.

**Ubuntu 22.04.3 LTS**
1. `sudo dpkg -P globalprotect-openconnect`
2. `cd /opt`
3. ``wget https://github.com/yuezk/GlobalProtect-openconnect/releases/download/v1.4.9/globalprotect-openconnect-1.4.9.tar.gz`
4. `tar -xzf globalprotect-openconnect-1.4.9.tar.gz`
5. `cd globalprotect-openconnect-1.4.9`
6. `./scripts/install-ubuntu.sh`
7. `gpclient`

**Comment by huang-jy** [comment]
I have the same problem. I know it's not openconnect as I can use gp-saml-gui (https://github.com/dlenski/gp-saml-gui) and it still works and is my interim solution until this is fixed.

I am on openconnect v9.12

```
OpenConnect version v9.12
Using GnuTLS 3.8.2. Features present: TPM, TPMv2, PKCS#11, RSA software token, HOTP software token, TOTP software token, Yubikey OATH, System keys, DTLS, ESP
Supported protocols: anyconnect (default), nc, gp, pulse, f5, fortinet, array
Default vpnc-script (override with --script): /etc/vpnc/vpnc-script
```

**Comment by zoharsnir** [comment]
Thanks @aallu-rythmos for the quick how-to. Worked for me.

**Comment by rmontanana** [comment]
I have the same problem and tried to use the 1.4.9 in my Fedora 39, but got this message:
```
[ 63%] Linking CXX executable gpclient
/usr/bin/ld: /usr/lib64/libQt5Quick.so.5.15.11: undefined reference to `QWindow::setVulkanInstance(QVulkanInstance*)@Qt_5'
/usr/bin/ld: /usr/lib64/libQt5Quick.so.5.15.11: undefined reference to `QVulkanInstance::setLayers(QList<QByteArray> const&)@Qt_5'
/usr/bin/ld: /usr/lib64/libQt5Quick.so.5.15.11: undefined reference to `QTextureGlyphCache::populate(QFontEngine*, int, unsigned int const*, QFixedPoint const*, bool)@Qt_5_PRIVATE_API'
/usr/bin/ld: /usr/lib64/libQt5Quick.so.5.15.11: undefined reference to `QWindow::vulkanInstance() const@Qt_5'
/usr/bin/ld: /usr/lib64/libQt5Quick.so.5.15.11: undefined reference to `QVulkanInstance::QVulkanInstance()@Qt_5'
/usr/bin/ld: /usr/lib64/libQt5Quick.so.5.15.11: undefined reference to `QVulkanInstance::setExtensions(QList<QByteArray> const&)@Qt_5'
/usr/bin/ld: /usr/lib64/libQt5Quick.so.5.15.11: undefined reference to `QVulkanInstance::create()@Qt_5'
/usr/bin/ld: /usr/lib64/libQt5Quick.so.5.15.11: undefined reference to `QVulkanInstance::~QVulkanInstance()@Qt_5'
collect2: error: ld returned 1 exit status
gmake[2]: *** [GPClient/CMakeFiles/gpclient.dir/build.make:476: GPClient/gpclient] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:353: GPClient/CMakeFiles/gpclient.dir/all] Error 2
gmake: *** [Makefile:136: all] Error 2
```

**Comment by yuezk** [comment]
The UA problem has been fixed in 2.0.0-beta2, closing.

**Comment by rmontanana** [comment]
Tried beta 2 and still got the same message, I've tried to change the client to windows (I've got Fedora 39), to Linux but nothing seems to work anyway. I've cleared the credentials to start from scratch with beta 2 but didn't have any luck with this.

**Comment by 4mig4** [comment]
Same for me

**Comment by 4mig4** [comment]
is there a way we can get back the old GUI as well  ?  the deb package is gone for 1.49

**Comment by sh4t7er** [comment]
> I uninstalled the latest broken version of `GlobalProtect-openclient` and installed the last working version `v1.4.9`. I am able to connect to VPN without any issues in this version. Below are the steps that can help others who are facing connection issues as in this issue.
> 
> **Ubuntu 22.04.3 LTS:**
> 
>     1. `sudo dpkg -P globalprotect-openconnect`
> 
>     2. `cd /opt`
> 
>     3. `wget https://github.com/yuezk/GlobalProtect-openconnect/releases/download/v1.4.9/globalprotect-openconnect-1.4.9.tar.gz`
> 
>     4. `tar -xzf globalprotect-openconnect-1.4.9.tar.gz`
> 
>     5. `cd globalprotect-openconnect-1.4.9`
> 
>     6. `./scripts/install-ubuntu.sh`
> 
>     7. `gpclient`

This workaround works great! Is there an easy way to uninstall this workaround for when the bug gets fixed?

**Comment by other-juan** [comment]
@sh4t7er I did that yesterday and everything was working but two hours ago the VPN disconnected and now it drops a `Segmentation fault (core dump)` when I try to connect to a gateway.

**Comment by aallu-rythmos** [comment]
> > I uninstalled the latest broken version of `GlobalProtect-openclient` and installed the last working version `v1.4.9`. I am able to connect to VPN without any issues in this version. Below are the steps that can help others who are facing connection issues as in this issue.
> > **Ubuntu 22.04.3 LTS:**
> > ```
> > 1. `sudo dpkg -P globalprotect-openconnect`
> > 
> > 2. `cd /opt`
> > 
> > 3. `wget https://github.com/yuezk/GlobalProtect-openconnect/releases/download/v1.4.9/globalprotect-openconnect-1.4.9.tar.gz`
> > 
> > 4. `tar -xzf globalprotect-openconnect-1.4.9.tar.gz`
> > 
> > 5. `cd globalprotect-openconnect-1.4.9`
> > 
> > 6. `./scripts/install-ubuntu.sh`
> > 
> > 7. `gpclient`
> > ```
> 
> This workaround works great! Is there an easy way to uninstall this workaround for when the bug gets fixed?

This software uses `cmake` . When you build from `cmake`, the `build` folder will get a `install_manifest.txt` file inside ir. You need to manually remove the files listed in this file
![image](https://github.com/yuezk/GlobalProtect-openconnect/assets/89516629/913b551a-d1ac-4038-a8d5-66600dc693ba)
![image](https://github.com/yuezk/GlobalProtect-openconnect/assets/89516629/2f997f93-661e-4831-a074-f654af96eaf2)

`sudo systemctl status gpservice.service `
`sudo systemctl is-enabled gpservice.service`

before doing it, we can stop the service - `gpservice.service`
1. `sudo systemctl disable gpservice.service`
2. `sudo systemctl daemon-reload`
3. Now, manually delete all the files in the `install_manifest.txt` in the `build` folder of the extracted `globalprotect-openconnect-1.4.9` folder.

These should work, however, I haven't uninstalled the `1.49` version yet.

[uninstall software built from cmake reference](https://www.reddit.com/r/linuxquestions/comments/6skvr7/how_to_uninstall_something_i_build_from_source/)

**Comment by aallu-rythmos** [comment]
> @sh4t7er I did that yesterday and everything was working but two hours ago the VPN disconnected and now it drops a `Segmentation fault (core dump)` when I try to connect to a gateway.

I too had this errors with the VPN software clients in Ubuntu OS, I think we need to do a clean installation.

1. `sudo apt-get autoclean`
2. `sudo apt-get clean`
3. `sudo apt-get autoremove`
4. `sudo apt-get update`
5. `sudo apt-get upgrade`
6. [remove installed package](https://github.com/yuezk/GlobalProtect-openconnect/issues/280#issuecomment-1901154165)
7. retry building from the source again.
