### ISSUE TITLE
New payed version 2?

### ISSUE THREAD

**Issue by bodograumann** [yuezk/GlobalProtect-openconnect#281]
We have observed some worrying developments:
- The ubuntu ppa offers a beta version on the stable channel: https://launchpad.net/~yuezk/+archive/ubuntu/globalprotect-openconnect
- This new version is automatically installed on update for existing users.
- It shows a "14d trial" notice and says a license need to be purchased on https://yuezk.lemonsqueezy.com/checkout
- The app doesn't seem to correspond to this repo, as I cannot find any mentions of trial / license in the code or any announcement about it.
- The lemonsqueezy page is not mentioned anywhere in this repo either.

Is that an attempt from someone else to profit from this app or simply a miscommunication?

**Comment by yosh-se** [comment]
Same here, the screenshot from the release page states "Donate" instead of "Trial (13d)".
I can't seem to be able to find any information about this transition?

**Comment by yuezk** [comment]
Yes, it's me, planning to make the future GUI version as a paid software. I'm still working on the document updating. 

You could still use the CLI version, see `gpclient -h`, it's always free and totally open sourced in this repo, it provides almost the same functions as the GUI. The GUI version is just a wrapper.

If you don't like it, you can still using the old version, `1.4.9`, it's under the [1.x branch](https://github.com/yuezk/GlobalProtect-openconnect/tree/1.x). Or any other alternatives, like https://github.com/dlenski/gp-saml-gui.

Hope you understand it. Thanks.

**Comment by zoharsnir** [comment]
For anybody trying to quickly recover from this and get back to previous version, see https://github.com/yuezk/GlobalProtect-openconnect/issues/280#issuecomment-1897922829

**Comment by wolfram-ostec** [comment]
Getting a beta installed automatically that doesn't work but requires a licence feels weird.

**Comment by yuezk** [comment]
Document updated, closing.

**Comment by guilhermegps** [comment]
It's really a pity. It was a good project for the community. Thanks for your contribution until here.
