### ISSUE TITLE
error secure storage-manjaro wayland

### ISSUE THREAD

**Issue by userofryzen** [yuezk/GlobalProtect-openconnect#284]
Manjaro Linux (testing) (wayland plasma) downloading the latest release in your github page. 

![imagen](https://github.com/yuezk/GlobalProtect-openconnect/assets/33232977/6c0fa3aa-4cff-4ee2-b602-03d958cb7e15)

And another bug with only terminal, with the same package. 

![imagen](https://github.com/yuezk/GlobalProtect-openconnect/assets/33232977/d6960d58-c45b-4565-9894-7f51acc434ab)

I will revert to the older one that was working correct without much issues. I don't think we needed much more than we had, maybe only the bugs with some specific stuff but I couldn't test the new package for obvious reasons. 

If it's not much to ask, how much the license will cost?

**Comment by userofryzen** [comment]
[2024-01-18T20:53:30Z INFO gpservice::cli] gpservice started: 2.0.0-beta2 (2024-01-18)
[2024-01-18T20:53:30Z INFO gpservice::ws_server] WS server listening on port: 45173
[2024-01-18T20:53:30Z INFO  gpgui::cli] gpgui started: 2.0.0-beta2 (2024-01-18)
[2024-01-18T20:53:30Z INFO  gpgui::app] Setting the custom openssl conf path
[2024-01-18T20:53:30Z WARN  gpgui::app::app_initializer] Can't read the config key from the keyring: Platform secure storage failure: zbus error: org.freedesktop.DBus.Error.ServiceUnknown: The name is not activatable
[2024-01-18T20:58:29Z INFO gpservice::cli] Shutdown signal received
[2024-01-18T20:58:29Z INFO gpservice::vpn_task] VPN task cancelled
[2024-01-18T20:58:29Z INFO gpservice::vpn_task] VPN is not connected, skip disconnect
[2024-01-18T20:58:29Z INFO gpservice::ws_server] WS server cancelled
[2024-01-18T20:58:29Z INFO gpservice::cli] gpservice stopped

**Comment by yuezk** [comment]
@userofryzen For the secure storage problem, can you help ensure that the [KDE_Wallet](https://wiki.archlinux.org/title/KDE_Wallet) is installed? I will also test it on Manjaro Wayland myself to investigate later.

The CLI problem is a common problem I encountered with my VPN portal. As the message suggests, retrying the command could back to normal.

**Comment by yuezk** [comment]
I will keep releasing the new beta version until it becomes stable. Each beta version has a fresh 14 trial days. So you won't be asked to require a license as long as you are kept with the latest beta version. Or you could try the CLI version, which is always free to use.

**Comment by userofryzen** [comment]
> @userofryzen For the secure storage problem, can you help ensure that the [KDE_Wallet](https://wiki.archlinux.org/title/KDE_Wallet) is installed? I will also test it on Manjaro Wayland myself to investigate later.
> 
> The CLI problem is a common problem I encountered with my VPN portal. As the message suggests, retrying the command could back to normal.

About secure storage, I have tested on fresh install of manjaro xorg plasma( I have no time this week for working reasons) It appears that the problems comes from have disabled kwallet( I didn't use in my life so always disabling it when installing manjaro) I suppose that in wayland works well too, I'll let you know when I can test.

The cli problem, retrying the command doesn't help, error with the oath again

I could test the gui too with your beta package, the same as cli, error with auth, it doesn't mind if I change the user agent to linux or macos. The older worked perfect without doing anything special. 

So we can say that beta 2 is not working neverthless the error secure storage is gone or not...

Leave in standby this issue until I can test on wayland pls, or if you test it in manjaro and works for you feel free to close this issue. 

On another side I have to say, if you permit me that I have seen the prices of this app for curiosity and think about buy one when all this issues are fixed, multiple choices is good idea, but the prices... I will use the older client I think, sorry.  To be honest I have started a week ago to use this client, what a news to an starter! hahaha

Regards! Good luck

**Comment by andrikevich** [comment]
> @userofryzen For the secure storage problem, can you help ensure that the [KDE_Wallet](https://wiki.archlinux.org/title/KDE_Wallet) is installed? I will also test it on Manjaro Wayland myself to investigate later.
> 
> The CLI problem is a common problem I encountered with my VPN portal. As the message suggests, retrying the command could back to normal.

I have the same issue. And retrying didn't help me. Only rollback to previous version works well.

**Comment by userofryzen** [comment]
> > @userofryzen For the secure storage problem, can you help ensure that the [KDE_Wallet](https://wiki.archlinux.org/title/KDE_Wallet) is installed? I will also test it on Manjaro Wayland myself to investigate later.
> > The CLI problem is a common problem I encountered with my VPN portal. As the message suggests, retrying the command could back to normal.
> 
> I have the same issue. And retrying didn't help me. Only rollback to previous version works well.

I think I will use the older ones that doesn't give me any big problem. At least for now, but I have used it 1 hour in total amount.. I have started the last week to use it!
The gui of the new ones to be honest it was cool but honestly I think don't worth all the work that is giving with the launch to @yuezk . May be it's because I have not used it much and I have not see the bugs or anything else on the older one.

**Comment by userofryzen** [comment]
Yes it works un manjaro wayland

**Comment by yuezk** [comment]
Looks problem is resolved. Closing.
