### ISSUE TITLE
Feren OS 2023.04 fresh install gpclient not running

### ISSUE THREAD

**Issue by mmorri** [yuezk/GlobalProtect-openconnect#286]
Hi,

I have a fresh installation of Feren OS 2023.04; I tried to install gpclient using the instruction in the code page, but when I try to run the gui or the terminal gpclient command I have the following error

`gpclient: /lib/x86_64-linux-gnu/libopenconnect.so.5: version `OPENCONNECT_5_7' not found (required by gpclient)`

I have installed all required dependencies, so I am a bit lost. 

Thanks,
Maurizio

**Comment by antaveiv** [comment]
Hi,
exactly the same error on Mint
thanks

**Comment by yuezk** [comment]
`OPENCONNECT_5_7` missing should be relatively easy to fix, I'm checking on this.

**Comment by yuezk** [comment]
@mmorri This client requires openconnect >= 8.20 (8.0 no longer works), please check the installed openconnect version.

@antaveiv If you are installing the client using PPA, you can try to update it. I have uploaded openconnect 9.12 to the PPA.
