### ISSUE TITLE
Strange new issue on Ubuntu 20.04

### ISSUE THREAD

**Issue by tzhao42** [yuezk/GlobalProtect-openconnect#289]
First, thank you for making this app! :partying_face: Regular globalprotect UI's embedded browser does not seem to work with Duo 2FA but this app works seamlessly; you have saved me many a cold walk to the office...

System is `Ubuntu 20.04.6 LTS x86_64`; installed via `sudo apt update; sudo apt install globalprotect-openconnect`. Worked fine about a month ago; used it again last night and client no longer starts:

```
user@machine:~/vpn $ gpclient
gpclient: /lib/x86_64-linux-gnu/libopenconnect.so.5: version `OPENCONNECT_5_7' not found (required by gpclient)
```
Seems related to #286. I tried reverting back to 1.4.8 (a version that used to run fine on my machine):
```
user@machine:~/vpn $ gpclient
gpclient: /lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by gpclient)
```
I originally installed 1.4.8 via `apt` and so did not build from source -- perhaps the current problem is in how I'm building from source? I'm running `./scripts/install_ubuntu.sh` as recommended by readme, so not sure what's going on there; if you still have a 1.4.8 deb then it would be nice to check this...

Also tried reinstalling current version (same `OPENCONNECT_5_7' not found ` error) , tried manually building and installing 1.4.9 (same `GLIBCXX_3.4.29' not found` error), nothing worked.

I don't really understand this error and would appreciate any pointers on how to resolve. Thank you!

**Comment by tzhao42** [comment]
Update: I still have not gotten the new 2.0 beta version to work, but I have fixed my current problem by building 1.4.9 and manually installing a dependency for `GLIBCXX_3.4.29`.

Manually install `GLIBCXX_3.4.29` (from [this stackoverflow post](https://stackoverflow.com/questions/65349875/where-can-i-find-glibcxx-3-4-29)):

```bash
sudo add-apt-repository ppa:ubuntu-toolchain-r/test # Ignore if not ubuntu
sudo apt-get update
sudo apt-get install gcc-4.9
sudo apt-get upgrade libstdc++6
sudo apt-get dist-upgrade
```

Then build `1.4.9` from source:

```
wget https://github.com/yuezk/GlobalProtect-openconnect/releases/download/v1.4.9/globalprotect-openconnect-1.4.9.tar.gz
tar -xzf globalprotect-openconnect-1.4.9.tar.gz
cd globalprotect-openconnect-1.4.9
./scripts/install-ubuntu.sh
gpclient
```

**Comment by yuezk** [comment]
2.x requires openconnect >= 8.20, I have uploaded openconnect 9.12 to the PPA, if you installed the software via PPA, you can try to update it.

**Comment by ap91484** [comment]
To build 1.4.9 on an Arm system:
In the script **cmakew**, replace **X86_64** in the download_link string to **aarch64**.

**Comment by yuezk** [comment]
> 2.x requires openconnect >= 8.20, I have uploaded openconnect 9.12 to the PPA, if you installed the software via PPA, you can try to update it.

Closing.
