### ISSUE TITLE
Incorrect MTU set or not set at all?

### ISSUE THREAD

**Issue by emead-indeed** [yuezk/GlobalProtect-openconnect#29]
It seems like GP either doesn't set the MTU correctly or doesn't at all on connection. My tun0 defaults to 1500, which doesn't work as the actual MTU is much lower.

After connecting I use incrementing pings to detect it (really hacky), then set it manually:
```
last=1300; 
for s in {1300..1500}; do
    ping -c 1 -W 1 -s $s 1.1.1.1 &>/dev/null; 
    if [ "$?" -eq 0 ]; then 
        last=$s; 
    else 
        echo "$last+28"|bc;  
        break; 
    fi
done
```
In my case the MTU varies between 1372 and 1390 depending on the vpn I am connecting to.

OS: Arch Linux
Kernel: Linux no 5.8.1-arch1-1
Network: systemd-networkd (systemd 246.1-1)

I am curious if this might be an issue with my network stack or GP, but it seems like GP might be at fault here.

**Comment by yuezk** [comment]
This GUI client doesn't specify any MTU and has no MTU-related logic inside it. Looks like MTU can be set through the openconnect command line.

```
-m,--mtu=MTU

Request MTU from server as the MTU of the tunnel.

--base-mtu=MTU

Indicate MTU as the path MTU between client and server on the unencrypted network. Newer servers will automatically calculate the MTU to be used on the tunnel from this value.
```

You can follow [this link](https://github.com/yuezk/GlobalProtect-openconnect/issues/7#issuecomment-606984548) to pass these arguments to openconnect if you like.

**Comment by yuezk** [comment]
These arguments can be added through https://github.com/yuezk/GlobalProtect-openconnect#passing-the-custom-parameters-to-openconnect-cli in version 1.3.0

I'm closing this and let me know if you still have problems. Thanks.
