### ISSUE TITLE
Remove GlobalProtect-openconnect from PPA, COPR, OBS since GUI is not Open Source, Remove GPLv3 license info from documentation

### ISSUE THREAD

**Issue by kuba86** [yuezk/GlobalProtect-openconnect#296]
Since project is no longer 100% Open Source (GUI part is not), the license https://github.com/yuezk/GlobalProtect-openconnect/blob/main/LICENSE should be changed to reflect that.

When user visits the license file, one can read in GitHub summary:

Permissions:
- [x] Commercial use
- [x] Modification
- [x] Distribution
- [x] Patent use
- [x] Private use

This can give impression that one can take the code or rpm, deb file and modify it - let's say remove code responsible for license check and it will be ok. This is probably not the intention of the author since it will allow for not paying for the software. 

Since files in release page include Non-Open Source they should not be included in this repo. 

Once the license is changed to reflect changes from version 2.0.0, the author should remove `GlobalProtect-openconnect` from PPA, COPR, OBS, AUR since GUI is not Open Source. As a Fedora user, I user CORP, and in Terms and Conditions there are specific licenses that are allowed for repositories in CORP https://docs.pagure.org/copr.copr/user_documentation.html#what-i-can-build-in-copr Non-Open Source software is not allowed there. 

Perhaps this repo should be for Open Source part (CLI), and a dedicated GUI in a separate repo, with Non-Open Source license? This would allow for inclusion in PPA, COPR, OBS, AUR for the CLI and add information in documentation that there is "Pro" or "GUI" propitiatory version?

**Comment by yuezk** [comment]
@kuba86 

Thanks for raising this issue.

I have considered this before. The license has not been updated fully yet.

- The `openconnect` crate dynamically links to `libopenconnect` which is licensed under LGPL-2.1. This means that the `openconnect` crate can be licensed under GPL-3.0.
- The `gpapi` crates does not link to any proprietary code and is licensed under MIT.
- The `gpclient` binary depends on the `openconnect` crate and is licensed under GPL-3.0.
- The `gpauth` binary depends on the `gpapi`, which is licensed under MIT. It still makes sense to license it under GPL-3.0.
- The `gpservice` binary depends on the `gpapi` and `openconnect` crates and is licensed under GPL-3.0.
- The `gpgui` binary belongs to a different repository and it only depends on the `gpapi` crate. So, it can be licensed under a proprietary license.

For the distribution. I'm planning to distribute `gpclient`, `gpauth`, and `gpservice` as via the PPA, COPR, OBS, and AUR, and build from the source code. The `gpgui` will be distributed via another channel, e.g, GitHub releases, CDN, etc. And will be downloaded when the user wants to use the GUI as an optional feature.

I will update the license to reflect the changes. Thanks for the reminder.

**Comment by nemobis** [comment]
https://reuse.software/ may be helpful.

**Comment by yuezk** [comment]
The distribution from PPA, OBS, and CORP don't include the GUI components, closing.
