### ISSUE TITLE
gpclient CLI with external-browser

### ISSUE THREAD

**Issue by CalleB3** [yuezk/GlobalProtect-openconnect#298]
Hi,
How does one use the CLI and configure it to use an external-browser? Chrome in my case

I tried the new 2.0.0-beta5 release with GUI and that works, besides me getting invalid auth cookies.

I would want to use CLI with Chrome+yubikey, is that possible?
I see the `--user-agent` is that what should be used to accomplish this? if so, how?

![image](https://github.com/yuezk/GlobalProtect-openconnect/assets/91601778/00b25ff1-d2af-4d67-ad5f-37d770c91976)

**Comment by yuezk** [comment]
Planned in 2.2.0

**Comment by qraynaud** [comment]
This should be reopened since it was rollbacked. This would be very usefull to get this back.

**Comment by yuezk** [comment]
> This should be reopened since it was rollbacked. This would be very usefull to get this back.

@qraynaud What do you mean by this? I didn't roll back it.

Does `sudo -E gpclient connect --default-browser <portal>` work for you?

**Comment by qraynaud** [comment]
Sorry. I thought you had. It works on my local computer but not through vscode using remote-ssh. I’m puzzled as to why since `aws sso login` is opening my browser properly and working as expected.

**Comment by yuezk** [comment]
It doesn't support launching the default browser from within the SSH session. Are you using the aws cli from SSH session or the host? If the AWS cli works from the SSH session, I can refer to its implementation.

**Comment by qraynaud** [comment]
Yeah, I'm using the cli from the SSH session. This is somewhat cool!

**Comment by yuezk** [comment]
@qraynaud The remote SSH session support has been tracked by #375, so we can discuss it further.
