### ISSUE TITLE
Seg Fault after login

### ISSUE THREAD

**Issue by tpe11etier** [yuezk/GlobalProtect-openconnect#30]
It seems I'm logging in successfully, but immediately segfault when trying to bring up the token window.
Arch Linux
Any ideas?

2020-09-01 14:02:42.609 INFO  [127473] [gpclient::helper::parseGatewayResponse@50] Start parsing the gateway response...
2020-09-01 14:02:42.609 INFO  [127473] [gpclient::helper::parseGatewayResponse@51] The gateway response is: 
var respStatus = "Challenge";
var respMsg = "Krontech Single Connect Please Enter OTP";
thisForm.inputStr.value = "5f323dea0000bc23";
Segmentation fault

**Comment by yuezk** [comment]
The response said that you should enter the OTP, but there is no way to provide this information on the client.

This should be a new feature for this client.

I'm not sure about the workflow of this. Have you ever connect it on Windows or macOS, how they handle the OTP?

**Comment by advilm** [comment]
I'm also having this problem.
Here my university's documentation for how it works on [Windows](https://ucrsupport.service-now.com/ucr_portal/?id=kb_article&sys_id=8a264d791b5f0c149c0b844fdd4bcb34) and [MacOS](https://ucrsupport.service-now.com/ucr_portal/?id=kb_article&sys_id=8a264d791b5f0c149c0b844fdd4bcb34#2).

**Comment by advilm** [comment]
I'm also having this problem.
Here is my university's documentation for how it works on [Windows](https://ucrsupport.service-now.com/ucr_portal/?id=kb_article&sys_id=8a264d791b5f0c149c0b844fdd4bcb34#2) and [MacOS](https://ucrsupport.service-now.com/ucr_portal/?id=kb_article&sys_id=8a264d791b5f0c149c0b844fdd4bcb34#3).

My logs:
```2021-11-03 22:51:10.847 INFO  [78349] [gpclient::helper::parseGatewayResponse@52] The gateway response is:
var respStatus = "Challenge";
var respMsg = "Duo two-factor login for [redacted]  Enter a passcode or select one of the following options:   1. Duo Push to XXX-XXX-[redacted]  2. SMS passcodes to XXX-XXX-[redacted]  Passcode or option (1-2): ";
thisForm.inputStr.value = "5fd168d80056417f";


[1]    78349 segmentation fault (core dumped)  gpclient
```
It seems as if this would be hard to implement.

**Comment by yuezk** [comment]
@advilm Thanks for your documentation and it can help me to understand the workflow of the authentication. It’s the feature I want to implement in the past, but I didn’t have enough knowledge on it. Now I will implement it once I understood it. I might need your help to test it.

**Comment by advilm** [comment]
No problem. I'll help in any way I can. Thank you for your time :)

**Comment by advilm** [comment]
By the way, the place where we sign in then download the installer seems to give the same installer to everyone. (The link used to download is straight forward with no random character stuff) So it probably isn't generating them on a per user basis.

**Comment by yuezk** [comment]
Hi @advilm, I have an implementation in the `develop` branch. You can build it from the source code or install it from the snapshot version package published. Would you please try it with your environment? Thanks.

**Comment by advilm** [comment]
It gets to the prompt, but after I select 1 it says "Gateway login failed. Please check your credentials and try again."
I know my login details are correct because if I put an incorrect password I don't even get the 2fa prompt.

**Comment by yuezk** [comment]
@advilm Thanks for your feedback.

I want to know the workflow after you input the 2fa prompt on Mac or Windows with the official client. Does it just connect to the VPN without any other actions?

**Comment by advilm** [comment]
Yeah, after the verification it connects. No further actions required.

**Comment by yuezk** [comment]
> var respMsg = "Duo two-factor login for [redacted]  Enter a passcode or select one of the following options:   1. Duo Push to XXX-XXX-[redacted]  2. SMS passcodes to XXX-XXX-[redacted]  Passcode or option (1-2): ";

But I'm wondering how do you continue the authentication workflow if you input `1` or `2` as the answer to the 2fa prompt? Do you need to switch to the Duo or the SMS app to do some extra action?

**Comment by yuezk** [comment]
@advilm I found a video to demostrate the workflow (https://www.youtube.com/watch?v=vmChkVlnDms). After you input `1` or `2` in the 2fa prompt, it will display a Connecting UI and waiting for the user to approve on your phone. I think there should be some logic to loop the login request under the hood. But I don't know the request the official client is looping for.

For my client, please update the source code and recompile it, then you can input the Duo passcode directly instead of input the option `1` or `2`. I want to know if the passcode works.

**Comment by advilm** [comment]
Ah, yeah it waits for the approval from duo mobile. 

It seems to almost work with the passcode. Log: https://pastebin.com/raw/0DBc3uFR

**Comment by yuezk** [comment]
You could try https://github.com/yuezk/GlobalProtect-openconnect/issues/96#issuecomment-926511285 to see if it works.

**Comment by yuezk** [comment]
@advilm And would you please try to input `1` or `2` and provide the log file to me because I want to know what's happened after inputting the special `challenge` value. Thanks.

**Comment by advilm** [comment]
I'll try it when I get home in ~3 hours

**Comment by advilm** [comment]
The duo push actually worked when I tried it right now. Same error with the "Matching client config not found" though. I tried --os=win but no luck. I guess the 2FA works now and this is a separate issue? 
Log: https://pastebin.com/raw/zC4R1XhX

**Comment by yuezk** [comment]
Yes, `Matching client config not found` is an issue with openconnect. I will keep an eye on it. Thanks again for your prompt feedback on implementing the 2FA feature.

**Comment by advilm** [comment]
Alright, thanks for implementing this so quickly.
