### ISSUE TITLE
root need with gpclient cli?

### ISSUE THREAD

**Issue by userofryzen** [yuezk/GlobalProtect-openconnect#301]
I have installed the latest beta( 7 i think) and I have been doing tests. 
With CLI I have to run gpclient with sudo because unless it there will be errors that prevent me to use the VPN and exit the program without connect

With GUI there is no need to do nothing more(either sudo) than put the VPN url and after, choose, the server you wants.

It's the intended way to works or not?

I can't put right now the output of cli and gui clients but I will in a few days if you cant reproduce. 
With cli I have to put SUDO before using it. 

On another side, the problem with auth key for me is gone with beta 7, good job!
I wouldn't buy a license probably for many reasons(one of them is that I'll probably quit the job and the price that is monthly...) but I would try to help you as much as I can with those issues or bugs I ve found before quitting.

**Comment by yuezk** [comment]
> It's the intended way to works or not?

Yes. It is expected.

The reason why the GUI version doesn't need sudo is that I defined a polkit policy ([reference](https://www.freedesktop.org/software/polkit/docs/latest/polkit.8.html)) for it. You can find it at `/usr/share/polkit-1/actions/com.yuezk.gpgui.policy`.

The content is shown below:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE policyconfig PUBLIC "-//freedesktop//DTD PolicyKit Policy Configuration 1.0//EN" "http://www.freedesktop.org/standards/PolicyKit/1/policyconfig.dtd">
<policyconfig>
  <vendor>The GlobalProtect-openconnect Project</vendor>
  <vendor_url>https://github.com/yuezk/GlobalProtect-openconnect</vendor_url>
  <icon_name>gpgui</icon_name>
  <action id="com.yuezk.gpgui.service">
    <description>Run GPService as root</description>
    <message>Authentication is required to run the GPService as root</message>
    <defaults>
      <allow_any>auth_admin</allow_any>
      <allow_inactive>auth_admin</allow_inactive>
      <allow_active>yes</allow_active>
    </defaults>
    <annotate key="org.freedesktop.policykit.exec.path">/usr/bin/gpservice</annotate>
    <annotate key="org.freedesktop.policykit.exec.allow_gui">true</annotate>
  </action>
</policyconfig>
```

You can see `<allow_active>yes</allow_active>`, which means that it won't open the authenticator when running the application.
