### ISSUE TITLE
v2: SSL authentication doesn't work anymore

### ISSUE THREAD

**Issue by Xathviar** [yuezk/GlobalProtect-openconnect#302]
Hello, I've been using your tool for over a year, and it worked flawlessly up until recently when you recently the new version. 

Now I am unable to connect to connect via SSL...

I always get this error. 
![error](https://github.com/yuezk/GlobalProtect-openconnect/assets/41727154/9acf1933-5e9b-4d53-883d-676fc0343d8d)

It doesn't matter if I use my default browser or the built in browser... 

Please fix this

**Comment by yuezk** [comment]
@Xathviar which version are you using, similar issue has been fixed in 2.0.0-beta7

**Comment by Xathviar** [comment]
I think I used 2.0.0-beta5, that would explain it. I rolled back to version 1.4 and it's working again, and I don't plan on upgrading soon anymore
