### ISSUE TITLE
Incorrect browser detected in version 2.0.0-beta7

### ISSUE THREAD

**Issue by steve-jeffrey** [yuezk/GlobalProtect-openconnect#303]
I am getting an error when using version 2.0.0-beta7:

_Security key or biometric authenticator is not supported on this browser..._

 as shown in the attached image.

I suspect the problem is with version 2 (not the server I am trying to connect to) because:
- I can connect with version 1.4.9
- I received an email from Okta warning me "New sign-on detected for your Okta account", but the message indicated the browser was "Safari on Linux", but I don't use Safari (it is not installed on my system).

I am using Fedora 39.

![gpclient_2](https://github.com/yuezk/GlobalProtect-openconnect/assets/91641738/6dfdc13a-e07f-44c7-b313-54a863dec557)

**Comment by yuezk** [comment]
You could try to use the external browser to do the authentication, it can be configured in settings.

**Comment by steve-jeffrey** [comment]
Would that be added in `/etc/gpservice/gp.conf`? If so, do you have any docs with an example (I can't see one on the [configuration page](https://github.com/yuezk/GlobalProtect-openconnect/wiki/Configuration) on the wiki).

**Comment by yuezk** [comment]
`gp.conf` is for 1.x, which is no longer supported by 2.x. The 2.x release has its configuration page. You can find it via:

<img width="269" alt="image" src="https://github.com/yuezk/GlobalProtect-openconnect/assets/3297602/bb2affec-cb0c-485e-b280-366182518e2a">
<img width="501" alt="image" src="https://github.com/yuezk/GlobalProtect-openconnect/assets/3297602/434e91dc-cef8-453e-a4ef-34aabe18b895">
