### ISSUE TITLE
Connection failed: Failed to parse gateways

### ISSUE THREAD

**Issue by zsolt-donca** [yuezk/GlobalProtect-openconnect#304]
Using the beta release 2.0.0beta7 with the AUR package [globalprotect-openconnect-git](https://aur.archlinux.org/packages/globalprotect-openconnect-git), I get an error when connecting to the VPN:

![image](https://github.com/yuezk/GlobalProtect-openconnect/assets/6824167/aa1c2742-3000-486a-857a-8e5b69f0d74c)

Here are the logs: [gpclient.log](https://github.com/yuezk/GlobalProtect-openconnect/files/14052518/gpclient.log)

This error reminds me that my VPN server is not a "portal server", as [it was established ](https://github.com/yuezk/GlobalProtect-openconnect/issues/10#issuecomment-636419274) in a previous bug report.

**Comment by yuezk** [comment]
I remember the case, working on it.

**Comment by yuezk** [comment]
@zsolt-donca You can try extra the package and replace the `/usr/bin/gpgui` with the unpacked one, and see if it fixed.
[gpgui.tar.gz](https://github.com/yuezk/GlobalProtect-openconnect/files/14053203/gpgui.tar.gz)

**Comment by zsolt-donca** [comment]
It behaves weird. Instead of giving me an error, it enters this weird state of "connecting" for a while (maybe for a minute? not sure):

![image](https://github.com/yuezk/GlobalProtect-openconnect/assets/6824167/d6f566cd-3c12-4cc2-b1ce-2d690a1093f8)

And then it switches to "Connected". The old version never did this. Also, while in "connecting", `resolvectl` shows that the tunnel is up. Anyway, this is usable now. 👍

**Comment by yuezk** [comment]
@zsolt-donca I see, I know the problem and will improve the workflow.

**Comment by yuezk** [comment]
Fixed in 2.0.0-beta8. Now it will try to connect the portal as a gateway if it fails to fetch the portal config.
