### ISSUE TITLE
SUDO required, resolvconf modified requiring manual change after disconnect

### ISSUE THREAD

**Issue by Janmorgen** [yuezk/GlobalProtect-openconnect#307]
After quitting this version of global protect the nameservers from the VPN connection remain without any other nameserver backup and I need to reinstall resolvconf from apt as well as manually change /etc/resov.conf to return internet access

Command used: `sudo gpclient --ignore-tls-errors connect ....`

**Comment by yuezk** [comment]
@Janmorgen Which command do you use to disconnect the connection, `Ctrl+C`?
