### ISSUE TITLE
How to vpn-slice parameters in 2x?

### ISSUE THREAD

**Issue by EmptyVisual** [yuezk/GlobalProtect-openconnect#308]
Previously on 1x I had modified the config /etc/gpservice/gp.conf with my script parameters. How do you do this in the 2.x version?

I'd like to know how to parse script parameters via the gpclient 2.x CLI

My config was like the below:
```
[vpn.company.com]
openconnect-args=--script "vpn-slice -K {subdomain1,subdomain2,subdomain3}.domain.com"
```

**Comment by yuezk** [comment]
You could try to put the script content in a separate script file, say, `vpn-slice.sh`, make it executable, and then you can set its absolute path to the VPNC script field.

<img width="659" alt="image" src="https://github.com/yuezk/GlobalProtect-openconnect/assets/3297602/b2927929-9f27-4a02-bb47-a695e91ae564">

I will support this case in the next release so you don't have to create a separate file.

**Comment by EmptyVisual** [comment]
> You could try to put the script content in a separate script file, say, `vpn-slice.sh`, make it executable, and then you can set its absolute path to the VPNC script field.
> 
> <img alt="image" width="659" src="https://private-user-images.githubusercontent.com/3297602/301009961-b2927929-9f27-4a02-bb47-a695e91ae564.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY2NjY1MDcsIm5iZiI6MTcwNjY2NjIwNywicGF0aCI6Ii8zMjk3NjAyLzMwMTAwOTk2MS1iMjkyNzkyOS05ZjI3LTRhMDItYmI0Ny1hNjk1ZTkxYWU1NjQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEzMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMzFUMDE1NjQ3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OTA3MzNlYjk1ZjA0MjQyNjU1MWNkYThiYzA3NDUyODJjODc0NzhlYTdkZTVjZDVjZDgyMWFhYWMzMTAyYzFiMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ._afF2WnAiAAekbPgJikoQqsUcpsE2HzRmT20OWZPuls">
> I will support this case in the next release so you don't have to create a separate file.

Thank you. I’m running this on a headless server so I don’t have access to the UI. I have reverted to 1.x for now.

**Comment by yuranos** [comment]
I have a similar question. How do you pass --csd-wrapper now for example. Autoupdate to 2.X caused me a lot of stress today.
I will probably also have to revert for now.

**Comment by yuezk** [comment]
Both `vpnc-slice` and `csd-wrapper` can be configured in settings, or passed via the cli parameter, see `gpclient connect -h` for details.

![image](https://github.com/yuezk/GlobalProtect-openconnect/assets/3297602/23d3baea-f00a-4fb1-9d1f-b52103b12fee)
