### ISSUE TITLE
Install only CLI

### ISSUE THREAD

**Issue by piazzai** [yuezk/GlobalProtect-openconnect#310]
Hello! Thanks a lot for the software. I am interested in installing only the CLI tool. I am not interested in the GUI. Is there any way to install only the components I need for that (`gpclient`, `gpauth`, `gpservice`) and avoid installing `gpgui`?

You mentioned in the issue below that you plan to distribute `gpclient`, `gpauth`, and `gpservice` via the PPA, while `gpgui` will only be distributed via GitHub. That sounds good, but as far as I can see it is not the case yet. Both the releases here on GitHub and the version available from the PPA seem to install `gpgui` as part of the package.

https://github.com/yuezk/GlobalProtect-openconnect/issues/296#issuecomment-1905168220

**Comment by yuezk** [comment]
Hi @piazzai, I have done some spikes and found that building the Rust source project on PPA is challenging. With the functionality stable, The next step is to improve the delivery method described in #296.

**Comment by piazzai** [comment]
Thanks for the effort. As far as my needs go, I'd be perfectly happy with both versions (with and without GUI) being released via GitHub. Just as long as there is a way to avoid the cumbersome and proprietary GUI.

**Comment by yuezk** [comment]
Release from PPA/COPR/OBS won't include the GUI component.

It's hard to manage these release assets (with/without GUI component) via GitHub release, so it will includes the GUI components in the GitHub release assets.

You can also build the package from source code with a command (e.g. `make deb`), which won't include the GUI component by default.
