### ISSUE TITLE
v2.0.0 ignores MTU

### ISSUE THREAD

**Issue by orclex** [yuezk/GlobalProtect-openconnect#317]
Hi,

I set a special MTU size in /etc/gpservice/gp.conf:
`openconnect-args=--mtu=1356`
Unfortunately, _GlobalProtect-openconnect UI_ ignores this parameter and I cannot set it in the UI. 
Where can I set my MTU size?

**Comment by yuezk** [comment]
Hi @orclex, will add this option in the next release.

**Comment by yuezk** [comment]
Added in 2.1.0.
