### ISSUE TITLE
will not connect after upgrading client

### ISSUE THREAD

**Issue by GMCINTO** [yuezk/GlobalProtect-openconnect#320]
For some reason I can no longer connect after authenticating after I upgraded the client. Any help would be greatly appreciated. 

[logs.txt](https://github.com/yuezk/GlobalProtect-openconnect/files/14226615/logs.txt)

**Comment by GMCINTO** [comment]
I am not sure how to add a copy of my logs

**Comment by yuezk** [comment]
Hi @GMCINTO, thanks for you feedback.

Have you ever connected to your portal successfully?

I check the logs and found taht the errors logs indicate that the request to your gateway is timed out. It seems a problem with your network or the gateway server.

```
Gateway login failed: error sending request for url (https://129.82.0.6/ssl-vpn/login.esp): error trying to connect: tcp connect error: Connection timed out (os error 110)
```

**Comment by GMCINTO** [comment]
Thanks for your timely response. Yes before the update I had been using successfully for over a year. It seems like it authenticates and I get the confirmation after the 2FA goes through, sometimes twice and still just continues to attempt connection.

**Comment by GMCINTO** [comment]
Im sorry if I am not understanding the functionality correctly but it seems like my etc/resolv.conf isnt being updated correctly while trying to connect to the gateway.

**Comment by GMCINTO** [comment]
It seems like the issue is on my side as the VPN works flawlessly when i use from inside the network when testing. Thanks for your time looking into it
