### ISSUE TITLE
Secure Storage not ready

### ISSUE THREAD

**Issue by Zombie-Ryushu** [yuezk/GlobalProtect-openconnect#321]
I got an error from 2.0.0 that The Secure Storage is not ready. 
Couldn't access platform Secure storage.
SS error: result not returned from API

**Comment by yuezk** [comment]
Please try to install `gnome-keyring`, you might need to restart.

**Comment by yuezk** [comment]
BTW, what's your OS and desktop environment?

**Comment by Zombie-Ryushu** [comment]
Ubuntu 18.04.1

**Comment by Zombie-Ryushu** [comment]
nome-keyring is already the newest version (3.28.0.2-1ubuntu1.18.04.1).

**Comment by Zombie-Ryushu** [comment]
[2024-02-12T04:55:53Z INFO gpservice::cli] gpservice started: 2.0.0 (2024-02-05)
[2024-02-12T04:55:53Z INFO gpservice::ws_server] WS server listening on port: 40099
[2024-02-12T04:55:53Z INFO  gpgui::cli] gpgui started: 2.0.0 (2024-02-05)
[2024-02-12T04:55:53Z INFO  gpgui::app] Setting the custom openssl conf path
[2024-02-12T04:55:53Z INFO  gpgui::config::private_data] Generating config key
[2024-02-12T04:55:53Z WARN  gpgui::app::app_initializer] Can't read the config key from the keyring: Couldn't access platform secure storage: SS error: result not returned from SS API
[2024-02-12T04:55:55Z WARN  gpapi::utils::window] Failed to raise window: Failed to raise window: GlobalProtect
[2024-02-12T04:56:11Z INFO gpservice::cli] Shutdown signal received
[2024-02-12T04:56:11Z INFO gpservice::vpn_task] VPN task cancelled
[2024-02-12T04:56:11Z INFO gpservice::vpn_task] VPN is not connected, skip disconnect
[2024-02-12T04:56:11Z INFO gpservice::ws_server] VPN state watch task completed
[2024-02-12T04:56:11Z INFO gpservice::cli] gpservice stopped

**Comment by yuezk** [comment]
@Zombie-Ryushu I'm using Ubuntu 18.04 as well. What's the output of the command `ps aux | grep gnome-keyring`?

For me, it outputs:

```sh
kevin      2495  0.0  0.0 234148  6840 ?        Sl   00:08   0:00 /usr/bin/gnome-keyring-daemon --daemonize --login
```

**Comment by Zombie-Ryushu** [comment]
masterz   2166  0.0  0.2 281276  8164 ?        SLl  Feb11   0:00 /usr/bin/gnome-keyring-daemon --start --foreground --components=secrets
It may not be starting correctly, I launched it by hand.

**Comment by yuezk** [comment]
For me, `gnome-keyring-daemon` starts automatically after boot, I don't have to start it manually.

Has `gnome-keyring` already been installed before, or did you just install it after my suggestion?

**Comment by Zombie-Ryushu** [comment]
I installed it after you suggested it. But I started it at the command line over ssh

**Comment by yuezk** [comment]
Have you ever restarted after installing it?

**Comment by Zombie-Ryushu** [comment]
Yes, is there something I need to enable in systemctl? I'll restart it right now.

**Comment by yuezk** [comment]
It's not launched by systemctl. Just restart it and check whether the `gnome-keyring-daemon` is start.

**Comment by yuezk** [comment]
Are you launching the client using a remote desktop?

**Comment by yuezk** [comment]
Can you launch the password manager from `Activities` ->  Search `Password`, shown below

<img width="1152" alt="image" src="https://github.com/yuezk/GlobalProtect-openconnect/assets/3297602/9dc74a0c-a833-4610-864b-7863ef136572">

<img width="989" alt="image" src="https://github.com/yuezk/GlobalProtect-openconnect/assets/3297602/1cef975c-a366-42a3-a27e-10ca41fd17f2">

**Comment by Zombie-Ryushu** [comment]
I have KDE (Kubuntu sub Package.)

**Comment by Zombie-Ryushu** [comment]
What is the name of the management GUI?

**Comment by yuezk** [comment]
It's `seahorse`

**Comment by yuezk** [comment]
> I have KDE (Kubuntu sub Package.)

Weird. I have a VM installed Ubuntu 18.04 with KDE. The daemon starts automatically after restart.

**Comment by yuezk** [comment]
Just install `seahorse` and open it to see if it works.

<img width="662" alt="image" src="https://github.com/yuezk/GlobalProtect-openconnect/assets/3297602/822234b8-9cf7-4e8d-a1c2-be6cbe1b1f76">

**Comment by Zombie-Ryushu** [comment]
I created a Keyring, I installed Seahorse and got a keyring like yours. Does the keyring need to be called login? I'm, getting the same error.

**Comment by Zombie-Ryushu** [comment]
2587 ?        SLl    0:00 /usr/bin/gnome-keyring-daemon --start --foreground --components=secrets

**Comment by yuezk** [comment]
Does it still output the following error?

```
[2024-02-12T04:55:53Z WARN gpgui::app::app_initializer] Can't read the config key from the keyring: Couldn't access platform secure storage: SS error: result not returned from SS API
```

**Comment by Zombie-Ryushu** [comment]
2024-02-12T05:57:42Z INFO  gpgui::config::private_data] Generating config key
[2024-02-12T05:57:42Z WARN  gpgui::app::app_initializer] Can't read the config key from the keyring: Couldn't access platform secure storage: SS error: result not returned from SS API
[2024-02-12T05:57:43Z WARN  gpapi::utils::window] Failed to raise window: Failed to raise window: GlobalProtect
masterz@Tachikoma:~

**Comment by yuezk** [comment]
Can you install the `d-feet` and check the `org.freedesktop.secrets` dubs?

<img width="693" alt="image" src="https://github.com/yuezk/GlobalProtect-openconnect/assets/3297602/0f8dc68b-cbad-498e-ae97-a8db785b09bc">

**Comment by Zombie-Ryushu** [comment]
Yes.
![image](https://github.com/yuezk/GlobalProtect-openconnect/assets/7809674/ab084ceb-6f4d-458a-bccd-8464b6d7c384)

**Comment by yuezk** [comment]
All looks good. Let me try to see if there is a workaround for this.

**Comment by Zombie-Ryushu** [comment]
After much working around, this is what got it working:
I added gnome-keyring to my PAM Configuration,  and then created a keyring just called 'login' in all lower case. After that, Global Protect worked perfectly. No IP or DNS issues.

**Comment by yuezk** [comment]
@Zombie-Ryushu Great findings. Is there an online do for this?
> I added gnome-keyring to my PAM Configuration, and then created a keyring just called 'login' in all lower case.

And is #322 still a problem?

**Comment by Zombie-Ryushu** [comment]
Yes, this issue can be resolved. The OpenSuse issue is still an issue and is unrelated. 
Future packages of this for Ubuntu need to require gnome-keyring, and add the pam statements and create the 'login' keyring if doesn't exist.

**Comment by DropkickSteve** [comment]
> Can you launch the password manager from `Activities` -> Search `Password`, shown below
> 
> <img alt="image" width="1152" src="https://private-user-images.githubusercontent.com/3297602/303976463-9dc74a0c-a833-4610-864b-7863ef136572.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM5NDkxMjcsIm5iZiI6MTcxMzk0ODgyNywicGF0aCI6Ii8zMjk3NjAyLzMwMzk3NjQ2My05ZGM3NGEwYy1hODMzLTQ2MTAtODY0Yi03ODYzZWYxMzY1NzIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQyNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MjRUMDg1MzQ3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NDA0MThiNDU1ZDk1ZDk2NGE3OWQ2NTRiMzExZTUxNzc3OTlhY2M0NGZjZGU2ZGU2NzlmYjU3NTg4OGUxMDViYiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.38rEw36tTnqNSrO4vxq1N-E2lhnZHQxpmQBAbQ6J8wo"> <img alt="image" width="989" src="https://private-user-images.githubusercontent.com/3297602/303976505-1cef975c-a366-42a3-a27e-10ca41fd17f2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM5NDkxMjcsIm5iZiI6MTcxMzk0ODgyNywicGF0aCI6Ii8zMjk3NjAyLzMwMzk3NjUwNS0xY2VmOTc1Yy1hMzY2LTQyYTMtYTI3ZS0xMGNhNDFmZDE3ZjIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQyNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MjRUMDg1MzQ3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NmMxNWQ5OWQwOGE0ODBjNDJjYWUyMzY5ODU5MTEwYzBhM2E4OWVmYzE2YTI4OGZmMjQ1MTEyZjBjNWQ0YTZjNiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.JWCfv0ZPbdl-Nr_1EqK4bh6xTmFySqAWlVFVTQ5JBdA">

Did this entry get auto-generated in your Keyring? Because I get the Error of this thread when launching GlobalProtect, I was never prompted for credentials. I tried to manually add the keyring but can't figure out where the Username is entered, I only see Description & Password.
ps aux | grep gnome-keyring-daemon
steve     2262  0.0  0.0 355316  8136 ?        SLl  11:52   0:00 /usr/bin/gnome-keyring-daemon --daemonize --login
steve    27491ps aux | grep gnome-keyring
steve     2262  0.0  0.0 355316  8136 ?        SLl  11:52   0:00 /usr/bin/gnome-keyring-daemon --daemonize --login
steve    27499  0.0  0.0  14436  1008 pts/0    S+   17:11   0:00 grep --color=auto gnome-keyring
  0.0  0.0  14436  1064 pts/0    S+   17:11   0:00 grep --color=auto gnome-keyring-daemon

I also tried the PAM Configuration but didn't make it work. I'm on Ubuntu 18.04.6 LTS

**Comment by yuezk** [comment]
Hi @DropkickSteve, the keyring is automatically generated when you launch the client for the first time. But it will fail if the gnome-keyring is not available.

The solution is to configure the `gnome-keyring` with PAM configuration and add the `login` keyring, but you said it doesn't work for you. I want to help you with this, please open another issue for further discussion.

**Comment by yuezk** [comment]
Hi @DropkickSteve, the latest client fixed this using file-based storage when the keyring is unavailable. You can try to upgrade to 2.2.0 by following the instructions for Ubuntun 18.04

https://github.com/yuezk/GlobalProtect-openconnect/tree/main?tab=readme-ov-file#ubuntu-1804

**Comment by DropkickSteve** [comment]
> Hi @DropkickSteve, the latest client fixed this using file-based storage when the keyring is unavailable. You can try to upgrade to 2.2.0 by following the [instructions for Ubuntu 18.04](https://github.com/yuezk/GlobalProtect-openconnect/tree/main?tab=readme-ov-file#ubuntu-1804:~:text=the%20latest%20package.-,Ubuntu%2018.04,the%20Install%20from%20deb%20package%20section%20to%20install%20the%20latest%20package.,-Install%20from%20deb).

Thank you so much this resolved my problem!
