### ISSUE TITLE
Kinoite: Failed to update the GUI components (immutable system)

### ISSUE THREAD

**Issue by kem-a** [yuezk/GlobalProtect-openconnect#329]
**Describe the bug**

On app launch I get this error. Retry does not work, can not do anything.  *Error when helper tries to update **read-only system***

**Screenshots**
![Screenshot_20240301_213459](https://github.com/yuezk/GlobalProtect-openconnect/assets/33252703/b7f1bcb9-2453-4899-aa26-c3ce1a0162e0)

**Logs**
```
[2024-03-01T19:34:48Z INFO  gpservice::handlers] Installing GUI
[2024-03-01T19:34:48Z INFO  gpservice::handlers] Unpacking GUI archive
[2024-03-01T19:34:48Z WARN  gpservice::handlers] Failed to install GUI: Read-only file system (os error 30)
[2024-03-01T19:34:48Z WARN  gpgui_helper::updater] Install error: HTTP status server error (500 Internal Server Error) for url (http://127.0.0.1:33331/update-gui)
```
**Environment:**
 - OS: Fedora Kinoite
 - Desktop Environment: KDE Wayland

**Comment by yuezk** [comment]
Thanks for the feedback, I’ll fix this.

**Comment by yuezk** [comment]
@kem-a I'm new to Kinoite, how do you install this client on Kinoite?

**Comment by kem-a** [comment]
On immutable system you can layer packages that are not part of core system. There are two ways to do it, one by adding private repo and then install or directly layering rpm package. I did the latest:

```
rpm-ostree install <package.rpm>
```

The 3rd option would be running in container with toolbox, but that often causes issues coz of container limitations.

**Comment by yuezk** [comment]
Hi @kem-a, the latest RPM package on the release page fixed the problem by including the GUI component. Tested in Kinoite in VM.
