### ISSUE TITLE
Allow ignoring ERR_CERT_INVALID after SAML redirect login

### ISSUE THREAD

**Issue by ghost** [yuezk/GlobalProtect-openconnect#33]
I am able to successfully open the login screen and enter my credentials. Afterward, however, I encounter this screen:

![Screenshot from 2020-09-30 19-03-36](https://user-images.githubusercontent.com/1628229/94680989-40406e80-0355-11eb-84e0-f2e4e7c208d1.png)

I would file a PR myself but I'm unfortunately not well-versed in C++. I found this reference that might be helpful though: https://stackoverflow.com/questions/58875159/how-to-ignore-ssl-certificate-errors-with-qwebengineview

**Comment by zakiharis** [comment]
+1

```
This site can’t be reachedThe webpage at https://x.x.x.x/SAML20/SP/ACS might be temporarily down or it may have moved permanently to a new web address.
ERR_CERT_AUTHORITY_INVALID
```

**Comment by Brenopms** [comment]
I'm having the same issue. Is there any workaround for now?

The official GUI Application for GlobalProtect crashes every time I complete the MFA.

**Comment by sethomas** [comment]
To get around this, I ended up exporting the insecure certificate, and adding it via `certutil`.

**Comment by syk0saje** [comment]
> To get around this, I ended up exporting the insecure certificate, and adding it via `certutil`.

I'd like to try this myself. @sethomas from where and how did you export the certificate?

**Comment by NgoHuy** [comment]
+1 
I have same problem with self certificate.

**Comment by jhonatanTeixeira** [comment]
> To get around this, I ended up exporting the insecure certificate, and adding it via `certutil`.

can you please explain me this workaround

**Comment by kkuhle** [comment]
Same issue here.  I wasn't able to get this working, but did get the other method from https://github.com/dlenski/gp-saml-gui to work.  It's not as friendly to figure out though.

**Comment by yuezk** [comment]
Already fixed.
