### ISSUE TITLE
Multiple problems activating v2 GUI

### ISSUE THREAD

**Issue by mjpelmear** [yuezk/GlobalProtect-openconnect#330]
1) [In some browsers] I tried to activate the v2 GUI through https://yuezk.lemonsqueezy.com/, however I was never brought to PayPal to confirm the transaction after clicking the yellow "PayPal" button in the payment screen.

This happens for me with both Brave 1.63.162 (chromium 122.0.6261.69) and Chrome 122.0.6261.94.
It works in Firefox 123.0.

2) In Firefox, after completing the payment through PayPal, I am returned to yuezk.lemonsqueezy.com but the operation never completes:

![image](https://github.com/yuezk/GlobalProtect-openconnect/assets/484922/a328924b-bb47-4764-a5ed-c4dde0fcb72f)

To be clear, I did receive a license key via email, but this process was far from smooth.

**Comment by yuezk** [comment]
Thanks for the feedback! I will report this to Lemon Squeezy.
