### ISSUE TITLE
License violation?

### ISSUE THREAD

**Issue by CarloRamponi** [yuezk/GlobalProtect-openconnect#331]
Dear @yuezk, you now pulled the GUI code from this repository to distribute it in a paid model.
However, since the GUI was previously distributed under the GPLv3 license, this requires that you publish all the modifications that you do to it if you then distribute the program (which you do).
I myself contributed to the code of the GUI, so this impacts me directly.
Isn't this a clear violation of the GPL license?

**Comment by yuezk** [comment]
Hi @CarloRamponi Thanks for your contribution for this project. Code under this repo is totally complaint with GPL v3 and fully open-sourced. The GUI component is now rewritten with Tauri and Rust, in another private repo and only contains my contribution. More details can be found in https://github.com/yuezk/GlobalProtect-openconnect/issues/296#issuecomment-1905168220
