### ISSUE TITLE
The `tun0` device is created but its state is DOWN

### ISSUE THREAD

**Issue by yuezk** [yuezk/GlobalProtect-openconnect#336]
When I connect via `sudo -E gpclient connect` then a `tun0` device is created but its state is `DOWN` and I don't have access to the IPs of the network I am trying to connect to. Here is what I believe to be the relevant part of the error log.

> [2024-02-19T10:04:45Z INFO  openconnect::ffi] POST https://ras-int.cf.ac.uk/ssl-vpn/hipreportcheck.esp
[2024-02-19T10:04:45Z WARN  openconnect::ffi] WARNING: Server asked us to submit HIP report with md5sum 71b3f5351c2388741513b6942fe06701.
        VPN connectivity may be disabled or limited without HIP report submission.
        You need to provide a --csd-wrapper argument with the HIP report submission script.
[2024-02-19T10:04:45Z INFO  openconnect::ffi] ESP session established with server
[2024-02-19T10:04:45Z INFO  openconnect::ffi] ESP tunnel connected; exiting HTTPS mainloop.
[2024-02-19T10:04:46Z INFO  openconnect::ffi] Using vhost-net for tun acceleration, ring size 32
[2024-02-19T10:04:46Z INFO  openconnect::vpn] Connected to VPN, pipe_fd: 11
[2024-02-19T10:04:46Z INFO  gpclient::connect] Wrote PID 6234 to /var/run/gpclient.lock

_Originally posted by @gonneman in https://github.com/yuezk/GlobalProtect-openconnect/issues/316#issuecomment-1952150297_

**Comment by yuezk** [comment]
The WARNING can be mitigated by passing the `--csd-wrapper` parameter to the `gpclient connect` command.

You can find the `--csd-wrapper` from one of the following places.

```
"/usr/lib/x86_64-linux-gnu/openconnect/hipreport.sh",
"/usr/lib/aarch64-linux-gnu/openconnect/hipreport.sh",
"/usr/lib/openconnect/hipreport.sh",
"/usr/libexec/openconnect/hipreport.sh",
```

**Comment by gonneman** [comment]
Indeed `sudo -E gpclient connect [server] --csd-wrapper=/usr/lib/openconnect/hipreport.sh` removes the HIP report warning. Sadly, the `tun0` device is still down though.

Does this mean that the VPN connection is being created (i.e. the `tun0` device), but nothing is being routed through it? Do I need to manually set `tun0` to up and then rout my network connections through it?

Is this an issue of the VPN server not providing gpclient with the necessary information or is this a bug? If it is a bug, are there any logs I can provide that would be helpful?

**Comment by yuezk** [comment]
@gonneman I'm able to reproduce this problem in openSUSE 15.5. The reason is that the client doesn't detect the vpnc_script. You could try this: `sudo gpclient connect <portal> --script /etc/openconnect/vpnc-script`.

I'll fix this in the next release.

**Comment by 55octet** [comment]
Thank you for looking at this.  I ran into the the problem on openSUSE 15.5.  I did see something in the logs about the vpnc-script.

I'll give this a try when I have a chance to boot to openSUSE 15.5.
