### ISSUE TITLE
Not Connected, even after several tries of putting in the right username and password

### ISSUE THREAD

**Issue by rsmath** [yuezk/GlobalProtect-openconnect#340]
I have been using this software for almost a year. It automatically updated last week and now my vpn is not connecting anymore.

**Comment by yuezk** [comment]
Hi @rsmath sorry for the inconvenience.

I fixed a similar issue in [v2.1.2](https://github.com/yuezk/GlobalProtect-openconnect/releases/tag/v2.1.2) 5 days ago. Could you upgrade it to 2.1.2 if you use an older version?

Could you please upload the logs (`~/.local/share/gpclient/gpclient.log`) if the issue still exists, so I can investigate it further? 

Thanks.

**Comment by rsmath** [comment]
It started working a couple of hours ago somehow :) thank you for your response.
