### ISSUE TITLE
GlobalProtect makes me sign in twice

### ISSUE THREAD

**Issue by rsmath** [yuezk/GlobalProtect-openconnect#342]
I am using the app for logging into a university vpn. It used to only make me log into the vpn portal once, but after the update it consistently asks me to log into it twice. Is this by design?

**Comment by yuezk** [comment]
@rsmath, are you using the CLI version? It seems the same as https://github.com/yuezk/GlobalProtect-openconnect/issues/318#issuecomment-2032260240. I plan to add an option to the CLI to deal with this problem.

**Comment by rsmath** [comment]
No, sorry. I am using the GUI.

**Comment by yuezk** [comment]
@rsmath Can you upload the log file from `~ /.local/share/gpclient/gpclient.log`?

**Comment by rsmath** [comment]
[gpclient.log](https://github.com/yuezk/GlobalProtect-openconnect/files/14887657/gpclient.log)

**Comment by yuezk** [comment]
Hi @rsmath it seems like that there is an TLS error when connecting to the gateway after the first authentication. Please set it to ignore the TLS errors and see if it works.

![Screenshot_20240406_183655](https://github.com/yuezk/GlobalProtect-openconnect/assets/3297602/a87237eb-395f-4a8f-a313-bdfda0a96bbc)

**Comment by rsmath** [comment]
It still took two tries. Here's the latest log file.
[gpclient.log](https://github.com/yuezk/GlobalProtect-openconnect/files/14895140/gpclient.log)

**Comment by yuezk** [comment]
Hi @rsmath, it should be fixed in 2.1.3. I added an option to the GUI to support connecting the server as a gateway, click the icon, and change it to the Gateway Server.

<img width="270" alt="image" src="https://github.com/yuezk/GlobalProtect-openconnect/assets/3297602/5de0e761-50b0-40be-99c1-3f9fe6bc5120">

Closing it for now and reopen it if it is not fixed.

**Comment by rsmath** [comment]
It's still not fixed :(

**Comment by yuezk** [comment]
Reopend. Can I have your log file?

**Comment by rsmath** [comment]
Thank you.
[gpclient.log](https://github.com/yuezk/GlobalProtect-openconnect/files/14900934/gpclient.log)

**Comment by yuezk** [comment]
Hi @rsmath just checked the logs, looks like you didn’t set the gateway server. Please try to click the globe icon, and select the `Gateway Server`. Then connect it again.

**Comment by rsmath** [comment]
I will try that, thank you for the quick response and your help.

**Comment by rsmath** [comment]
It seems to work now, thank you :)
