### ISSUE TITLE
Phone pin pop up in ubuntu

### ISSUE THREAD

**Issue by pedromnchunks35** [yuezk/GlobalProtect-openconnect#343]
Hello, if i am not mistaken you are also the maintainer of the AUR package of the Global Protect.
What happens is the following, recently i moved from linux manjaro for ubuntu because of some startup problems. Now that i am currently using ubuntu i tryied to install the Global Protect on ubuntu.
In ubuntu what i notice is a more recent version compared to the arch linux version but it does not function quite like the arch linux version.
In order to connect via VPN to server that i am working on i need to put the host along with the credentials which is the normal step. In the last version (arch linux version) it would request me to put a pin that i receive on my phone via message but in the ubuntu version it fails to go to that menu. The following images represent firstly the manjaro version and secondly the ubuntu version.
![image](https://github.com/yuezk/GlobalProtect-openconnect/assets/48800536/e35f0da9-c752-4c5c-8c67-f549f9bd1d40)
164229
![image](https://github.com/yuezk/GlobalProtect-openconnect/assets/48800536/552b9f2c-a5a6-47cc-8aba-976041100865)

**Comment by yuezk** [comment]
@pedromnchunks35 I would like to support this. Can you upload the log file from `~ /.local/share/gpclient/gpclient.log`?

**Comment by pedromnchunks35** [comment]
I will send it when I can, I will be away from office for a couple of days. If it helps I would like to tell you that the logs that I saw is the receivable of what appears to be a html form but I will send it to you as soon as I can!!

**Comment by yuezk** [comment]
Hi @pedromnchunks35, MFA is supported in 2.1.4, please upgrade and see if it works for you. Thanks.

<img width="284" alt="image" src="https://github.com/yuezk/GlobalProtect-openconnect/assets/3297602/0a7e0714-a05a-4ec2-ac5b-c820b23ac0e1">
