### ISSUE TITLE
Save the credentials after first login on CLI agent

### ISSUE THREAD

**Issue by aritroCoder** [yuezk/GlobalProtect-openconnect#355]
Although it saves the credentials for the GUI version, the CLI lacks the saved credentials capability which is an hinderence and should be fixed.

**Comment by yuezk** [comment]
In 2.3.7, you can save the credentials get from `gpauth <portal>` to a file and pipe it to the `gpclient` with `sudo gpclient connect <portal> --cookie-on-stdin`.
