### ISSUE TITLE
/tmp/gpauth.html is removed before user's browser can open it

### ISSUE THREAD

**Issue by thor0215** [yuezk/GlobalProtect-openconnect#366]
**Describe the bug**
When running 'sudo -E gpclient connect --default-browser vpn-global.domain.com' the user's browser cannot open the /tmp/gpauth.html file because it no longer exists

**Expected behavior**
gpauth.html is being removed too soon

**Environment:**
 - OS: Opensuse Tumbleweed
 - Desktop Environment: KDE 6.0.4
 - Is remote SSH? No

**Additional context**
I created an inotifywait script to cp the gpauth.html file when it's modified and the contents look as expected, it's just being removed to quickly

**Comment by sorind-broadsign** [comment]
Any news on this issue ?

**Comment by yuezk** [comment]
Will fix it in the next release.

**Comment by yuezk** [comment]
Released in 2.3.2
