### ISSUE TITLE
OpenSUSE build service is still building/releasing 2.2.1 

### ISSUE THREAD

**Issue by ldriscoll** [yuezk/GlobalProtect-openconnect#373]
**Describe the bug**
I'm running on OpenSUSE Tumbleweed, and the latest updates are for 2.2.1 instead of 2.3.1

**Expected behavior**
Should be updating to 2.3.1

**Screenshots**
N/A

**Logs**
N/A

**Environment:**
 - OS: OpenSUSE Tumbleweed
 - Desktop Environment: KDE Plasma
 - Output of `ps aux | grep 'gnome-keyring\|kwalletd5' | grep -v grep`: [Required for secure store error]
 - Is remote SSH? No

**Additional context**

**Comment by yuezk** [comment]
Thanks for your reminder it has been updated to 2.3.1 now.
