### ISSUE TITLE
provide password from file or environment variable

### ISSUE THREAD

**Issue by alperyilmaz** [yuezk/GlobalProtect-openconnect#381]
**Describe the bug**
I'm using gpclient cli within docker container. For more automated use, I need to provide the password from file (or environment variable) but I cannot do that right now, I need to enter the password in interactive TTY. When I searched previous issues, found one about credentials being saved but couldn't figure out how to use it to solve my issue.

**Expected behavior**
Using a commandline argument to provide a filename or environment variable which contains password so that gpclient can be more scriptable without user intervention 

**Environment:**
 - OS: Ubuntu 22.04 (within docker)
 - Desktop Environment: none
 - Is remote SSH? Yes

**Comment by yuezk** [comment]
Currently, the username can be passed via the `-u` option, while the password must be from the user input. I will evaluate if it is possible to read the password from the std in. So usage like `echo "$PASSWORD" | gpclient connect <portal> -u user` could work.

**Comment by yuezk** [comment]
@alperyilmaz In 2.3.4, you can pass the password from stdin, via `echo "$PASSWORD" | gpclient connect <portal> -u <user> --passwd-on-stdin`

**Comment by yuezk** [comment]
Closing it for now, feel free to reopen if it still has the issue.

**Comment by alperyilmaz** [comment]
thanks.. it works!..
