### ISSUE TITLE
How to connect using gclient CLI

### ISSUE THREAD

**Issue by gserci** [yuezk/GlobalProtect-openconnect#388]
Hi,
I've tried connecting on VPN using GUI version of gpclient and it works correctly, but I don't understand how to connect using CLI version.
My data are:
portal: vpn.example.it
gateway: vpn6.example.it
group: GPG-IPSEC-RTSC
shared key: VPNExample!

How can I put these inputs on the terminal?

Thank you.

**Comment by yuezk** [comment]
Try `sudo gpclient connect <portal>` and see what happens.

**Comment by gserci** [comment]
> Try `sudo gpclient connect <portal>` and see what happens.

Thank you, it works! ☺️
