### ISSUE TITLE
ubuntu 20.04 lts

### ISSUE THREAD

**Issue by BFriedmanWorx** [yuezk/GlobalProtect-openconnect#39]
sudo apt install qt5-default libqt5websockets5-dev qtwebengine5-dev

That fails to install on ubuntu 20.04 LTS.  In fact, I'm having trouble getting _any_ of the qt5 packages to install.  Not sure what I'm doing wrong. 

![image](https://user-images.githubusercontent.com/63876862/102394616-3f53cc00-3f97-11eb-88ac-6e75dcb082cb.png)

**Comment by mikedld** [comment]
Your issue is with your particular system, not this software; you'll probably get more help talking to people in Ubuntu-specific forum or IRC channel to resolve it. Just confirmed that dependencies install fine and everything builds in Ubuntu 20.04 using the following Dockerfile:

```dockerfile
FROM ubuntu:20.04

RUN set -ex; \
    apt update; \
    DEBIAN_FRONTEND=noninteractive apt install --no-install-recommends -y \
        qt5-default \
        libqt5websockets5-dev \
        qtwebengine5-dev \
        git \
        ca-certificates \
        build-essential; \
    git clone --recurse-submodules https://github.com/yuezk/GlobalProtect-openconnect /src; \
    mkdir /src/_build; \
    cd /src/_build; \
    qmake ..; \
    make -j$(nproc) install
```

**Comment by BFriedmanWorx** [comment]
thank you.
