### ISSUE TITLE
Add support for FIDO key authentication with pin in SAML web page

### ISSUE THREAD

**Issue by Trevelian** [yuezk/GlobalProtect-openconnect#392]
**Describe the bug**
Add support for FIDO key authentication with pin in SAML web page, like Microsoft Office365.
Actually no popup windows are opened so we cant enter the pin of the key and the office365 authentication fail.
![image](https://github.com/user-attachments/assets/9b27150d-6e4c-49f9-9626-7ad90ff12abf)

**Expected behavior**
A popup windows should appear to enter the pin of the FIDO key like in chrome :  
![image](https://github.com/user-attachments/assets/0dbfe5dc-7daf-4d70-b1d8-72ba243fc5fa)

**Environment:**
 - OS: Archlinux
 - Desktop Environment: lxqt
 - Is remote SSH? No

**Comment by yuezk** [comment]
Hi @Trevelian, looks like you are not using the default browser authentication. You can use it by enabling it in the `Authentication` settings of the GUI.

**Comment by Trevelian** [comment]
I just see that in the Archlinux repository "globalprotect-openconnect" is still in the 1.4.9 version. I think this feature is not there in this old release. So if its using the default browser in the new release, its great !

**Comment by yuezk** [comment]
You can install 2.x from the AUR package [globalprotect-openconnect-git](https://aur.archlinux.org/packages/globalprotect-openconnect-git)

Both the CLI and GUI versions (no longer free) support the default browser.

Use the `sudo -E gpclient connect --default-browser <portal>` command for the CLI version.

**Comment by Trevelian** [comment]
Thanks for your help, and for this nice software !
