### ISSUE TITLE
gpclient process does not end

### ISSUE THREAD

**Issue by gurucubano** [yuezk/GlobalProtect-openconnect#400]
I run version 1.4.9 of gpclient on my FreeBSD laptop and my Purism L5 cellphone (Debian based). Both installation work fine. The gpclient on FreeBSD is started from a KDE5-plasma desktop icon, or by shell just running `/usr/local/bin/gpclient`. In both cases the GUI comes up fine and I can do the VPN connection.

On `Disconnect` button the VPN connection goes down. The GUI keeps running. I can terminate the GUI with the Window-manager `x`-symbol. But, the `gpclient` process keeps running and must be stopped with `killall gpclient`. 

Is this intention, i.e. feature, or a bug?

**Comment by yuezk** [comment]
Hi @gurucubano, have you tried to `quit` it from the system tray icon?

**Comment by gurucubano** [comment]
There is no `quit` in the system tray icon, only `Cerrar` (my desktop is in Spanish), see attached picture. When I click this, the GUI closes, but these processes stay:
```
$ ps ax | grep gp
1582  -  I     0:00,07 /usr/local/bin/gpservice
1576 v0  S     0:04,09 /usr/local/bin/gpclient
```
![Cerrar](https://github.com/user-attachments/assets/257d6a84-1e2f-4a3b-a22d-d1c29c57b6ba)

**Comment by yuezk** [comment]
Sorry, I may not provide sufficient help with this. As I'm not familiar with FreeBSD and have limited experience with the QT framework. That's why I refactored it using the Tauri framework.

**Comment by gurucubano** [comment]
El día miércoles, agosto 14, 2024 a las 08:01:30 -0700, Kevin Yue escribió:

> Sorry, I may not provide sufficient help with this. As I'm not familiar with FreeBSD and have limited experience with the QT framework. That's why I refactored it using the Tauri framework.
> 

The maintainer of the port in FreeBSD replied to me, that this is a
feature and not a bug:


That's how it works.  From my lecture notes for a course I taught using VPN:

        <note>
        GlobalProtect OpenConnect <glossterm>daemonizes</glossterm> 
        a program called <command>gpservice</command> to maintain the 
        connection to the VPN server.  As a daemon, 
        <command>gpservice</command> continues to run after the GUI 
        <command>gpclient</command> is terminated. 
        If left running for a long time, 
        the connection can go <emphasis>stale</emphasis>, resulting in 
        failed connections.  You may need to manually terminate the 
        daemon by running <command>pkill gpservice</command> as root, 
        so that a new VPN connection is established next time you run 
        <command>gpclient</command>. 
        </note>

-- 
Matthias Apitz, ✉ ***@***.***, http://www.unixarea.de/ +49-176-38902045
Public GnuPG key: http://www.unixarea.de/key.pub

**Comment by yuezk** [comment]
Thanks for the update, I’m closing this.
