### ISSUE TITLE
Install error: Unable to locate package globalprotect-openconnect_2.3.4-1_amd64.deb

### ISSUE THREAD

**Issue by WillieMaddox** [yuezk/GlobalProtect-openconnect#401]
**Describe the bug**

After installing `libjavascriptcoregtk-4.0-18_2.43.3-1_amd64.deb` and `libwebkit2gtk-4.0-37_2.43.3-1_amd64.deb` as per the Ubuntu 24.04 instructions, I get stuck on the last step:
```
$ sudo apt install --fix-broken globalprotect-openconnect_*.deb
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package globalprotect-openconnect_2.3.4-1_amd64.deb
```
Please advise, Thanks.

**Environment**
 - OS: Ubuntu 24.04
 - Desktop Environment:  GNOME
 - Output of `ps aux | grep 'gnome-keyring\|kwalletd5' | grep -v grep`: 
   - maddoxw     2922  0.0  0.0 316744  9600 ?        SLsl Jul28   0:00 /usr/bin/gnome-keyring-daemon --foreground --components=pkcs11,secrets --control-directory=/run/user/1000/keyring
 - Is remote SSH? No

**Comment by yuezk** [comment]
Hi @WillieMaddox what about specifying the absolute path of `globalprotect-openconnect_2.3.4-1_amd64.deb`?

**Comment by WillieMaddox** [comment]
> Hi @WillieMaddox what about specifying the absolute path of `globalprotect-openconnect_2.3.4-1_amd64.deb`?

```
$ sudo apt install --fix-broken globalprotect-openconnect_2.3.4-1_amd64.deb
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package globalprotect-openconnect_2.3.4-1_amd64.deb
```
Same.

**Comment by yuezk** [comment]
How about `sudo apt install --fix-broken ./globalprotect-openconnect_2.3.4-1_amd64.deb`?

**Comment by WillieMaddox** [comment]
OMG! Of course that worked.  Such a noob mistake.  

Thank you and sorry for wasting your time.
