### ISSUE TITLE
vpnc-script reports error copying /etc/resolv.conf to /var/run/vpnc, causing DNS failures

### ISSUE THREAD

**Issue by dhsmith1001** [yuezk/GlobalProtect-openconnect#408]
**Describe the bug**
When I am connected to the VPN portal, I can't reach internal servers due to DNS errors. When I cat /etc/resolv.conf, I don't see the name servers relevant to my organization, only the generic ones I have when not connected to VPN. I'm using the GUI to connect.

When I view the log, I see this error:
/usr/share/vpnc-scripts/vpnc-script: 600: cannot open /var/run/vpnc/resolv.conf-backup.99098: No such file
[2024-08-08T15:16:39Z WARN  openconnect::ffi] Script '/usr/share/vpnc-scripts/vpnc-script' returned error 2

At line 600 in my vpnc-script, it's trying to copy /etc/resolv.conf:
exec 6< "$RESOLV_CONF_BACKUP"
while read LINE <&6 ; do
	case "$LINE" in
		# omit; we will overwrite these
		nameserver*) ;;
		# extract listed domains and prepend to list
		domain* | search*) DOMAINS="${LINE#* } $DOMAINS" ;;
		# retain other lines
		*) NEW_RESOLVCONF="$NEW_RESOLVCONF
$LINE" ;;
	esac
done
exec 6<&-

I tried granting rwx to all on /var/run/vpnc:
chmod 777 /var/run/vpnc

ls -lad /var/run/vpnc:
drwxrwxrwx 2 root root 80 Aug  8 11:18 /var/run/vpnc/
but this did not help.

**Expected behavior**
I expect the vpnc-script to work and copy /etc/resolv.conf, then write a temporary one with the name servers from my organization

**Screenshots**
No error is shown in the GUI
![GlobalProtect](https://github.com/user-attachments/assets/82345551-1fdf-453f-8ade-5c330c0828ee)

**Logs**
[gpclient.log](https://github.com/user-attachments/files/16550424/gpclient.log)

**Environment:**
 - OS: Ubuntu 23.10
 - Desktop Environment: KDE
 - Output of `ps aux | grep 'gnome-keyring\|kwalletd5' | grep -v grep`: [Required for secure store error]
donald      3066  0.0  0.0 316604  8448 ?        SLsl Aug07   0:00 /usr/bin/gnome-keyring-daemon --foreground --components=pkcs11,secrets --control-directory=/run/user/1000/keyring
donald      3096  0.0  0.1 1328316 33540 ?       Sl   Aug07   0:02 /usr/bin/kwalletd5 --pam-login 13 14

 - Is remote SSH? No

**Additional context**
Settings:
![GlobalProtect2](https://github.com/user-attachments/assets/f29247fe-22b3-4917-be2f-90499e9ad0a0)

**Comment by yuezk** [comment]
Hi @dhsmith1001 the error is raised by `/usr/share/vpnc-scripts/vpnc-script`. You can try re-installing the `openconnect` package to see if it works.
