### ISSUE TITLE
Can not install on RHEL 9

### ISSUE THREAD

**Issue by xoroz** [yuezk/GlobalProtect-openconnect#415]
**Describe the bug**
Unable to install rpm on RHEL 9.4

**Expected behavior**
Install success

**Logs**
# rpm -i globalprotect-openconnect-2.3.7-1.x86_64.rpm 
error: Failed dependencies:
	(libayatana-appindicator or libappindicator-gtk3) is needed by globalprotect-openconnect-2.3.7-1.x86_64
	libc.so.6(GLIBC_2.38)(64bit) is needed by globalprotect-openconnect-2.3.7-1.x86_64

**Additional context**
I was able to get over libappindicator-gtk3, but not glibc2.38 issue even know file is there, but version is 2.34

glibc-2.34-100.el9_4.2.x86_64 : The GNU libc libraries
Repo        : rhel-9-for-x86_64-baseos-rpms
Matched from:
Filename    : /lib64/libc.so.6

I believe this is easy to reproduce also on CENTOS 9.

any advice ?

**Comment by yuezk** [comment]
Hi @xoroz you may need to follow the steps here to install it because the rpm package is built on a relatively newer OS.

https://github.com/yuezk/GlobalProtect-openconnect#other-distributions

**Comment by QuinnBast** [comment]
That worked but...

```
$ sudo make install
===> Installing...
install -Dm755 artifacts/usr/bin/gpclient /usr/bin/gpclient
install -Dm755 artifacts/usr/bin/gpservice /usr/bin/gpservice
install -Dm755 artifacts/usr/bin/gpauth /usr/bin/gpauth
install -Dm755 artifacts/usr/bin/gpgui-helper /usr/bin/gpgui-helper
if [ -f artifacts/usr/bin/gpgui ]; then \
	install -Dm755 artifacts/usr/bin/gpgui /usr/bin/gpgui; \
fi
install -Dm644 artifacts/usr/share/applications/gpgui.desktop /usr/share/applications/gpgui.desktop
install -Dm644 artifacts/usr/share/icons/hicolor/scalable/apps/gpgui.svg /usr/share/icons/hicolor/scalable/apps/gpgui.svg
install -Dm644 artifacts/usr/share/icons/hicolor/32x32/apps/gpgui.png /usr/share/icons/hicolor/32x32/apps/gpgui.png
install -Dm644 artifacts/usr/share/icons/hicolor/128x128/apps/gpgui.png /usr/share/icons/hicolor/128x128/apps/gpgui.png
install -Dm644 artifacts/usr/share/icons/hicolor/256x256@2/apps/gpgui.png /usr/share/icons/hicolor/256x256@2/apps/gpgui.png
install -Dm644 artifacts/usr/share/polkit-1/actions/com.yuezk.gpgui.policy /usr/share/polkit-1/actions/com.yuezk.gpgui.policy
```

None of the commands execute because they are for the wrong CPU architecture

```
$ gpclient
bash: /usr/bin/gpclient: cannot execute binary file: Exec format error
$ gpclient launch-gui
bash: /usr/bin/gpclient: cannot execute binary file: Exec format error
```

**Comment by yuezk** [comment]
Thanks, I'm closing this.

**Comment by xoroz** [comment]
sorry to reopen this issue, but I am still strugling to have it running under rhel 9 with only rhel repos basicaly I am stuck because

- gpgui after 2.3 is webkit2gtk4.1 and that is not avail or easy to install without only rhel 9 repos 
- gpgui started: 2.3.11 (2025-01-21) - then gpservice can not find libopenconnect.so.5
/usr/bin/gpclient: error while loading shared libraries: libopenconnect.so.5: cannot open shared object file: No such file or directory
Failed to launch the GUI, exit status: ExitStatus(unix_wait_status(32512))

Does anyone have this running on rocky linux 9 or rhel 9 with gpgui ? 

Event the original GlobalProtect version I get many errors like
PanGPA[119110]: segfault at 0 ip 00007fae0b75c7f5 sp 00007ffec6dba758 error 4 in libc.so.6[7fae0b629000+175000] likely on CPU 3 (core 3, socket 

please help me out 
I see other users with same issue at
[rhel9 support](https://github.com/yuezk/GlobalProtect-openconnect/issues/527)

**Comment by yuezk** [comment]
Hi @xoroz, i will prioritize the rhe9 support. Let's track it in https://github.com/yuezk/GlobalProtect-openconnect/issues/527
