### ISSUE TITLE
After connect UI still showing as connecting status

### ISSUE THREAD

**Issue by marcosjrvrael** [yuezk/GlobalProtect-openconnect#43]
Hi I've installed the app recent in PoP Os 20.04 following the steps to build the debian package and got a small issue even after a successfull connection the GUI keeps showing the connecting message without any return.
Attached images of the issue.;
![Screenshot from 2021-01-08 15-32-24](https://user-images.githubusercontent.com/39653959/104051902-aa27aa00-51c7-11eb-9b9d-bb7413fc4733.png)
![Screenshot from 2021-01-08 15-31-59](https://user-images.githubusercontent.com/39653959/104051911-aeec5e00-51c7-11eb-8b0a-9b308e1701a7.png)

**Comment by danys94** [comment]
Same here, VPN works, but it shows still as Connecting.. I have noticed it happens to me only on some systems. For example it doesn't happen on Linux Mint 20.X, but its happening on Linux Manjaro (arch-based system)

**Comment by BMartinos** [comment]
Happening to me as well. Running Ubuntu 20.04 LTS. Any possible fix for this soon?

**Comment by yuezk** [comment]
Sorry about this. It works for me, and I didn't get the time to investigate it.

I really appropriate your help if you guys familiar with C++.

The related code could be
https://github.com/yuezk/GlobalProtect-openconnect/blob/ccaf93ec3123e40bbcf48b575c2712189291b72b/GPService/gpservice.cpp#L106-L109
https://github.com/yuezk/GlobalProtect-openconnect/blob/ccaf93ec3123e40bbcf48b575c2712189291b72b/GPClient/gpclient.cpp#L147-L159

**Comment by saulgodino** [comment]
Here same problem with Zorin OS 15.3.

**Comment by danys94** [comment]
> Same here, VPN works, but it shows still as Connecting.. I have noticed it happens to me only on some systems. For example it doesn't happen on Linux Mint 20.X, but its happening on Linux Manjaro (arch-based system)

It was happening on my Manjaro, but now after some time of usage (probably I have installed some package which I am not aware off, that helped) it is working correctly now. :-D

**Comment by mlwdofc** [comment]
Same here.  Fresh install Linux Mint 20.1 on desktop shows "Connecting" although it truly is connected.  Interestingly, a fresh install of Linux Mint 20.1 on my laptop does not demonstrate this same behavior.

**Comment by conradogarciaberrotaran** [comment]
same issue here in ubuntu 20.04

**Comment by dmitriy-geels** [comment]
everyone suffering from this bug, here is a workaround (and a cause): https://github.com/yuezk/GlobalProtect-openconnect/issues/62#issuecomment-996083717

**Comment by kyechou** [comment]
The issue should be resolved in the merged PR #124.
