### ISSUE TITLE
How to use a client certificate?

### ISSUE THREAD

**Issue by dmgeurts** [yuezk/GlobalProtect-openconnect#437]
How can a client certificate be configured for a global protect connection? I've found inspections for openconnect on the cli, but need a way to preconfigure a user client certificate (Linux). The UI doesn't list any certificate options and the portal doesn't distribute it, so pre configuration is required.

**Comment by yuezk** [comment]
@dmgeurts 

For the CLI, you can pass the certificate via the `-c, --certificate` parameter
```
  -c, --certificate <CERTIFICATE>
          Use SSL client certificate file in pkcs#8 (.pem) or pkcs#12 (.p12, .pfx) format
  -k, --sslkey <SSLKEY>
          Use SSL private key file in pkcs#8 (.pem) format
  -p, --key-password <KEY_PASSWORD>
```

For GUI, you can configure the certificate in the settings panel.

<img width="798" alt="image" src="https://github.com/user-attachments/assets/ed0fb759-bee6-433a-8d8c-c60ee62a9aea">

**Comment by dmgeurts** [comment]
When adding the p12 certificate I now get this error:

```
builder error: error:0308010C:digital envelope
routines:inner_evp_generic_fetch:unsupported:crypto/evp/evp_fetch.c:342:Global
default library context, Algorithm (RC2-40-CBC : 0), Properties ()
```

![image](https://github.com/user-attachments/assets/f2c20da5-d2f6-4f35-a610-c4917e607d57)

**Comment by dmgeurts** [comment]
Connecting manually with openconnect works fine so it looks like gpgui isn't happy about something.

**Comment by yuezk** [comment]
Hi @dmgeurts, what the command do you use with openconnect?

**Comment by yuezk** [comment]
Hi @dmgeurts, it looks like the algorithm is not supported. You can following this to see if it works for you.

https://stackoverflow.com/questions/72859711/convert-an-old-style-p12-to-pem-unsupported-algorithm-rc2-40-cbc

**Comment by yuezk** [comment]
Try edit `~/.config/gpgui/openssl.cnf` and append the following content:

```
[default_sect]
activate = 1
[legacy_sect]
activate = 1

[provider_sect]
default = default_sect
legacy = legacy_sect
```

Then quit the client and restart it.

Reference: https://stackoverflow.com/questions/72859711/convert-an-old-style-p12-to-pem-unsupported-algorithm-rc2-40-cbc

**Comment by dmgeurts** [comment]
The openconnect command, no need to convert the pkcs certificate for openconnect. The certificate is generated on a Palo Alto firewall:

`sudo openconnect --protocol=gp --server=vpn.domain.com -u user -c Documents/VPN/user_cert.p12 -p <pwd>`

Editing the openssl.cnf file hasn't made a difference.

**Comment by dmgeurts** [comment]
The -legacy flag is indeed needed:

```
$ openssl pkcs12 -in Documents/VPN/user_cert.p12 -nodes
Enter Import Password:
Error outputting keys and certificates
2080E47329F60000:error:0308010C:digital envelope routines:inner_evp_generic_fetch:unsupported:../crypto/evp/evp_fetch.c:386:Global default library context, Algorithm (RC2-40-CBC : 0), Properties ()
```

**Comment by dmgeurts** [comment]
I also tried adding this to the openssl.cnf  file, but still no dice when trying to save the gpgui config with a legacy pkc12 file.

```
[openssl_init]
providers = provider_sect
```

**Comment by dmgeurts** [comment]
If I convert the legacy p12 to a current/normal pkcs12, the error disappears when saving the gpgui config.

**Comment by yuezk** [comment]
>If I convert the legacy p12 to a current/normal pkcs12, the error disappears when saving the gpgui config.

Then can you connect the VPN in the gui client?

**Comment by dmgeurts** [comment]
Indeed, the VPN connects successfully when using the non-legacy pkcs12 certificate. Can gpgui be made to not throw an error for legacy pkcs12 certificates?

**Comment by yuezk** [comment]
> If I convert the legacy p12 to a current/normal pkcs12, the error disappears when saving the gpgui config.

I will check. Can you post the command you use to convert the certificate?

**Comment by dmgeurts** [comment]
In a nutshell: 

```
openssl pkcs12 -legacy -in legacy.p12 -out temp.pem -nodes -passin pass:<pass>
openssl pkcs12 -legacy -in legacy.p12 -nocerts -out temp.key -passin pass:<pass> -passout pass:<pass>
openssl pkcs12 -export -out new.p12 -inkey temp.key -in temp.pem -passin pass:<pass> -passout pass:<pass>
```

**Comment by dmgeurts** [comment]
Much appreciated.

If it was just me, converting the legacy pkcs would be fine, but I'd like to avoid the process of having to convert the certificate when detailing VPN agent deployment and configuration for others.

**Comment by h4cking4fun** [comment]
I'll check if I'm able to process the legacy certificate in the code.

**Comment by h4cking4fun** [comment]
I'll check if I'm able to process the legacy certificate in the code.

**Comment by yuezk** [comment]
I'll check if I'm able to process the legacy certificate in the code.

**Comment by yuezk** [comment]
Released in 2.3.9. You should remove the `~/.config/gpgui/openssl.cnf` first and restart the client.

**Comment by dmgeurts** [comment]
I've updated to 2.3.9 but still get the same error, after deleting the `openssl.cnf` file, should it be regenerated?

**Comment by yuezk** [comment]
It will be regenerated automatically. If it doesn't regenerate, then you may not quit it entirely, because closing the close button won't quit it. You should click the quit menu from the hamburger menu.

**Comment by dmgeurts** [comment]
Hmmm, it's not regenerated. What's the content of this file meant to be? I should've just moved it instead of deleting it.

**Comment by dmgeurts** [comment]
Rebooted, quit using the hamburger and then reinstalled it. It still throws the same error when using a legacy format pkcs12 certificate and no openssl.cnf file generated.

**Comment by yuezk** [comment]
I forgot to mention that the `Enable OpenSSL Legacy Mode` should also be checked.

<img width="638" alt="image" src="https://github.com/user-attachments/assets/ad5fd011-bfc5-4a1f-89cd-7c9548f67d7a">
