### ISSUE TITLE
help parameter missing

### ISSUE THREAD

**Issue by kringalf** [yuezk/GlobalProtect-openconnect#44]
It would be nice to get some parameters like:
* help
* username
* password
* server
* mtu
* token-mode (from openconnect)
* token-secret (from openconnect)

**Comment by yuezk** [comment]
2.x has more options available. Closing.

**Comment by CodingKittens247** [comment]
How is this closed if there's no password param?

**Comment by yuezk** [comment]
We won't port all the openconnect parameters. Use `--passwd-on-stdin` if you want to provide the password.
