### ISSUE TITLE
Refactor constant URL parameters in a single place.

### ISSUE THREAD

**Issue by hrk** [yuezk/GlobalProtect-openconnect#48]
Currently, there are some constant URL parameters that are hardcoded in the code in the files GPClient/{loginparams.cpp,portalauthenticator.cpp,gatewayauthenticator.cpp}.

Especially clientos, os-version and version are three common parameters that should be refactored to be in a single place and (at a future date) customizable.

**Comment by yuezk** [comment]
No longer a problem, closing.
