### ISSUE TITLE
Fails on VPNs with multiple gateways.

### ISSUE THREAD

**Issue by frsilent** [yuezk/GlobalProtect-openconnect#5]
When connecting to a VPN with multiple gateways I receive the error:
`This does not appear to be a SAML prelogin response (<saml-auth-method> or <saml-request> tags missing)`

Will try to look into it more this weekend but believe that additional branching logic might need to be added based on the prelogin response containing a list of gateways.

**Comment by kerry-perret** [comment]
@frsilent yup this is exactly that!

A workaround is to actually setup one of the gateways addresses right in the portal text box.

In my case the portal address with the official GP Windows Client is something like:
`vpn.xxxxx.somextension`

and I know that one of the gateways returned when playing with `openconnect` is `gateway1`

So I just ended up typing something like:
`gateway1.xxxxx.somextension`

And it works like a charm!

**Comment by dlenski** [comment]
> Will try to look into it more this weekend but believe that additional branching logic might need to be added based on the prelogin response containing a list of gateways.

In fact, the issue in this case must be that the SAML is done _only_ in the gateway interface and _not_ in the portal interface.

Go to `https://the.portal.server/global-protect/prelogin.esp`, and you'll see no SAML tags, then go to `https://any.gateway.server/ssl-vpn/prelogin.esp`, and you'll see SAML tags.

This is a bit of an odd setup… when you connect from a Windows client, how does it require you to authenticate? (GlobalProtect's strange design makes it possibly to setup the portal and gateway interfaces in strangely divergent ways, often a source of security holes). 

(I'm the author of the core GlobalProtect support in OpenConnect.)

**Comment by yuezk** [comment]
@dlenski Thanks for your explanation. Looks like you have already implemented it in [gp-saml-gui](https://github.com/dlenski/gp-saml-gui), I’d like to ship it as well, but I have no environment to test it with.

**Comment by yuezk** [comment]
Hi, @dlenski I tested the portal interface (https://vpn.xxx.com/global-protect/prelogin.esp) on my VPN server, after authentication, the `portal-userauthcookie` field didn't appear in the response headers. Do you have any idea about this?

![image](https://user-images.githubusercontent.com/3297602/81502732-484e3200-9312-11ea-9e0b-d8f02d0e3711.png)

**Comment by yuezk** [comment]
I see. I should set the UA to `PAN GlobalProtect`, then I can get the `portal-userauthcookie`.

**Comment by dlenski** [comment]
> Hi, @dlenski I tested the portal interface (https://vpn.xxx.com/global-protect/prelogin.esp) on my VPN server, after authentication, the `portal-userauthcookie` field didn't appear in the response headers. Do you have any idea about this?

I'm a bit confused. How do you _usually_ do this? Your app instructs users to "Please enter your **portal** address" in the main window, _not_ the gateway address.

> I see. I should set the UA to PAN GlobalProtect, then I can get the portal-userauthcookie.

Your server responds to SAML on portal interface differently if the UA *isn't* `PAN GlobalProtect`? Are you sure about this?

We've kept this UA string in `gp-saml-gui.py` and in OpenConnect, but I haven't actually seen a server in a long time where it behaves differently with this UA string. Can you confirm?

**Comment by dlenski** [comment]
One of the things I'm hoping you or your users can figure out is _how the portal hands off to the gateway_ in the case where you do SAML authentication to the portal rather than the gateway.

The only GP+SAML VPN that I have access to does SAML authentication to the _gateway_, so I can't effectively test this. It's pretty much the only missing piece in fully understanding GP protocol.

**Comment by yuezk** [comment]
> I'm a bit confused. How do you usually do this? Your app instructs users to "Please enter your portal address" in the main window, not the gateway address.

I had an misleading on the input box, it should be "Please enter your **gateway** address", not the portal address.

**Comment by yuezk** [comment]
I will add the support for the multiple gateways in the future, and we can use @kerry-perret solution as the workaround for now.

**Comment by yuezk** [comment]
I have added the support for multiple gateways in #9

The workflow is the same as the official client in macOS.

1. Request the `/global-protect/preloing.esp` to get the `region` value
2. Filter out the matched gateway from the gateways returned in `/global-protect/getconfig.esp` by the `region` value.
3. Connect to the best matched gateway.

**Comment by yuezk** [comment]
Also supports switching gateway manually from the system tray menu.

![image](https://user-images.githubusercontent.com/3297602/82757078-b87bae00-9e10-11ea-9c35-1201d0b88ca8.png)

**Comment by kerry-perret** [comment]
@yuezk awesome! Thanks!
