### ISSUE TITLE
How do you start the client on debian?

### ISSUE THREAD

**Issue by qups** [yuezk/GlobalProtect-openconnect#50]
How do you start the client? Thank you.

**Comment by yuezk** [comment]
@qups You might need to build it by yourself from the source code. Here is the steps: https://github.com/yuezk/GlobalProtect-openconnect#debian-package

**Comment by VJatla** [comment]
Hi,
I am running MX Linux 21 (not systemd) and after installing I did the following,
```bash
# I opened one terminal and run
gpservice
# In another terminal
gpclient
```
And I logged in and it works.
