### ISSUE TITLE
Build Erro..! Doesn't compiler

### ISSUE THREAD

**Issue by jreo** [yuezk/GlobalProtect-openconnect#59]
I'm try to compile source, but receive this erro below..!

/usr/bin/ld: main.o: na função "main.cold":
main.cpp:(.text.unlikely+0xa3): reference not defined for  "SingleApplication::~SingleApplication()"
/usr/bin/ld: main.o: in function  "main":
main.cpp:(.text.startup+0x2a2): reference not defined for  "SingleApplication::SingleApplication(int&, char**, bool, QFlags<SingleApplication::Mode>, int, QString const&)"
/usr/bin/ld: main.cpp:(.text.startup+0x2d3): reference not defined for  "SingleApplication::instanceStarted()"
/usr/bin/ld: main.cpp:(.text.startup+0x35e): reference not defined for  "SingleApplication::staticMetaObject"
/usr/bin/ld: main.cpp:(.text.startup+0x38e): reference not defined for  "SingleApplication::~SingleApplication()"
collect2: error: ld returned 1 exit status
make[1]: *** [Makefile:238: gpclient] Erro 1
make[1]: Saindo do diretório '/usr/src/GlobalProtect-openconnect-master/GPClient'
make: *** [Makefile:48: sub-GPClient-make_first] Erro 2
root@BBWL0607-LNX:/usr/src/GlobalProtect-openconnect-master# 

O.S: Ubuntu 20.10.1

any ideas to solve?

**Comment by yuezk** [comment]
No idea about this error. Did you follow the steps in README?

**Comment by yuezk** [comment]
Looks like the submodules are not updated. Please run `git submodule update --init` first.

**Comment by yuezk** [comment]
Your source folder is `GlobalProtect-openconnect-master`, did you download it as Zip instead of following the steps here? https://github.com/yuezk/GlobalProtect-openconnect#build-from-source-code

I'm closing this and feel free to reopen it if you still encounter problems with the steps above.
