### ISSUE TITLE
cant find executable in arch

### ISSUE THREAD

**Issue by jamelwa** [yuezk/GlobalProtect-openconnect#6]
im using arch linux with no desktop environment (i3 only) and installed this package from aur. but i cant find this executeable in my bin directories? how do i run this?

**Comment by yuezk** [comment]
This client is for the desktop environment, it might not work properly if you don't have a desktop environment.

By the way, the binary bin locates at `/usr/bin/gpclient`

**Comment by jamelwa** [comment]
ah thank you i just found out that executable name is gpc after builidng it from source. by the way when i tried to launch, it says not connected. should i try it in de?

**Comment by yuezk** [comment]
I'm not sure why the executable name is gpc. Of cause, you should try it in de as this client was designed for de.

**Comment by jamelwa** [comment]
it says Prelogin request error:  QNetworkReply::OperationCanceledError

**Comment by yuezk** [comment]
Can you open the link in the browser and see the response?

`https://<vpn.example.com>/ssl-vpn/prelogin.esp`
