### ISSUE TITLE
Can't sign in to Microsoft SAML (unknown device)

### ISSUE THREAD

**Issue by Andreas85** [yuezk/GlobalProtect-openconnect#63]
I'm able to install and connect just fine, but when I try to log in to Microsoft I get the following error:

![Screenshot from 2021-05-18 07-55-37](https://user-images.githubusercontent.com/919843/118598601-9b24ba00-b7ae-11eb-9f37-7444302293d2.png)

I saw something in some other issue about connecting with the --os=win parameter for openconnect but even recompiling with that parameter didn't work.

How does Microsoft know what OS I'm connecting from? 

How can I fix this?

**Comment by yuezk** [comment]
@Andreas85 Looks like MS did UA sniffing to detect the device. And in this project, the User-Agent of the webview that used to load the login page the default value. But it can be set to other values manually.

Try to add the following code after [samlloginwindow.cpp#L17](https://github.com/yuezk/GlobalProtect-openconnect/blob/266ab658922b76844c0c8c58cde43d219e37da04/GPClient/samlloginwindow.cpp#L17) and recompile the project to see if it works.

```c++
webView->profile()->setHttpUserAgent("Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36");
```

**Comment by yuezk** [comment]
No longer a problem in the latest 2.x release. You could try to use the external browser to do authentication. Closing.
