### ISSUE TITLE
Microsoft Authentication: SAML Issue

### ISSUE THREAD

**Issue by Hugobsb** [yuezk/GlobalProtect-openconnect#64]
Any idea of what is going on? I've also tried [this one](https://github.com/dlenski/gp-saml-gui) with Windows and Linux flag, but I still got the same error.

![image](https://user-images.githubusercontent.com/58279735/119843474-f9077f00-bedd-11eb-9611-c73d5b4f134e.png)

**Comment by bandogora** [comment]
Have you tried selecting "Reset" from system tray menu? There's a known issue (#120) that requires many users to have to reset before every connect.

**Comment by bandogora** [comment]
> No idea lol I've already left the company that required this VPN a long time ago.

Gotcha, it's probably safe to close this issue then.
