### ISSUE TITLE
Can not clear use/session

### ISSUE THREAD

**Issue by karlos1337** [yuezk/GlobalProtect-openconnect#66]
I need to swap my user on the same domain but I couldn't find the option to do it nor for clearing the session/cache/whatever.
I guess should be some file somewhere in my system that store my user/password but couldn't find it in `.local/share/gpclient ` and removing `.cache/GlobalProtect-openconnect` neither solve the problem, the credentials remain.

**Comment by yuezk** [comment]
The client itself doesn't cache the credentials. I guess it should be the WebView the client launched that cached the authentication status (i.e., the cookie in the WebView).

**Comment by karlos1337** [comment]
Could be great to add some option for forcing this but removing the folder solve my problem anyway, thank you so much :)

**Comment by yuezk** [comment]
Would like to add this feature in the future. Thanks for your advice.
