### ISSUE TITLE
Add HIP report script option

### ISSUE THREAD

**Issue by lucianlepadatu** [yuezk/GlobalProtect-openconnect#7]
Hello,

Is there any chance of adding a HIP report script option to pass it to openconnect via "--csd-wrapper" argument?

**Comment by yuezk** [comment]
Yes, you can open `/etc/systemd/system/systemd/gpservice.service` and append any arguments supported by the openconnect cli to `/usr/bin/gpservice`, including the `--csd-wrapper` argument.

https://github.com/yuezk/GlobalProtect-openconnect/blob/76a4977e9260a8123c39fc439944355ff6bff9aa/GPService/systemd/gpservice.service#L7

**Comment by lucianlepadatu** [comment]
cool, thanks. works as expected.
