### ISSUE TITLE
Build from source error

### ISSUE THREAD

**Issue by sharifelguindi** [yuezk/GlobalProtect-openconnect#78]
Hello -

Great project, thanks.  I received this error when trying to build from source in the make step:

gpservice.cpp: In member function ‘void GPService::connect(QString, QString, QString, QString)’:
gpservice.cpp:68:19: error: ‘splitCommand’ is not a member of ‘QProcess’
   68 |      << QProcess::splitCommand(extraArgs)
      |                   ^~~~~~~~~~~~
make[1]: *** [Makefile:498: gpservice.o] Error 1
make[1]: Leaving directory '/home/sharif/Downloads/GlobalProtect-openconnect/GPService'
make: *** [Makefile:73: sub-GPService-make_first] Error 2

This same error showed up trying to build the deb package.

I ended up removing the line it was failing at: gpservice.cpp:68:19 regarding the splitCommand for QProcess.  Does that work for you? The Qdocumentation doesn't mention this function, but I am not versed in this package at all.

I'm on Ubuntu Budgie, 20.04 LTS.  I followed the openconnect and Qt package installs w/ appropriate versions. No issue there.

In any case, I removed the line and it was able to build, and it works! not sure what that code line was doing.  I am connecting via a 2-factor auth w/ third party so maybe because I'm not using a username/password the app doesn't complain.

In any case, that was my experience - thank you!

**Comment by yuezk** [comment]
Please make sure the Qt on your system is at least `5.15` since the `spitCommand` method was introduced in `5.15`, see https://doc.qt.io/qt-5/qprocess.html#splitCommand

**Comment by iliatcymbal** [comment]
I have the same issue on _linux mint 20.2_
And the Qt version is 5.12.8
How I can upgrade it to 5.15, I've made installation according to README instructions?
```
sudo apt install qtbase5-dev libqt5websockets5-dev qtwebengine5-dev qttools5-dev debhelper
```

Actually GlobalProtect was installed even with `‘splitCommand’ is not a member of ‘QProcess’` error, but it's freezing after authentication in _Connecting_ state

**Comment by yuezk** [comment]
I will port the `splitCommand` from the Qt base to this repo, so it won't rely on 5.15.

**Comment by iliatcymbal** [comment]
@yuezk is it possible to use GlobalProtect with Qt6?

**Comment by yuezk** [comment]
@iliatcymbal I haven't tested it on with the Qt6 environment yet.

**Comment by iliatcymbal** [comment]
Anyway, thanks for your help!

**Comment by yuezk** [comment]
@sharifelguindi @iliatcymbal Ported the `splitCommand` method in #79, it supports Qt 5.12 now.

**Comment by sharifelguindi** [comment]
Wow thank you! I will test this out today, I appreciate the help!
