### ISSUE TITLE
SAML auth succeeds, but openconnect fails to get config

### ISSUE THREAD

**Issue by terminalmage** [yuezk/GlobalProtect-openconnect#8]
When running gpclient in the terminal, this is what I see:

```
"Openconnect started successfully, PID=136056"
"[2020-05-01 19:46:39] POST https://my.portal.server/ssl-vpn/prelogin.esp?tmp=tmp&clientVer=4100&clientos=Linux\n"
"[2020-05-01 19:46:39] Connected to XXX.XXX.XXX.XXX:443\n"
"[2020-05-01 19:46:39] SSL negotiation with my.portal.server\n"
"[2020-05-01 19:46:40] Connected to HTTPS on my.portal.server\n"
"SAML login is required via REDIRECT to this URL:\n\thttps://login.microsoftonline.com/REDACTEDnEnter login credentials\n"
"[2020-05-01 19:46:40] POST https://my.portal.server/ssl-vpn/login.esp\n"
"[2020-05-01 19:46:40] GlobalProtect login returned authentication-source=XXXXXXX-SAML\n[2020-05-01 19:46:40] POST https://my.portal.server/ssl-vpn/getconfig.esp\n"
"[2020-05-01 19:46:40] Matching client config not found\nCreating SSL connection failed\n"
"Openconnect process exited with code 1 and exit status NormalExit"
```

I am able to complete the SAML login prompt (including 2FA authentication), but it disconnects shortly afterward. I took the redirect URL and opened it in my browser, did the auth there, and then from the auth'ed session I navigated to the `getconfig.esp` URL and saw an almost empty page with no visible text. Upon viewing the source of this page, it simply said `errors getting SSL/VPN config`.

Please let me know if there's anything I can do to get you more useful information.

**Comment by yuezk** [comment]
Hi, @terminalmage Sorry for the late response.

I have never encountered your problem, looks like `"[2020-05-01 19:46:40] Matching client config not found\nCreating SSL connection failed\n"` is the key to this failure.

I [searched for the error message](https://www.google.com/search?q=Matching+client+config+not+found&oq=Matching+client+config+not+found&aqs=chrome..69i57&sourceid=chrome&ie=UTF-8) and found that it should be an error message returned by the VPN server. So this might be a problem of the VPN server configuration.

BTW, have you ever tried to use https://github.com/dlenski/gp-saml-gui to connect to the VPN server? It has a better support on the portal interface.

**Comment by terminalmage** [comment]
OK, if it's a VPN configuration issue I don't think I'll get anyone to fix it. As far as I know, Linux is not officially supported. The reason I was trying to use GlobalProtect-openconnect is because Palo Alto's Linux GUI is awful.

I had not heard of the other project, but I'll give that a look, thanks!

**Comment by terminalmage** [comment]
The other tool also passed the SAML login but failed with the same "client config" error.

I'll try connecting on an OS other than Windows and make sure it's not just something stupid like my account not being enabled on this VPN.

I'm trying to use my company's new GP VPN, since my company's old VPN will no longer work at some point. So to be honest, I've never successfully connected to it, even from Windows.

**Comment by yuezk** [comment]
Closing this as this looks more like a problem of VPN server.
