### ISSUE TITLE
Upgrading Issues - Incompatibilities between gpclient and gpservice

### ISSUE THREAD

**Issue by murph** [yuezk/GlobalProtect-openconnect#82]
When I upgraded from v1.2.9 to v.1.3.0, connecting just started silently failing.

It took me an hour to debug that b4f9cfae6713a94d10f93d0d12a5cd08906bb222 had changed the interface to gpservice, and the old (v.1.2.9) gpservice was still running after i closed the client. So it'd connect up to the "vpn->connect" call which would get silently dropped.

I'm fine now, so feel free to close or keep this issue, but I wanted to share incase there's a way to notice incompatibility and error or restart gpservice.

**Comment by yuezk** [comment]
Thanks for report this. And yes, as you said I did some enhancement on the `gpservice`, the user needs to restart the service to make it effective. For example:

```
sudo systemctl restart gpservice
```

I will keep this issue opening for a while and add the instructions in the README
