### ISSUE TITLE
cafile

### ISSUE THREAD

**Issue by brjadams** [yuezk/GlobalProtect-openconnect#84]
passing cafile as part of custom parameters?

**Comment by yuezk** [comment]
@brjadams What do you mean by cafile? Is it the certificate file passed to the OpenConnect CLI?

**Comment by brjadams** [comment]
i ended up using gp_saml_gui.py, and was able to pass a certificate via teh --cafile argument as such: 

gp_saml_gui.py \
  --gateway \
  --pkexec-openconnect \
  --clientos=Windows \
  --no-verify myvpn.domain.com -- \
  --cafile=${HOME}/Documents/DigiCertTLSRSASHA2562020CA1-1.crt.pem

I was not able to connect with your program and I believe the difference to be the ability to pass that cert.

**Comment by yuezk** [comment]
I see, the cafile is used by the webview to load the web page, instead of passing to the OpenConnect CLI, so the custom parameter doesn't work.
