### ISSUE TITLE
Freeebsd Support

### ISSUE THREAD

**Issue by xgupta** [yuezk/GlobalProtect-openconnect#90]
Hi I am trying to build it on freebsd. But getting  few errors

 fatal error: 'QtCore/QElapsedTimer' file not found
#include <QtCore/QElapsedTimer>
         ^~~~~~~~~~~~~~~~~~~~~~
1 error generated.

I have installed all qt packages. Do I need to path, I first time building qt based project.

**Comment by xgupta** [comment]
Sorry, I found the way where openconnect have gp protocol mode which can be use as alternative. 
But thanks for creating this project.

**Comment by outpaddling** [comment]
FYI, this is just a matter of installing the proper Qt components before building.
Soon it won't matter, though.  I'm currently testing an official FreeBSD port, which should be committed soon.  WIP version available here:
[https://github.com/outpaddling/freebsd-ports-wip](https://github.com/outpaddling/freebsd-ports-wip)
