### ISSUE TITLE
Troubleshooting guide?

### ISSUE THREAD

**Issue by aallrd** [yuezk/GlobalProtect-openconnect#94]
Hello,

Thank you for this application that is already a lot nicer than the official Palo Alto GlobalProtect client on Linux.

I am trying to connect to our GlobalProtect gateway using a SAML authentication but so far I am unable to make it work.
I have installed the client on my Fedora Workstation 34 using the project's documentation and it worked without a glitch.
The first time I clicked on _Connect_ I had my company authentication webpage prompting me for my username/password but then it stayed in status _Not Connected_.
Clicking on _Connect_ now shows _Authenticating..._ then it brings out a pop-up that closes very fast and _Not Connected_ again.

Running `gpclient` in my terminal prints the below output and bring out the GUI:
```
2021-09-24 11:43:21.464 INFO  [80208] [main@25] GlobalProtect started, version: 1.3.3
```
There is no troubleshooting guide and I would like to know:
- I cannot find the logs for the application, do you know where I can get them ?
- Do you have a checklist of most common issues ?

**Comment by yuezk** [comment]
The log file locates at `~/.cache/GlobalProtect-openconnect/gpclient.log`.

**Comment by aallrd** [comment]
Thank you !
I have opened https://github.com/yuezk/GlobalProtect-openconnect/pull/95 to document this location.

**Comment by hjaltioj** [comment]
Hi
my log file says this?:
VPN connectivity may be disabled or limited without HIP report submission.
You need to provide a --csd-wrapper argument with the HIP report submission script.

Does anyone know what i can do to make it work?

**Comment by yuezk** [comment]
@hjaltioj I have the same warning, but it doesn't affect my VPN connectivity, so I just ignored it. Does it affect yours?

**Comment by hjaltioj** [comment]
> @hjaltioj I have the same warning, but it doesn't affect my VPN connectivity, so I just ignored it. Does it affect yours?

I can connect but thats it, no internet og gateway. :(
